In [1]:
# import libraries

import pymupdf
import spacy
import re
import pandas as pd
import numpy as np
#import unicodedata
import os
from pathlib import Path
from translate import Translator

In [4]:
!python3 -m spacy download es_core_news_lg

Collecting es-core-news-lg==3.8.0
  Downloading es_core_news_lg-3.8.0-py3-none-any.whl (568.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 568.0/568.0 MB 4.2 MB/s  0:02:080:00:0100:04

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
✔ Download and installation successful
You can now load the package via spacy.load('es_core_news_lg')

In [2]:
# nlp piplines from spacy for the 3 languages. large chosen for the higher dimension word vector libraries

nlp_en = spacy.load('en_core_web_lg')
nlp_pt = spacy.load('pt_core_news_lg')
nlp_es = spacy.load('es_core_news_lg')

In [3]:
# lists of green bond category words for usse in spacy similarity method 

not_re_cat_words_en = ['efficiency', 'retrofit', 'pollution', 'waste', 'land', 'agriculture', 'forestry', 'forest', 
                      'fisheries', 'food', 'terrestrial', 'aquatic', 'biodiversity', 'conservation', 'transportation', 
                      'electric', 'battery', 'EV', 'charger', 'bus', 'rail', 'train', 'car', 'vehicle', 'bicycle', 
                      'non-motorized', 'aviation', 'water', 'potable', 'wastewater', 'sanitation', 'treatment', 
                      'adaptation', 'disaster', 'circular', 'recycle', 'reuse','buildings', 'appliances', 'housing']

all_cat_words_en = ['renewable', 'solar', 'wind', 'bioenergy', 'biofuel', 'biomass', 'hydropower', 'hydrogen', 
                     'hydroelectric', 'power', 'grid', 'transmission', 'generation', 'efficiency', 'retrofit', 'pollution',
                    'waste', 'land', 'agriculture', 'forestry', 'forest', 'fisheries', 'food', 'terrestrial', 'aquatic',
                    'biodiversity', 'conservation', 'transportation', 'electric', 'battery', 'EV', 'charger', 'bus',
                    'rail', 'train', 'car', 'vehicle', 'bicycle', 'non-motorized', 'aviation', 'water', 'potable',
                    'wastewater', 'sanitation', 'treatment', 'adaptation', 'disaster', 'circular', 'recycle',
                    'reuse','buildings', 'appliances', 'housing']

renewable_energy_en = ['renewable', 'solar', 'wind', 'bioenergy', 'biofuel', 'biomass', 'hydropower', 'hydrogen', 'hydroelectric', 'power', 'grid', 'transmission', 'generation']
energy_efficiency_en = ['efficiency', 'retrofit']
pollution_prevention_and_control_en = ['pollution', 'waste']
environmentally_sustainable_management_of_living_natural_resources_and_land_use_en = ['land', 'agriculture', 'forestry', 'forest', 'fisheries', 'food']
terrestrial_and_aquatic_biodiversity_conservation_en = ['terrestrial', 'aquatic', 'biodiversity', 'conservation']
clean_transportation_en = ['transportation', 'electric', 'battery', 'EV', 'charger', 'bus', 'rail', 'train', 'car', 'vehicle', 'bicycle', 'non-motorized', 'aviation']
sustainable_water_and_wastewater_management_en = ['water', 'potable', 'wastewater', 'sanitation', 'treatment']
climate_change_adaptation_en = ['adaptation', 'disaster']
circular_economy_and_or_ecoefficient_projects_en = ['circular', 'recycle', 'reuse']
green_buildings_en = ['buildings', 'appliances', 'housing']

In [4]:
# iterate each word in the lists through the Translator from translate - English to Portuguese

not_re_cat_words_pt = []
all_cat_words_pt = []
renewable_energy_pt = []
energy_efficiency_pt = []
pollution_prevention_and_control_pt = []
environmentally_sustainable_management_of_living_natural_resources_and_land_use_pt = []
terrestrial_and_aquatic_biodiversity_conservation_pt = []
clean_transportation_pt = []
sustainable_water_and_wastewater_management_pt = []
climate_change_adaptation_pt = []
circular_economy_and_or_ecoefficient_projects_pt = []
green_buildings_pt = []


translator = Translator(to_lang='pt',from_lang='en')
# for word in not_re_cat_words_en:
    # translation = translator.translate(word)
    # not_re_cat_words_pt.append(translation)
for word in all_cat_words_en:
    translation = translator.translate(word)
    all_cat_words_pt.append(translation)
for word in renewable_energy_en:
    translation = translator.translate(word)
    renewable_energy_pt.append(translation)
for word in energy_efficiency_en:
    translation = translator.translate(word)
    energy_efficiency_pt.append(translation)
for word in pollution_prevention_and_control_en:
    translation = translator.translate(word)
    pollution_prevention_and_control_pt.append(translation)
for word in environmentally_sustainable_management_of_living_natural_resources_and_land_use_en:
    translation = translator.translate(word)
    environmentally_sustainable_management_of_living_natural_resources_and_land_use_pt.append(translation)
for word in terrestrial_and_aquatic_biodiversity_conservation_en:
    translation = translator.translate(word)
    terrestrial_and_aquatic_biodiversity_conservation_pt.append(translation)
for word in clean_transportation_en:
    translation = translator.translate(word)
    clean_transportation_pt.append(translation)
for word in sustainable_water_and_wastewater_management_en:
    translation = translator.translate(word)
    sustainable_water_and_wastewater_management_pt.append(translation)
for word in climate_change_adaptation_en:
    translation = translator.translate(word)
    climate_change_adaptation_pt.append(translation)
for word in circular_economy_and_or_ecoefficient_projects_en:
    translation = translator.translate(word)
    circular_economy_and_or_ecoefficient_projects_pt.append(translation)
for word in green_buildings_en:
    translation = translator.translate(word)
    green_buildings_pt.append(translation)

In [5]:
# iterate each word in the lists through the Translator from translate - English to Spanish

not_re_cat_words_es = []
all_cat_words_es = []
renewable_energy_es = []
energy_efficiency_es = []
pollution_prevention_and_control_es = []
environmentally_sustainable_management_of_living_natural_resources_and_land_use_es = []
terrestrial_and_aquatic_biodiversity_conservation_es = []
clean_transportation_es = []
sustainable_water_and_wastewater_management_es = []
climate_change_adaptation_es = []
circular_economy_and_or_ecoefficient_projects_es = []
green_buildings_es = []


translator = Translator(to_lang='es',from_lang='en')
# for word in not_re_cat_words_en:
    # translation = translator.translate(word)
    # not_re_cat_words_es.append(translation)
for word in all_cat_words_en:
    translation = translator.translate(word)
    all_cat_words_es.append(translation)
for word in renewable_energy_en:
    translation = translator.translate(word)
    renewable_energy_es.append(translation)
for word in energy_efficiency_en:
    translation = translator.translate(word)
    energy_efficiency_es.append(translation)
for word in pollution_prevention_and_control_en:
    translation = translator.translate(word)
    pollution_prevention_and_control_es.append(translation)
for word in environmentally_sustainable_management_of_living_natural_resources_and_land_use_en:
    translation = translator.translate(word)
    environmentally_sustainable_management_of_living_natural_resources_and_land_use_es.append(translation)
for word in terrestrial_and_aquatic_biodiversity_conservation_en:
    translation = translator.translate(word)
    terrestrial_and_aquatic_biodiversity_conservation_es.append(translation)
for word in clean_transportation_en:
    translation = translator.translate(word)
    clean_transportation_es.append(translation)
for word in sustainable_water_and_wastewater_management_en:
    translation = translator.translate(word)
    sustainable_water_and_wastewater_management_es.append(translation)
for word in climate_change_adaptation_en:
    translation = translator.translate(word)
    climate_change_adaptation_es.append(translation)
for word in circular_economy_and_or_ecoefficient_projects_en:
    translation = translator.translate(word)
    circular_economy_and_or_ecoefficient_projects_es.append(translation)
for word in green_buildings_en:
    translation = translator.translate(word)
    green_buildings_es.append(translation)

In [6]:
# find tables in the document and return table info
# pdfname: https://www.geeksforgeeks.org/python/get-filename-from-path-without-extension-using-python/

def catTable(document, tableStrategy):
    
    pdf = pymupdf.open(document) 
    filename = os.path.basename(document)
    pdfname = filename.split('.',1)[0]

    tableCount = 0
    tablePages = []
    tableHeaders = []
    tableDFs = []


    for page_idx in range(len(pdf)): 
        page = pdf[page_idx]

        find_tables = page.find_tables(strategy = tableStrategy)
        if find_tables.tables:
            table_count = len(find_tables.tables)
            tableheader = find_tables[0].header.names # assume only 1 table per page
            tableDF = find_tables[0].to_pandas()
            tableCount += table_count
            tablePages.append(page_idx)
            tableHeaders.append(tableheader)
            tableDFs.append(tableDF)

    return filename, pdfname, tableCount, tablePages, tableHeaders, tableDFs

In [7]:
# assess the tables found in the catTable function to identify the Category tables and extract unique list of category phrases

def tableAssess(language, tableCount, tablePages, tableHeaders, tableDFs):

    if language == 'PT':
        keywordsCAT = ['Categoria']
        nlp = nlp_pt
    elif language == 'ES':
        keywordsCAT = ['Categoría', 'Categorías']
        nlp = nlp_es
    elif language == 'EN':
        keywordsCAT = ['Category', 'Categories', 'Criteria', 'Criterion']
        nlp = nlp_en
    
    tablePageCurrent = 0
    tablePagePrior = 0
    tablepageCurrentTrue = 0
    uniqueCats = []
    uniqueCatsNoDupes = []
    table_idx = []

    if tableCount == 1: # applicable if only 1 table detected in whole pdf
        dataFrame = tableDFs[0]
        header = tableHeaders[0]
        for keyword in keywordsCAT:
            if keyword.lower() in header[0].lower(): # assumes category col is always the first (LHS) col
                colName = header[0]
                uniqueC = dataFrame[colName].dropna().unique().tolist()
                for messyCat in uniqueC:
                    if messyCat:
                        tidyCat = messyCat.replace('\n',' ').lower()
                        uniqueCatsNoDupes.append(tidyCat)
                        table_idx.append(0)
    elif tableCount > 1:
        for idx in range(len(tableDFs)): # count of tableHeaders and DFs should be the same, based on the page level find_tables object
            tablePageCurrent = tablePages[idx]
            dataFrame = tableDFs[idx]
            header = tableHeaders[idx]
            for keyword in keywordsCAT:
                if keyword.lower() in header[0].lower():
                    colName = header[0]
                    uniqueC = dataFrame[colName].dropna().unique().tolist() # unique list of phrases in left hand col of table
                    tablepageCurrentTrue = tablePageCurrent
                    for messyCat in uniqueC:
                        if messyCat:
                            tidyCat = messyCat.replace('\n',' ').lower()
                            uniqueCats.append(tidyCat)
                            table_idx.append(idx)
                elif header[0] == 'Col0' and tablePageCurrent - tablepageCurrentTrue == 1: # the condition where the last keyword-compliant table processed was one page before the current table 
                    uniqueC = dataFrame['Col0'].dropna().unique().tolist()
                    if uniqueC:
                        for messyCat in uniqueC:
                            if messyCat:
                                tidyCat = messyCat.replace('\n',' ').lower()
                                uniqueCats.append(tidyCat)
                                table_idx.append(idx)
            tablePagePrior = tablePageCurrent
        uniqueCatsNoDupes = list(set(uniqueCats))

    return uniqueCatsNoDupes, table_idx

In [8]:
# clean up spurious table content and assess presence of enerygy systems

def tableClean(language, uniqueCatsNoDupes):

    sim_th_en = 0.65
    sim_th_pt = 0.65
    sim_th_es = 0.65
    cleanup_TH_en = 0.65
    cleanup_TH_pt = 0.65
    cleanup_TH_es = 0.65

    if language == 'PT':
        re = renewable_energy_pt
        not_re = not_re_cat_words_pt
        all = all_cat_words_pt
        nlp = nlp_pt
        cleanup_TH = cleanup_TH_pt
        similarity_threshold = sim_th_pt
    elif language == 'ES':
        re = renewable_energy_es
        not_re = not_re_cat_words_es
        all = all_cat_words_es
        nlp = nlp_es
        cleanup_TH = cleanup_TH_es
        similarity_threshold = sim_th_es
    elif language == 'EN':
        re = renewable_energy_en
        not_re = not_re_cat_words_en
        all = all_cat_words_en
        nlp = nlp_en
        cleanup_TH = cleanup_TH_en
        similarity_threshold = sim_th_en

    CatwordsFinal = []
    simScores_cln = {}
    notresimScores = {}
    resimScores = {}
    energy_system_tbl = ""

    if len(uniqueCatsNoDupes) > 0:
        for cat in uniqueCatsNoDupes: # phrases from tables' left hand cols
            docCat = nlp(cat) # run phrase through nlp pipeline
            for wordx in all:
                docx = nlp(wordx)
                simScore_cln = docCat.similarity(docx) # compare each cat phrase to all ref words
                if simScore_cln >= cleanup_TH: 
                    CatwordsFinal.append(cat)
                    simScores_cln[cat + ' ' + wordx] = simScore_cln
                    dfsimScores_cln = pd.DataFrame.from_dict(simScores_cln, 'index')
                    CatwordsFFinal = list(set(CatwordsFinal))
        for phrase in CatwordsFFinal: # only phrases that pass the cleanup TH
            docPhrase = nlp(phrase)
            for wordy in docPhrase:
                if wordy.has_vector:
                    for worda in re:
                        doca = nlp(worda)
                        resimScore = wordy.similarity(doca) # compare each word (token) in each cat phrase to renewable energy ref words
                        if resimScore >= similarity_threshold:
                            resimScores[worda] = resimScore
                            dfresimScores = pd.DataFrame.from_dict(resimScores, 'index')
        if resimScores:                     
            energy_system_tbl = True
        else:
            energy_system_tbl = False
            dfresimScores = pd.DataFrame()
    else:
        CatwordsFFinal = []
        dfsimScores_cln = pd.DataFrame()
        dfresimScores = pd.DataFrame()

    return CatwordsFFinal, dfsimScores_cln, dfresimScores, energy_system_tbl, cleanup_TH_en, cleanup_TH_es, cleanup_TH_pt

In [9]:
# to find the Use of Proceeds portion of the document, returns font info for key phrases that typically indicate the start and end of that portion

def fontInfo(language, document):

    results_UOP = []
    results_SEEGP = []
    
    pdf = pymupdf.open(document)
    
    if language == 'PT':
        keywordsUOP = ['Usos dos Recursos', 'Uso de Recursos']
        keywordsSEEGP = ['Selection and Evaluation', 'Process for the Project Evaluation and Selection', 'Project Evaluation and Selection Process', 'Project Selection and Evaluation Process', 'Process for Project Evaluation and Selection', 'Project Selection and Assessment Process', 'Project Selection Criteria', 'Project evaluation & selection', 'Project Selection Process']
        keywordsSEEGP_test = ['Avaliação e Seleção de Ativos', 'Processo de Avaliação e Seleção de Projetos']
    elif language == 'ES':
        keywordsUOP = ['Uso de los Fondos', 'Uso de Fondos', 'Uso de Recursos', 'Destinos de Fondos', 'Uso de los Recursos']
        keywordsSEEGP_test = ['Proceso de Evaluación y Selección de Proyectos', 'Selección y Evaluación de Proyectos', 'Procedimiento Selección', 'Evaluación y selección de proyectos']
    elif language == 'EN':
        keywordsUOP = ['Use of Proceeds', 'Use of Funds', 'Use of the Proceeds']
        keywordsSEEGP = ['Selection and Evaluation', 'Process for the Project Evaluation and Selection', 'Project Evaluation and Selection Process', 'Project Selection and Evaluation Process', 'Process for Project Evaluation and Selection', 'Project Selection and Assessment Process', 'Project Selection Criteria', 'Project evaluation & selection', 'Project Selection Process']
        keywordsSEEGP_test = ['Selection and Evaluation', 'Process for', 'Evaluation and Selection', 'Project Evaluation', 'Assessment Process', 'Selection process', 'Project selection criteria']


    for page_idx in range(len(pdf)): 
        page = pdf[page_idx]
        dict = page.get_text("dict")
        blocks = dict["blocks"] 
        for block in blocks:
            if "lines" in block.keys():
                spans = block['lines']
                for span in spans:
                    data = span['spans']
                    for lines in data:
                        for keyword in keywordsUOP:
                            if keyword.lower() in lines['text'].lower().strip():
                                results_UOP.append((lines['text'], lines['size'], lines['bbox'], page_idx))
                        for keyword in keywordsSEEGP_test:
                            if keyword.lower() in lines['text'].lower().strip():
                                results_SEEGP.append((lines['text'], lines['size'], lines['bbox'], page_idx))

                            

    return results_UOP, results_SEEGP

In [10]:
# from the results of the previous function, returns the result index containing the highest font size, assuming this is a section header 

def find_max_font(results_UOP, results_SEEGP):
    
    max_font_size_UOP = 0
    for result_idx_UOP in range(len(results_UOP)):
        resultA = results_UOP[result_idx_UOP]
        if resultA[1] > max_font_size_UOP:
            max_font_size_UOP = resultA[1]
            max_idx_UOP = result_idx_UOP

    max_font_size_SEEGP = 0
    if len(results_SEEGP) == 0:
        max_idx_SEEGP = 0
    else:       
        for result_idx_SEEGP in range(len(results_SEEGP)):
            resultB = results_SEEGP[result_idx_SEEGP]
            if resultB[1] > max_font_size_SEEGP:
                max_font_size_SEEGP = resultB[1]
                max_idx_SEEGP = result_idx_SEEGP

    return max_idx_UOP, max_idx_SEEGP

In [11]:
# corrects the UOP portion in the cases where the functions above have returned the table of contents instances of the start and end key phrases 

def tocCheck(results_UOP, results_SEEGP, max_idx_UOP, max_idx_SEEGP):
    
    if len(results_SEEGP) == 0:
        areaUOP = results_UOP[max_idx_UOP]
        areaUOP_page = areaUOP[3]
        areaUOP_coords = areaUOP[2]
        areaUOP_y1 = areaUOP_coords[3]
        areaSEEGP_page = 0
        areaSEEGP_y0 = 0

    else:
        areaUOP = results_UOP[max_idx_UOP]
        areaSEEGP = results_SEEGP[max_idx_SEEGP]
        areaUOP_page = areaUOP[3]
        areaSEEGP_page = areaSEEGP[3]
        areaUOP_coords = areaUOP[2]
        areaSEEGP_coords = areaSEEGP[2]
        areaUOP_y1 = areaUOP_coords[3]
        areaSEEGP_y0 = areaSEEGP_coords[1]

        if areaUOP_page == areaSEEGP_page:
            if 0 < areaSEEGP_y0 - areaUOP_y1 < 40:
                results_UOP_remove = results_UOP.pop(max_idx_UOP)
                results_SEEGP_remove = results_SEEGP.pop(max_idx_SEEGP)

                max_idx_UOP, max_idx_SEEGP = find_max_font(results_UOP, results_SEEGP)

                areaUOP = results_UOP[max_idx_UOP]
                areaSEEGP = results_SEEGP[max_idx_SEEGP]
                areaUOP_page = areaUOP[3]
                areaSEEGP_page = areaSEEGP[3]
                areaUOP_coords = areaUOP[2]
                areaSEEGP_coords = areaSEEGP[2]
                areaUOP_y1 = areaUOP_coords[3]
                areaSEEGP_y0 = areaSEEGP_coords[1]

    return areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0

In [12]:
# discards the UOP end boundary in cases where it comes before the start boundary

def keepSEEGP(areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0):

    if areaSEEGP_page == areaUOP_page:
        if areaSEEGP_y0 < areaUOP_y1:
            keep_areaSEEGP = False
        elif areaSEEGP_y0 > areaUOP_y1:
            keep_areaSEEGP = True
    elif areaSEEGP_page > areaUOP_page:
        keep_areaSEEGP = True
    elif areaSEEGP_page < areaUOP_page:
        keep_areaSEEGP = False

    return keep_areaSEEGP

In [13]:
# page scenarios and extract words when keep_areaSEEGP = True
# function called by another function

def wordsUOP_endPage(document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0):

    pdf = pymupdf.open(document)
    extractUOPwords = []

    # iterate pages
    for page_idx in range(len(pdf)):
        page = pdf[page_idx]

       
# process four page scenarios and extract text as words
    # A: UOP all on a single page
        if page_idx == areaUOP_page and page_idx == areaSEEGP_page:
            for word in page.get_text('words'):
                x0, y0, x1, y1, messyText, *_ = word
                if y0 > areaUOP_y1 and y1 < areaSEEGP_y0:
                    tidyText = messyText.replace('\n',' ').lower()
                    extractUOPwords.append(tidyText)

    # UOP across >1 page
    # B: current page is start page
        elif page_idx == areaUOP_page:
            for word in page.get_text('words'):
                x0, y0, x1, y1, messyText, *_ = word
                if y0 > areaUOP_y1:
                    tidyText = messyText.replace('\n',' ').lower()
                    extractUOPwords.append(tidyText)

    # D: current page is neither start nor end page but is in the UOP area
        elif page_idx > areaUOP_page and page_idx < areaSEEGP_page:
            for word in page.get_text('words'):
                x0, y0, x1, y1, messyText, *_ = word
                tidyText = messyText.replace('\n',' ').lower()
                extractUOPwords.append(tidyText)

    # C: current page is end page
        elif page_idx == areaSEEGP_page:
                for word in page.get_text('words'):
                    x0, y0, x1, y1, messyText, *_ = word
                    if y1 < areaSEEGP_y0:
                        tidyText = messyText.replace('\n',' ').lower()
                        extractUOPwords.append(tidyText)

    return extractUOPwords

In [14]:
# iterate pages in the pdf and extract words, preferrably between the UOP and SEEGP sections or else from UOP to end

def wordsUOP(keep_areaSEEGP, document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0):
    # language = language

    pdf = pymupdf.open(document)

    if keep_areaSEEGP == True:
        extractUOPwords = wordsUOP_endPage(document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0)
        UOPwordsNoDupes = list(set(extractUOPwords))

    elif keep_areaSEEGP == False:
        extractUOPwords = []

# iterate pages
        for page_idx in range(len(pdf)):
            page = pdf[page_idx]
       
    # process two page scenarios and extract text as words

        # assume UOP across > 1 page
        # B: current page is start page
            if page_idx == areaUOP_page:
                for word in page.get_text('words'):
                    x0, y0, x1, y1, messyText, *_ = word
                    if y0 > areaUOP_y1:
                        tidyText = messyText.replace('\n',' ').lower()
                        extractUOPwords.append(tidyText)

        # E: current page is after the UOP start page
            elif page_idx > areaUOP_page:
                for word in page.get_text('words'):
                    x0, y0, x1, y1, messyText, *_ = word
                    tidyText = messyText.replace('\n',' ').lower()
                    extractUOPwords.append(tidyText)
    
        UOPwordsNoDupes = list(set(extractUOPwords))
    
    return UOPwordsNoDupes

In [15]:
# process words into category word dictionaries where doc.similarity score passes threshold

def UOPwords_to_Catwords(language, UOPwordsNoDupes):

    sim_th_en = 0.65
    sim_th_pt = 0.65
    sim_th_es = 0.65

    if language == 'EN':
        nlp = nlp_en
        re = renewable_energy_en
        ee = energy_efficiency_en
        ppc = pollution_prevention_and_control_en
        esml = environmentally_sustainable_management_of_living_natural_resources_and_land_use_en
        tabc = terrestrial_and_aquatic_biodiversity_conservation_en
        ct = clean_transportation_en
        swwm = sustainable_water_and_wastewater_management_en
        cca = climate_change_adaptation_en
        ce = circular_economy_and_or_ecoefficient_projects_en
        gb = green_buildings_en
        similarity_threshold = sim_th_en
    elif language == 'PT':
        nlp = nlp_pt
        re = renewable_energy_pt
        ee = energy_efficiency_pt
        ppc = pollution_prevention_and_control_pt
        esml = environmentally_sustainable_management_of_living_natural_resources_and_land_use_pt
        tabc = terrestrial_and_aquatic_biodiversity_conservation_pt
        ct = clean_transportation_pt
        swwm = sustainable_water_and_wastewater_management_pt
        cca = climate_change_adaptation_pt
        ce = circular_economy_and_or_ecoefficient_projects_pt
        gb = green_buildings_pt
        similarity_threshold = sim_th_pt
    elif language == 'ES':
        nlp = nlp_es
        re = renewable_energy_es
        ee = energy_efficiency_es
        ppc = pollution_prevention_and_control_es
        esml = environmentally_sustainable_management_of_living_natural_resources_and_land_use_es
        tabc = terrestrial_and_aquatic_biodiversity_conservation_es
        ct = clean_transportation_es
        swwm = sustainable_water_and_wastewater_management_es
        cca = climate_change_adaptation_es
        ce = circular_economy_and_or_ecoefficient_projects_es
        gb = green_buildings_es
        similarity_threshold = sim_th_es

    # outputs
    simsre = {}
    energy_system_uop = ""
    simsee = {}
    simsppc = {}
    simsesml = {}
    simstabc = {}
    simsct = {}
    simsswwm = {}
    simscca = {}
    simsce = {}
    simsgb = {}
    cat_count_uop = 0
    

    # renewable_energy
    for worda in re:
        doca = nlp(worda)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            sim = doca.similarity(docb)
            if sim >= similarity_threshold:
                simsre[doca[0].text + ' ' + docb[0].text] = sim
    if simsre:
        energy_system_uop = True
        cat_count_uop +=1
    else:
        energy_system_uop = False

    # energy_efficiency
    for wordc in ee:
        docc = nlp(wordc)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            sim = docc.similarity(docb)
            if sim >= similarity_threshold:
                simsee[docc[0].text + ' ' + docb[0].text] = sim
    if simsee:
        cat_count_uop +=1
    
    # pollution_prevention_and_control
    for wordd in ppc:
        docd = nlp(wordd)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            sim = docd.similarity(docb)
            if sim >= similarity_threshold:
                simsppc[docd[0].text + ' ' + docb[0].text] = sim
    if simsppc:
        cat_count_uop +=1

    # environmentally_sustainable_management_of_living_natural_resources_and_land_use
    for worde in esml:
        doce = nlp(worde)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            sim = doce.similarity(docb)
            if sim >= similarity_threshold:
                simsesml[doce[0].text + ' ' + docb[0].text] = sim
    if simsesml:
        cat_count_uop +=1

    # terrestrial_and_aquatic_biodiversity_conservation
    for wordf in tabc:
        docf = nlp(wordf)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            sim = docf.similarity(docb)
            if sim >= similarity_threshold:
                simstabc[docf[0].text + ' ' + docb[0].text] = sim
    if simstabc:
        cat_count_uop +=1

    # clean_transportation
    for wordg in ct:
        docg = nlp(wordg)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            sim = docg.similarity(docb)
            if sim >= similarity_threshold:
                simsct[docg[0].text + ' ' + docb[0].text] = sim
    if simsct:
        cat_count_uop +=1

    # sustainable_water_and_wastewater_management
    for wordh in swwm:
        doch = nlp(wordh)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            sim = doch.similarity(docb)
            if sim >= similarity_threshold:
                simsswwm[doch[0].text + ' ' + docb[0].text] = sim
    if simsswwm:
        cat_count_uop +=1

    # climate_change_adaptation
    for wordi in cca:
        doci = nlp(wordi)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            sim = doci.similarity(docb)
            if sim >= similarity_threshold:
                simscca[doci[0].text + ' ' + docb[0].text] = sim
    if simscca:
        cat_count_uop +=1

        # circular_economy_and_or_ecoefficient_projects
    for wordj in ce:
        docj = nlp(wordj)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            sim = docj.similarity(docb)
            if sim >= similarity_threshold:
                simsce[docj[0].text + ' ' + docb[0].text] = sim
    if simsce:
        cat_count_uop +=1

    # green_buildings
    for wordk in gb:
        dock = nlp(wordk)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            sim = dock.similarity(docb)
            if sim >= similarity_threshold:
                simsgb[dock[0].text + ' ' + docb[0].text] = sim
    if simsgb:
        cat_count_uop +=1

    return simsre, simsee, simsppc, simsesml, simstabc, simsct, simsswwm, simscca, simsce, simsgb, sim_th_en, sim_th_es, sim_th_pt, energy_system_uop, cat_count_uop

In [16]:
# list of pdf filenames
pdf_en = ['Green_social_bond_framework_series_ad_ae_2019', 'ISA_CTM_FRAMEWORK', 'SONDA_S_A__GREEN_BOND_FRAMEWORK',
          'CIFI_Green_Bond_Framework', 'BTG_Sustainable_Financing_Framework', 'CABEI_Green_Bond_Framework', 
          'Genneia_Green_Bond_Framework', 'FS_Green_Bond_Framework_-_July_2021', 'CAFs_GREEN_BOND_FRAMEWORK', 
          'BTG_Pactual_Green,_Social_and_Sustainable_Financing_Framework', 'ILAP_Green_Financing_Framework', 
          'EGE_Haina_Green_Securities_Framework', 'CADU_GREEN_BOND_FRAMEWORK', 'Bci_Sustainable_Financing_Framework',
          'FS_Green_Bond_Framework_-_November_2020', 'Sicredi_Green_Bond_Framework', 'Nacional_Financiera_Green_Bond_USD',
          'Green_Bond_Financing_Framework', 'Green_Bond_Framework_of_Banco_Guayaquil', 
          'Marco_de_referencia_de_Bonos_Verdes_Soberanos_de_Colombia', 'Green_Finance_Framework_Interchile']
pdf_en_lines = ['Chile_Sustainable_Bond_Framework', 'Genneia_Green_Financing_Framework']
pdf_es = ['Cartilla_Bonos_Verdes', 'Bono_Azul_-_Framework', 'Marco_de_referencia_de_bono_verde_Coopeguanacaste,_R_L_',  
          'Marco_de_Referencia_del_Bono_Verde_de_la_Ciudad_de_Mexico', 'Nacional_Financiera_Green_Bond_MXN',
          'Marco_de_Gestión_de_Bono_Verde', 'Bono_Verde_de_Bancoldex_Framework']
pdf_es_lines = ['Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos_Verdes,_Sociales_o_Sostenibles_BDP_I']
pdf_pt = ['Green_Bond_Framework', 'Green_Bonds_Framework_Athon_2020']

In [17]:
# run the pdf through the pipeline - first pdf, initialise the dataframes

# input parameters
document = '/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/PDF1/Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__in_2021.pdf'
language = 'EN'
tableStrategy = 'lines_strict'

# call the functions in sequence
filename, pdfname, tableCount, tablePages, tableHeaders, tableDFs = catTable(document, tableStrategy)
uniqueCatsNoDupes, table_idx = tableAssess(language, tableCount, tablePages, tableHeaders, tableDFs)
CatwordsFFinal, dfsimScores_cln, dfresimScores, energy_system_tbl, cleanup_TH_en, cleanup_TH_es, cleanup_TH_pt = tableClean(language, uniqueCatsNoDupes)
results_UOP, results_SEEGP = fontInfo(language, document)
max_idx_UOP, max_idx_SEEGP = find_max_font(results_UOP, results_SEEGP)
areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0 = tocCheck(results_UOP, results_SEEGP, max_idx_UOP, max_idx_SEEGP)
keep_areaSEEGP = keepSEEGP(areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0)
UOPwordsNoDupes = wordsUOP(keep_areaSEEGP, document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0)

# dataframe output for transparency on how pipeline has processed the pdf
columns = ['pdfname', 'language', 'tableCount', 'areaUOP_page', 'areaUOP_y1', 'areaSEEGP_page', 'areaSEEGP_y0', 'keep_areaSEEGP', 'countUOP_words']
results_df = pd.DataFrame(columns=columns)
results_df.loc[len(results_df)] = [pdfname, language, tableCount, areaUOP_page, areaUOP_y1, areaSEEGP_page,areaSEEGP_y0, keep_areaSEEGP, len(UOPwordsNoDupes)]

# table info
columns = ['pdfname', 'tablePages_list', 'table.Headers_list', 'countCat_words', 'unique compliant Categories_list', 'energy_system_tbl', 'table_idx_list', 'unique Cats all', 'simScores for cleanup', 'simScores for ES']
table_df = pd.DataFrame(columns=columns)

# UOP start and end info
columns = ['pdfname', 'results_UOP_list (text, fontSize, bbox, page_idx)', 'max_idx_UOP', 'results_SEEGP_list (text, fontSize, bbox, page_idx)', 'max_idx_SEEGP']
UOP_df = pd.DataFrame(columns=columns)
UOP_df.loc[len(UOP_df)] = [pdfname, results_UOP, max_idx_UOP, results_SEEGP, max_idx_SEEGP]

# final Cateogory info
if len(uniqueCatsNoDupes) == 0:
    simsre, simsee, simsppc, simsesml, simstabc, simsct, simsswwm, simscca, simsce, simsgb, sim_th_en, sim_th_es, sim_th_pt, energy_system_uop, cat_count_uop = UOPwords_to_Catwords(language, UOPwordsNoDupes)
    print('')
    print('categories from UOP portion')
    columns = ['pdfname', 'energy_system_uop', 'renewable_energy', 're_scores ', 'energy_efficiency', 'ee_scores', 'pollution_prevention_and_control', 'ppc_scores', 
               'environmentally_sustainable_management_of_living_natural_resources_and_land_use', 'esml_scores',
               'terrestrial_and_aquatic_biodiversity_conservation', 'tabc_scores', 'clean_transportation', 'ct_scores',
               'sustainable_water_and_wastewater_management', 'swwm_scores', 'climate_change_adaptation', 'cca_scores' ,
               'circular_economy_and_or_ecoefficient_projects', 'ce_scores', 'green_buildings', 'gb_scores']
    UOP_Words_df = pd.DataFrame(columns=columns)
    UOP_Words_df.loc[len(UOP_Words_df)] = [pdfname, energy_system_uop, simsre.keys(), simsre.values(), simsee.keys(), simsee.values(), 
                                           simsppc.keys(), simsppc.values(), simsesml.keys(), simsesml.values(),
                                           simstabc.keys(), simstabc.values(), simsct.keys(), simsct.values(), 
                                           simsswwm.keys(), simsswwm.values(), simscca.keys(), simscca.values(),
                                           simsce.keys(), simsce.values(), simsgb.keys(), simsgb.values()]
else:
    print('')
    print('categories from tables')
    table_df.loc[len(table_df)] = [pdfname, tablePages, tableHeaders, len(CatwordsFFinal), CatwordsFFinal, energy_system_tbl, table_idx, uniqueCatsNoDupes, dfsimScores_cln, dfresimScores]

# data table with results, for evaluation to ground truth
# nlp_path 
nlp_path = ""
if len(uniqueCatsNoDupes)>0:
    nlp_path = 'Table'
elif len(uniqueCatsNoDupes)==0 and keep_areaSEEGP == True:
    nlp_path = 'UOP_section_true'
elif len(uniqueCatsNoDupes)==0 and keep_areaSEEGP == False:
    nlp_path = 'UOP_section_false'

# ES percent oucomes
ES_0_percent = False
ES_100_percent = False
ES_partial = False

if energy_system_tbl == False or energy_system_uop == False:
    ES_0_percent = True

elif energy_system_tbl == True:
    if len(CatwordsFFinal) == 1:
        ES_100_percent = True
    elif len(CatwordsFFinal) > 1:
        ES_partial = True

elif energy_system_uop == True:
    if cat_count_uop == 1:
        ES_100_percent = True
    elif cat_count_uop > 1:
        ES_partial = True

# number of cats
number_of_cats = 0
if len(CatwordsFFinal)>0:
    number_of_cats = len(CatwordsFFinal)
else:
    number_of_cats = cat_count_uop

# threshold params
similarity_threshold = 0.0
cleanup_threshold = 0.0
if language == 'EN':
    similarity_threshold = sim_th_en
    cleanup_threshold = cleanup_TH_en
elif language == 'ES':
    similarity_threshold = sim_th_es
    cleanup_threshold = cleanup_TH_es
elif language == 'PT':
    similarity_threshold = sim_th_pt
    cleanup_threshold = cleanup_TH_pt    

columns = ['pdfname', 'nlp_path', 'language', 'similarity_threshold', 'cleanup_threshold', 'ES_0_percent', 'ES_100_percent', 'ES_partial', 'number_of_cats']
pred_train_rpts = pd.DataFrame(columns=columns)
pred_train_rpts.loc[len(pred_train_rpts)] = [pdfname, nlp_path, language, similarity_threshold, cleanup_threshold, ES_0_percent, ES_100_percent, ES_partial, number_of_cats]

Consider using the pymupdf_layout package for a greatly improved page layout analysis.

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:69: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doca.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:83: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docc.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:94: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docd.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:105: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doce.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:116: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docf.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:127: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docg.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:138: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doch.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:149: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doci.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:160: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docj.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:171: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = dock.similarity(docb)

categories from UOP portion

In [27]:
# run the pdf through the pipeline - subsequent pdfs, populate the dataframes


# input parameters
filepath = '/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/PDFs/'
extention = '.pdf'
language = 'EN'
tableStrategy = 'lines_strict'

for pdf in pdf_en:
    document = filepath + pdf + extention

    # call the functions in sequence
    filename, pdfname, tableCount, tablePages, tableHeaders, tableDFs = catTable(document, tableStrategy)
    uniqueCatsNoDupes, table_idx = tableAssess(language, tableCount, tablePages, tableHeaders, tableDFs)
    CatwordsFFinal, dfsimScores_cln, dfresimScores, energy_system_tbl, cleanup_TH_en, cleanup_TH_es, cleanup_TH_pt = tableClean(language, uniqueCatsNoDupes) 
    results_UOP, results_SEEGP = fontInfo(language, document)
    max_idx_UOP, max_idx_SEEGP = find_max_font(results_UOP, results_SEEGP)
    areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0 = tocCheck(results_UOP, results_SEEGP, max_idx_UOP, max_idx_SEEGP)
    keep_areaSEEGP = keepSEEGP(areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0)
    UOPwordsNoDupes = wordsUOP(keep_areaSEEGP, document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0)

    # dataframe outputs for transparency on how pipeline has processed the pdf
    results_df.loc[len(results_df)] = [pdfname, language, tableCount, areaUOP_page, areaUOP_y1, areaSEEGP_page,areaSEEGP_y0, keep_areaSEEGP, len(UOPwordsNoDupes)]
    UOP_df.loc[len(UOP_df)] = [pdfname, results_UOP, max_idx_UOP, results_SEEGP, max_idx_SEEGP]

    # final Cateogory info
    if len(uniqueCatsNoDupes) == 0:
        simsre, simsee, simsppc, simsesml, simstabc, simsct, simsswwm, simscca, simsce, simsgb, sim_th_en, sim_th_es, sim_th_pt, energy_system_uop, cat_count_uop = UOPwords_to_Catwords(language, UOPwordsNoDupes)
        print('')
        print('categories from UOP portion')
        UOP_Words_df.loc[len(UOP_Words_df)] = [pdfname, energy_system_uop, simsre.keys(), simsre.values(), simsee.keys(), simsee.values(), 
                                           simsppc.keys(), simsppc.values(), simsesml.keys(), simsesml.values(),
                                           simstabc.keys(), simstabc.values(), simsct.keys(), simsct.values(), 
                                           simsswwm.keys(), simsswwm.values(), simscca.keys(), simscca.values(),
                                           simsce.keys(), simsce.values(), simsgb.keys(), simsgb.values()]
    else:
        print('')
        print('categories from tables')
        table_df.loc[len(table_df)] = [pdfname, tablePages, tableHeaders, len(CatwordsFFinal), CatwordsFFinal, energy_system_tbl, table_idx, uniqueCatsNoDupes, dfsimScores_cln, dfresimScores]


    # data table with results for evaluation to ground truth
    # nlp_path 
    nlp_path = ""
    if len(uniqueCatsNoDupes)>0:
        nlp_path = 'Table'
    elif len(uniqueCatsNoDupes)==0 and keep_areaSEEGP == True:
        nlp_path = 'UOP_section_true'
    elif len(uniqueCatsNoDupes)==0 and keep_areaSEEGP == False:
        nlp_path = 'UOP_section_false'

    # ES percent oucomes
    ES_0_percent = False
    ES_100_percent = False
    ES_partial = False

    if energy_system_tbl == False or energy_system_uop == False:
        ES_0_percent = True

    elif energy_system_tbl == True:
        if len(CatwordsFFinal) == 1:
            ES_100_percent = True
        elif len(CatwordsFFinal) > 1:
            ES_partial = True

    elif energy_system_uop == True:
        if cat_count_uop == 1:
            ES_100_percent = True
        elif cat_count_uop > 1:
            ES_partial = True

    # number of cats
    number_of_cats = 0
    if len(CatwordsFFinal)>0:
        number_of_cats = len(CatwordsFFinal)
    else:
        number_of_cats = cat_count_uop

    # threshold params
    similarity_threshold = 0.0
    cleanup_threshold = 0.0
    if language == 'EN':
        similarity_threshold = sim_th_en
        cleanup_threshold = cleanup_TH_en
    elif language == 'ES':
        similarity_threshold = sim_th_es
        cleanup_threshold = cleanup_TH_es
    elif language == 'PT':
        similarity_threshold = sim_th_pt
        cleanup_threshold = cleanup_TH_pt

    
    pred_train_rpts.loc[len(pred_train_rpts)] = [pdfname, nlp_path, language, similarity_threshold, cleanup_threshold, ES_0_percent, ES_100_percent, ES_partial, number_of_cats]

categories from tables

categories from tables

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:69: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doca.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:83: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docc.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:94: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docd.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:105: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doce.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:116: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docf.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:127: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docg.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:138: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doch.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:149: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doci.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:160: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docj.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:171: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = dock.similarity(docb)

categories from UOP portion

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:69: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doca.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:83: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docc.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:94: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docd.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:105: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doce.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:116: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docf.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:127: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docg.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:138: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doch.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:149: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doci.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:160: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docj.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:171: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = dock.similarity(docb)

categories from UOP portion

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:69: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doca.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:83: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docc.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:94: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docd.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:105: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doce.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:116: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docf.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:127: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docg.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:138: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doch.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:149: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doci.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:160: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docj.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:171: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = dock.similarity(docb)

categories from UOP portion

categories from tables

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:69: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doca.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:83: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docc.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:94: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docd.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:105: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doce.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:116: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docf.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:127: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docg.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:138: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doch.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:149: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doci.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:160: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docj.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:171: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = dock.similarity(docb)

categories from UOP portion

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:69: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doca.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:83: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docc.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:94: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docd.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:105: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doce.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:116: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docf.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:127: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docg.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:138: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doch.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:149: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doci.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:160: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docj.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:171: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = dock.similarity(docb)

categories from UOP portion

categories from tables

categories from tables

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:69: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doca.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:83: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docc.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:94: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docd.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:105: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doce.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:116: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docf.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:127: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docg.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:138: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doch.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:149: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doci.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:160: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docj.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:171: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = dock.similarity(docb)

categories from UOP portion

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:69: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doca.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:83: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docc.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:94: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docd.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:105: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doce.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:116: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docf.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:127: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docg.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:138: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doch.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:149: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doci.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:160: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docj.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:171: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = dock.similarity(docb)

categories from UOP portion

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:69: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doca.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:83: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docc.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:94: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docd.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:105: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doce.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:116: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docf.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:127: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docg.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:138: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doch.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:149: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doci.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:160: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docj.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:171: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = dock.similarity(docb)

categories from UOP portion

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:69: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doca.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:83: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docc.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:94: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docd.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:105: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doce.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:116: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docf.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:127: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docg.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:138: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doch.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:149: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doci.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:160: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docj.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:171: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = dock.similarity(docb)

categories from UOP portion

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:69: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doca.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:83: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docc.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:94: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docd.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:105: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doce.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:116: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docf.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:127: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docg.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:138: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doch.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:149: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doci.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:160: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docj.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:171: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = dock.similarity(docb)

categories from UOP portion

categories from tables

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:69: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doca.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:83: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docc.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:94: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docd.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:105: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doce.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:116: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docf.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:127: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docg.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:138: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doch.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:149: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doci.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:160: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docj.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:171: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = dock.similarity(docb)

categories from UOP portion

categories from tables

categories from tables

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:69: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doca.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:83: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docc.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:94: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docd.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:105: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doce.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:116: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docf.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:127: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docg.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:138: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doch.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:149: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doci.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:160: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docj.similarity(docb)
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/4257991032.py:171: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = dock.similarity(docb)

categories from UOP portion

categories from tables

In [28]:
results_df

,pdfname,language,tableCount,areaUOP_page,areaUOP_y1,areaSEEGP_page,areaSEEGP_y0,keep_areaSEEGP,countUOP_words
0,Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__i...,EN,1,1,420.328369,2,354.484863,True,188
1,Green_Bond_Framework,PT,5,1,304.611969,15,133.837967,True,1602
2,Green_Bonds_Framework_Athon_2020,PT,2,4,428.291565,6,551.981140,True,379
3,Cartilla_Bonos_Verdes,ES,0,10,433.616699,16,464.230499,True,497
4,Bono_Azul_-_Framework,ES,5,1,336.792603,1,390.216888,True,15
5,Marco_de_referencia_de_bono_verde_Coopeguanaca...,ES,18,15,89.151588,16,541.706238,True,271
6,Marco_de_Referencia_del_Bono_Verde_de_la_Ciuda...,ES,0,0,490.869995,0,395.050018,False,818
7,Nacional_Financiera_Green_Bond_MXN,ES,6,3,188.569992,3,534.459961,True,99
8,Marco_de_Gestión_de_Bono_Verde,ES,3,7,411.209991,2,210.830017,False,400
9,Bono_Verde_de_Bancoldex_Framework,ES,1,1,492.789978,3,365.630005,True,325
10,Chile_Sustainable_Bond_Framework,EN,13,18,217.077713,3,216.104080,False,1443
11,Genneia_Green_Financing_Framework,EN,2,1,600.482239,0,0.000000,False,1267
12,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,ES,43,5,102.917595,32,535.163818,True,2949
13,Green_social_bond_framework_series_ad_ae_2019,EN,3,1,98.540031,1,87.500031,False,927
14,ISA_CTM_FRAMEWORK,EN,11,8,271.757019,3,201.050018,False,503
15,SONDA_S_A__GREEN_BOND_FRAMEWORK,EN,0,4,124.099983,4,435.190002,True,124
16,CIFI_Green_Bond_Framework,EN,0,7,569.777405,8,169.974762,True,66
17,BTG_Sustainable_Financing_Framework,EN,1,20,80.458229,31,60.549740,True,1311
18,CABEI_Green_Bond_Framework,EN,5,7,441.189972,11,81.259979,True,387
19,Genneia_Green_Bond_Framework,EN,0,8,110.361000,9,104.296997,True,169
20,FS_Green_Bond_Framework_-_July_2021,EN,0,11,455.748077,5,223.619537,False,679
21,CAFs_GREEN_BOND_FRAMEWORK,EN,6,7,262.438385,9,336.903778,True,271
22,"BTG_Pactual_Green,_Social_and_Sustainable_Fina...",EN,4,14,406.338043,18,499.063019,True,327
23,ILAP_Green_Financing_Framework,EN,0,0,481.347198,0,470.681610,False,910
24,EGE_Haina_Green_Securities_Framework,EN,1,10,492.464996,12,428.401001,True,275
25,CADU_GREEN_BOND_FRAMEWORK,EN,0,6,140.128403,0,758.464783,False,578
26,Bci_Sustainable_Financing_Framework,EN,0,7,110.545990,1,28.432018,False,909
27,FS_Green_Bond_Framework_-_November_2020,EN,0,7,546.994019,7,403.429993,False,653
28,Sicredi_Green_Bond_Framework,EN,2,3,402.529999,4,579.070007,True,236
29,Nacional_Financiera_Green_Bond_USD,EN,1,3,123.770012,3,356.360016,True,84
30,Green_Bond_Financing_Framework,EN,3,7,179.089981,8,559.180054,True,186
31,Green_Bond_Framework_of_Banco_Guayaquil,EN,16,6,109.511734,11,71.712212,True,622
32,Marco_de_referencia_de_Bonos_Verdes_Soberanos_...,EN,1,14,479.131409,19,351.234100,True,731
33,Green_Finance_Framework_Interchile,EN,1,7,321.529999,9,111.740021,True,210

In [29]:
table_df

,pdfname,tablePages_list,table.Headers_list,countCat_words,unique compliant Categories_list,energy_system_tbl,table_idx_list,unique Cats all,simScores for cleanup,simScores for ES
0,Green_Bond_Framework,"[10, 14, 19, 21, 22]","[[Categoria, Descrição], [Projeto, Capaci\nda ...",2,"[transmissão de energia, energia renovável]",True,"[0, 0]","[transmissão de energia, energia renovável]",...,0 transmissão ...
1,Nacional_Financiera_Green_Bond_MXN,"[3, 9, 10, 11, 17]","[[Categoría, Actividades elegibles], [Col0, Pr...",2,"[pequeñas centrales hidroeléctricas, centrales...",True,"[0, 0]","[pequeñas centrales hidroeléctricas, centrales...",...,0 hidroelectricidad ...
2,Marco_de_Gestión_de_Bono_Verde,"[5, 8, 9]","[[Norma de\nDesempeño, Estatus1, Descripción],...",1,[proyecto de energías renovables (energía hidr...,True,[1],[proyecto de energías renovables (energía hidr...,...,0 bioenergía ...
3,Chile_Sustainable_Bond_Framework,"[0, 19, 20, 21, 22, 23, 24, 25, 26, 30, 37, 38...","[[Col0, Ministry of\nFinance\nGovernment of Ch...",8,"[energy efficiency, access to basic housing, r...",True,"[5, 5, 5, 5, 6, 6, 7, 7, 7, 8, 8, 10, 10, 10, ...",[support for the community through job creatio...,...,0 renewable 0.682400 power ...
4,Genneia_Green_Financing_Framework,"[5, 7]","[[Col0, 20161, 20202, 20251, 20301], [Eligible...",1,[renewable energy],True,[1],[renewable energy],0 renewable...,0 renewable 0.682400 bioene...
5,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,"[3, 4, 8, 16, 18, 19, 20, 21, 22, 23, 24, 25, ...",[[Contribuciones Nacionales Determinadas (NDCs...,1,[energías renovables],True,"[34, 34, 34, 34, 35, 35]","[verdes, energías renovables, eficiencia energ...",...,0 bioenergía 0.711818 reno...
6,Green_social_bond_framework_series_ad_ae_2019,"[3, 6, 7]","[[Category, Project name, Goal], [Categories o...",2,"[potable water supply, sanitation]",False,"[0, 0, 0, 1, 1, 1]","[potable water supply, sanitation, resilient i...",0 potable...,Empty DataFrame Columns: [] Index: []
7,ISA_CTM_FRAMEWORK,"[4, 5, 7, 8, 9, 15, 16, 17, 18]","[[Eligible Project Category, Questions, Alignm...",2,"[energy efficiency, renewable energy]",True,"[0, 0]","[energy efficiency, renewable energy]",0 energy ...,0 renewable 0.682400 power ...
8,CABEI_Green_Bond_Framework,"[7, 8, 9, 10, 12]","[[Eligible\nGreen\nProjects\nCategories, Sub-c...",3,"[renewable energy, sustainable land use, water...",True,"[0, 4, 4, 4, 4]","[clean transport, renewable energy, sustainabl...",0 renewable...,0 renewable 0.698057 bioene...
9,CAFs_GREEN_BOND_FRAMEWORK,"[1, 2, 8, 9]","[[Measure of Units, Col1], [Graphics, Content]...",4,"[clean transportation, renewable energy, waste...",True,"[2, 2, 2, 2]","[clean transportation, renewable energy, waste...",...,0 renewable 0.698057 bioene...
10,"BTG_Pactual_Green,_Social_and_Sustainable_Fina...","[15, 16, 17, 19]","[[Green\nProject\nCategory, Use of\nProceeds, ...",6,"[clean transportation, sustainable water and w...",True,"[0, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 3, 3]","[clean transportation, sustainable water and w...",...,0 renewable 0.682400 bioene...
11,Sicredi_Green_Bond_Framework,"[4, 6]","[[Eligible\nCategories, Description, Objective...",2,"[energy efficiency, renewable energy]",True,"[0, 0]","[energy efficiency, renewable energy]",0 energy ...,0 renewable 0.682400 power ...
12,Green_Bond_Financing_Framework,"[7, 8, 10]",[[Eligible Category aligned\nwith ICMA Green B...,2,"[clean transportation, energy efficiency]",True,"[0, 2, 2]","[clean transportation, energy efficiency]",0 ...,0 renewable 0.682400 power ...
13,Green_Bond_Framework_of_Banco_Guayaquil,"[6, 7, 8, 9, 10, 18, 19, 29, 30, 31, 38, 39]","[[GBP Eligible\nGreen Assets\nCategory, Banco ...",2,"[energy efficiency, renewable energy]",True,"[0, 1, 1, 1, 1]","[energy efficiency, renewable energy]",0 energy ...,0 renewable 0.682400 power ...
14,Green_Finance_Framework_Interchile,[8],"[[Eligible Project Category, Questions, Alignm...",3,"[energy efficiency, renewable energy, climate ...",True,"[0, 0, 0]","[renewable energy, energy efficiency, climate ...",0...,0 renewable 0.682400 power ...

In [30]:
check11 = table_df.iloc[11].loc['simScores for ES']
check11

                  0
renewable  0.682400
power      0.657853
bioenergy  0.651106
biofuel    0.690298
biomass    0.675836

In [31]:
UOP_df

,pdfname,"results_UOP_list (text, fontSize, bbox, page_idx)",max_idx_UOP,"results_SEEGP_list (text, fontSize, bbox, page_idx)",max_idx_SEEGP
0,Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__i...,"[(Use of Proceeds , 11.039999961853027, (85.1...",0,[(Selection and Evaluation of Eligible Green P...,0
1,Green_Bond_Framework,"[(Usos dos Recursos , 12.0, (115.25, 291.32797...",0,"[(Avaliação e Seleção de Ativos , 12.0, (103.2...",0
2,Green_Bonds_Framework_Athon_2020,[(Uso de Recursos ...............................,2,[(Processo de Avaliação e Seleção de Projetos ...,1
3,Cartilla_Bonos_Verdes,"[(Uso de Fondos Proyectos Verdes Elegibles , 1...",3,"[(Procedimiento Selección y Evaluación , 12.0,...",2
4,Bono_Azul_-_Framework,"[(2.1 Uso de los recursos , 12.0, (41.13280105...",0,[(2.2 Proceso de evaluación y selección de pr...,0
5,Marco_de_referencia_de_bono_verde_Coopeguanaca...,[(Destinos de Fondos. ...........................,1,[(Proceso de evaluación y selección de proyect...,2
6,Marco_de_Referencia_del_Bono_Verde_de_la_Ciuda...,"[(1. Uso de los Recursos , 12.0, (49.680000305...",0,[(2. Proceso de Evaluación y Selección de proy...,0
7,Nacional_Financiera_Green_Bond_MXN,"[(3.1. Uso de los Fondos , 11.039999961853027,...",1,[(3.2. Proceso de Evaluación y Selección de Pr...,2
8,Marco_de_Gestión_de_Bono_Verde,[(Uso de los Fondos .............................,2,[(Proceso de Selección y Evaluación de Proyect...,1
9,Bono_Verde_de_Bancoldex_Framework,"[(Uso de los recursos , 12.0, (113.41999816894...",0,[(ingresos o recursos; (ii) proceso de evaluac...,2
10,Chile_Sustainable_Bond_Framework,"[(Use of Proceeds, 8.0, (311.42449951171875, 5...",2,"[(Project Evaluation , 11.0, (123.502014160156...",0
11,Genneia_Green_Financing_Framework,"[(Use of proceeds, 9.0, (73.48359680175781, 58...",0,[],0
12,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,[(Marco de uso de fondos para las emisiones de...,7,[(3.2. Selección y Evaluación de Proyectos ......,2
13,Green_social_bond_framework_series_ad_ae_2019,"[(SBPs: Use of Funds, Evaluation and Selection...",0,"[(SBPs: Use of Funds, Evaluation and Selection...",0
14,ISA_CTM_FRAMEWORK,"[(Use of the proceeds , 11.039999961853027, (1...",4,"[(Process for Evaluation and Selection , 11.03...",0
15,SONDA_S_A__GREEN_BOND_FRAMEWORK,[(3.1 Use of Proceeds ...........................,1,[(3.2 Project Selection and Assessment Process...,1
16,CIFI_Green_Bond_Framework,"[(a. Use of Proceeds, 12.531599998474121, (69....",0,"[(b. Project Selection Criteria , 12.531599998...",0
17,BTG_Sustainable_Financing_Framework,"[(Use of Proceeds, 13.0, (241.72439575195312, ...",2,[(Process for Project Selection and Evaluation...,4
18,CABEI_Green_Bond_Framework,[(Use of Proceeds ...............................,1,[(Process for Project Evaluation and Selection...,3
19,Genneia_Green_Bond_Framework,"[( Use of Proceeds, 13.0, (253.3719940185547,...",1,"[(Process for Project Evaluation , 13.0, (269...",2
20,FS_Green_Bond_Framework_-_July_2021,"[(Use of Proceeds , 12.000450134277344, (110.6...",0,"[(theme within the company. Furthermore, in th...",0
21,CAFs_GREEN_BOND_FRAMEWORK,[(1. Use of Proceeds ............................,2,[(2. Process for Project Evaluation and Select...,6
22,"BTG_Pactual_Green,_Social_and_Sustainable_Fina...","[(Use of Proceeds , 12.0, (184.590087890625, 6...",3,"[(Process for Project , 12.0, (184.59008789062...",5
23,ILAP_Green_Financing_Framework,"[(1. Use of proceeds , 8.800000190734863, (77....",0,[( 2. Process for project evaluation and selec...,0
24,EGE_Haina_Green_Securities_Framework,"[(• Use of Proceeds\t, 10.0, (259.912902832031...",5,[(• Project Selection and Evaluation Process\t...,1
25,CADU_GREEN_BOND_FRAMEWORK,"[(Use of Proceeds , 11.039999961853027, (84.98...",0,"[(selection processes; and, the reporting meth...",0
26,Bci_Sustainable_Financing_Framework,"[(Green Use of Proceeds instruments: , 9.0, (6...",10,"[(Process for , 9.0, (277.7300109863281, 28.43...",0
27,FS_Green_Bond_Framework_-_November_2020,"[(Use of Proceeds , 12.0, (110.66000366210938,...",0,[(Capital Markets Association are voluntary pr...,0
28,Sicredi_Green_Bond_Framework,[(2.1 Use of Proceeds ...........................,2,[(2.2 Project evaluation & selection ............,3
29,Nacional_Financiera_Green_Bond_USD,"[(3.1 Use of Proceeds , 11.039999961853027, (9...",2,"[(3.2 Project Selection Process , 11.039999961...",1
30,Green_Bond_Financing_Framework,"[(Use of Proceeds , 11.039999961853027, (108.0...",1,[(5.2 Process of Project Evaluation and S...,5
31,Green_Bond_Framework_of_Banco_Guayaquil,[(First Principle – Use of Proceeds .............,3,[(Second Principle – Process for Project Evalu...,6
32,Marco_de_referencia_de_Bonos_Verdes_Soberanos_...,"[(Use of proceeds , 11.0, (360.3396911621094, ...",3,"[(Process for Project Evaluation and , 11.0, (...",5
33,Green_Finance_Framework_Interchile,[(4.1 Use of Proceeds ...........................,2,[(4.2 Process for Project Evaluation and Selec...,5

In [32]:
UOP_Words_df

,pdfname,energy_system_uop,renewable_energy,re_scores,energy_efficiency,ee_scores,pollution_prevention_and_control,ppc_scores,environmentally_sustainable_management_of_living_natural_resources_and_land_use,esml_scores,...,clean_transportation,ct_scores,sustainable_water_and_wastewater_management,swwm_scores,climate_change_adaptation,cca_scores,circular_economy_and_or_ecoefficient_projects,ce_scores,green_buildings,gb_scores
0,Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__i...,True,"(renewable energy, renewable electricity, rene...","(0.6823998093605042, 0.6735955476760864, 1.0, ...",(),(),(pollution emissions),(0.6611024141311646),(),(),...,(electric electricity),(0.671796441078186),(),(),(),(),(),(),(),()
1,Green_Bonds_Framework_Athon_2020,True,"(energia energia, bioenergia energia, Hidrelét...","(0.9084944128990173, 0.7116448879241943, 0.716...","(eficiência refinanciamentos, eficiência equip...","(0.6505798697471619, 0.6624636650085449, 0.656...",(resíduos alimentos),(0.6529195308685303),(alimentares alimentos),(0.8313022255897522),...,"(transporte equipamentos, transporte equipamen...","(0.6563118696212769, 0.7077468633651733, 0.748...","(saneamento construção, saneamento refinanciam...","(0.6654408574104309, 0.6842076182365417, 0.722...","(adaptação construção, adaptação implementação)","(0.6819092035293579, 0.7532346844673157)",(),(),"(construções construção, construções comunidad...","(0.7227913737297058, 0.7177586555480957, 0.671..."
2,Cartilla_Bonos_Verdes,True,"(renovable energética, renovable sostenible, r...","(0.6642146110534668, 0.6984525918960571, 0.794...","(red red, acondicionar mantenimiento, acondici...","(0.7134368419647217, 0.6677801609039307, 0.664...","(contaminación aprovechamiento, contaminación ...","(0.7311469316482544, 0.7124846577644348, 0.709...","(. saneamiento, . orgánicos, . renovable, . en...","(0.8664849996566772, 0.8785515427589417, 0.878...",...,"(transporte aprovechamiento, transporte manten...","(0.6558911204338074, 0.710953414440155, 0.6518...","(de de, de agua, potable, abastecimiento, ...","(0.7838726043701172, 0.6710147857666016, 1.000...","(adecuación aprovechamiento, adecuación eficie...","(0.7930677533149719, 0.7663856744766235, 0.737...","(reciclar reciclaje, reciclar reciclado, reuti...","(0.799636960029602, 0.7682274580001831, 0.6536...","(construcciones aprovechamientos, construccion...","(0.6915837526321411, 0.6967828273773193, 0.655..."
3,Bono_Azul_-_Framework,False,(),(),(),(),(de de),(0.9079835414886475),(),(),...,(),(),(de de),(0.7838726043701172),(adecuación elegibilidad),(0.7566782236099243),(),(),(y y),(0.9070735573768616)
4,Marco_de_referencia_de_bono_verde_Coopeguanaca...,True,"(renovable renovables, solar solar, hidroelect...","(0.7942190170288086, 1.0, 0.6773465871810913, ...","(red red, acondicionar realizar)","(0.7134368419647217, 0.6741795539855957)","(contaminación ambiental, contaminación habili...","(0.7083898186683655, 0.6785174608230591, 0.729...","(. r.l, . valorizables, . fiscalizaciones, . c...","(0.8423397541046143, 0.9034574627876282, 0.852...",...,"(transporte servicio, eléctricos eléctricos, e...","(0.6618167757987976, 1.0, 0.7007869482040405, ...","(de de, saneamiento ambiental, saneamiento hab...","(0.7838726043701172, 0.6879059076309204, 0.748...","(adecuación habilitación, adecuación fiscaliza...","(0.8525652289390564, 0.8114882707595825, 0.713...",(),(),"(construcciones condiciones, construcciones co...","(0.6861790418624878, 0.7309611439704895, 0.714..."
5,Marco_de_Referencia_del_Bono_Verde_de_la_Ciuda...,True,"(renovable energética, renovable renovables, r...","(0.6642146110534668, 0.7942190170288086, 0.661...","(red red, acondicionar mantenimiento, acondici...","(0.7134368419647217, 0.6677801609039307, 0.674...","(contaminación reutilización, contaminación ef...","(0.7821718454360962, 0.7124846577644348, 0.732...","(. bonos, . gbp, . renovable, . cdmx, . sexo, ...","(0.7479940056800842, 1.0, 0.8781610727310181, ...",...,"(transporte mantenimiento, transporte distribu...","(0.710953414440155, 0.6518039107322693, 0.6618...","(de de, de agua, potabilizada, Aguas residua...","(0.7838726043701172, 0.7279173731803894, 0.792...","(adecuación reutilización, adecuación eficienc...","(0.829303503036499, 0.7663856744766235, 0.7742...","(reciclar reciclada, reciclar reciclado, reuti...","(0.7133514881134033, 0.7682274580001831, 0.747...","(construcciones reutilización, construcciones ...","(0.6687862873077393, 0.6502566933631897, 0.769..."
6,Bono_Verde_de_Bancoldex_Framework,True,"(renovable energética, renovable sostenible, r...","(0.6642146110534668, 0.6984525918960571, 0.794...","(red red, acondicionar facilitar, acondicionar...","(0.7134368419647217, 0.652474045753479, 0.6647...","(contaminación aprovechamiento, contaminación ...","(0.7311469316482544, 0.6714393496513367, 0.654...","(. residual, . energía, . etc., . económicos, ...","(0.9217485785484314, 0.818902313709259, 0.6889...",...,"(transporte aprovechamiento, transporte transp...","(0.6558911204338074, 1.0, 0.7192397713661194, ...","(de de, de agua, saneamiento aprovechamiento, ...","(0.7838726043701172, 0.6710147857666016, 0.782...","(adecuación aprovechamiento, adecuación eficie...","(0.7930677533149719, 0.654384434223175, 0.7744...","(reutilizar facilitar, reutilizar almacenamiento)","(0.6510095000267029, 0.6537311673164368)","(construcciones prácticas, construcciones fuen...","(0.6995339393615723, 0.6967828273773193, 0.689..."
7,SONDA_S_A__GREEN_BOND_FRAMEWORK,True,"(renewable energy, renewable renewable, renewa...","(0.6823998093605042, 1.0, 0.6758356690406799, ...","(efficiency efficient, efficiency efficiency)","(0.7573143839836121, 1.0)","(pollution emissions, waste waste)","(0.7256803512573242, 1.0)",(),(),...,(),(),(),(),(),(),(),(),"(buildings buildings, buildings building)","(1.0, 0.797235906124115)"
8,CIFI_Green_Bond_Framework,True,"(renewable energy, renewable renewable, renewa...","(0.6823998093605042, 1.0, 0.6758356690406799, ...",(),(),"(waste recycling, waste waste)","(0.7248635292053223, 1.0)",(),(),...,(),(),"(wastewater wastewater, treatment treatment)","(1.0, 1.0)",(),(),"(recycle recycling, reuse recycling)","(0.8278464674949646, 0.6530712246894836)",(),()
9,BTG_Sustainable_Financing_Framework,True,"(renewable non, renewable renewable, renewable...","(0.72650146484375, 1.0, 0.6980571150779724, 0....","(efficiency efficient, efficiency efficiency)","(0.7573143839836121, 1.0)","(pollution environmental, pollution emissions,...","(0.7345117926597595, 0.6577414870262146, 1.0, ...","(land land, land “, agriculture livestock, agr...","(1.0, 0.8367156982421875, 0.6849189400672913, ...",...,"(transportation transportation, transportation...","(1.0, 0.6649630665779114, 0.6578854918479919, ...","(water water, wastewater wastewater, sanitatio...","(0.8583021759986877, 1.0, 0.8295572996139526, ...","(adaptation adaptation, disaster disasters)","(1.0, 0.8176723718643188)","(recycle recyclable, recycle recycling, reuse ...","(0.6732295155525208, 0.8278464674949646, 0.653...","(buildings buildings, housing housing)","(0.8454830050468445, 1.0)"
10,Genneia_Green_Bond_Framework,True,"(renewable energy, renewable renewable, solar ...","(0.6823998093605042, 1.0, 1.0, 1.0, 0.65110641...",(),(),(pollution emissions),(0.7256803512573242),(),(),...,"(battery battery, charger battery)","(1.0, 0.8197756409645081)",(),(),(),(),(),(),(),()
11,FS_Green_Bond_Framework_-_July_2021,True,"(renewable biomass, renewable sustainable, ren...","(0.6758356690406799, 0.6980571150779724, 0.690...","(efficiency efficient, efficiency productivity)","(0.7573143839836121, 0.6503185033798218)","(pollution environmental, pollution impacts)","(0.7345117926597595, 0.6625850796699524)","(land lands, land land, agriculture agricultur...","(0.7620790004730225, 1.0, 0.898859441280365, 1...",...,"(electric electricity, car car, vehicle car, n...","(0.671796441078186, 1.0, 0.7667538523674011, 0...",(water water),(0.8583021759986877),(),(),(),(),(),()
12,ILAP_Green_Financing_Framework,True,"(renewable sustainable, renewable energy, rene...","(0.6980571150779724, 0.6823998093605042, 1.0, ...",(),(),"(pollution emissions, pollution environmental,...","(0.7256803512573242, 0.7345117926597595, 1.0)",(),(),...,(electric electricity),(0.671796441078186),(),(),(adaptation adaptation),(0.8294525742530823),(),(),(),()
13,EGE_Haina_Green_Securities_Framework,True,"(renewable energy, renewable renewable, solar ...","(0.6823998093605042, 1.0, 0.7906877398490906, ...",(),(),(),(),(land land),(1.0),...,(electric electric),(1.0),(water water),(1.0),(),(),(),(),(),()
14,CADU_GREEN_BOND_FRAMEWORK,True,"(renewable sustainable, renewable energy, rene...","(0.6980571150779724, 0.6823998093605042, 0.673...",(efficiency efficiency),(1.0),"(pollution emissions, pollution environmental,...","(0.6611024141311646, 0.7345117926597595, 0.662...",(),(),...,(electric electricity),(0.671796441078186),"(water water, wastewater sewage)","(0.8583021759986877, 0.6909952759742737)",(),(),(),(),"(buildings buildings, buildings houses, housin...","(1.0, 0.7476946711540222, 1.0)"
15,Bci_Sustainable_Financing_Framework,True,"(renewable fuels, renewable sustainable, renew...","(0.6609903573989868, 0.6980571150779724, 0.682...","(efficiency efficient, efficiency efficiency)","(0.7573143839836121, 1.0)","(pollution emissions, pollution environmental,...","(0.7256803512573242, 0.7345117926597595, 1.0, ...",(),(),...,"(transportation transport, transportation tran...","(0.7263567447662354, 1.0, 0.7536609768867493, ...","(water water, potable potable, wastewater sewe...","(1.0, 1.0, 0.693297266960144, 1.0, 1.0, 0.6804...",(),(),(),(),(buildings buildings),(1.0)
16,FS_Green_Bond_Framework_-_November_2020,True,"(renewable biomass, renewable sustainable, ren...","(0.6758356690406799, 0.6980571150779724, 0.690...","(efficiency efficient, efficiency productivity)","(0.7573143839836121, 0.6503185033798218)","(pollution environmental, pollution impacts)","(0.7345117926597595, 0.6625850796699524)","(land lands, land land, agriculture agricultur...","(0.7620790004730225, 1.0, 0.898859441280365, 1...",...,"(electric electricity, car car, vehicle car, n...","(0.671796441078186, 1.0, 0.7667538523674011, 0...",(water water),(0.8583021759986877),(),(),(),(),(),()
17,Nacional_Financiera_Green_Bond_USD,True,"(renewable energy, wind wind, power energy, tr...","(0.6823998093605042, 1.0, 0.6578531265258789, ...",(),(),(),(),(),(),...,(),(),(),(),(),(),(),(),(),()
18,Marco_de_referencia_de_Bonos_Verdes_Soberanos_...,True,"(renewable fuels, renewable sustainable, renew...","(0.6609903573989868, 0.6980571150779724, 0.682...",(efficiency efficiency),(1.0),"(pollution emissions, pollution environmental,...","(0.7256803512573242, 0.7345117926597595, 1.0, ...","(land (, land land, agriculture agricultural, ...","(0.6583104133605957, 0.8250224590301514, 0.898...",...,"(transportation transport, transportation tran...","(0.7263567447662354, 1.0, 0.6578854918479919, ...","(water water, wastewater wastewater, sanitatio...","(0.8583021759986877, 1.0, 0.8295572996139526, ...","(adaptation adaptation, disaster disasters, di...","(1.0, 0.7475464344024658, 1.0)","(circular circular, recycle reuse, reuse reuse)","(1.0, 0.7356382608413696, 1.0)","(buildings building, buildings buildings, hous...","(0.797235906124115, 0.8554772734642029, 0.8488..."

In [33]:
pred_train_rpts

,pdfname,nlp_path,language,similarity_threshold,cleanup_threshold,ES_0_percent,ES_100_percent,ES_partial,number_of_cats
0,Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__i...,UOP_section_true,EN,0.65,0.65,False,False,True,3
1,Green_Bond_Framework,Table,PT,0.65,0.65,False,False,True,2
2,Green_Bonds_Framework_Athon_2020,UOP_section_true,PT,0.65,0.65,False,False,True,9
3,Cartilla_Bonos_Verdes,UOP_section_true,ES,0.65,0.65,False,False,True,10
4,Bono_Azul_-_Framework,UOP_section_true,ES,0.65,0.65,True,False,False,5
5,Marco_de_referencia_de_bono_verde_Coopeguanaca...,UOP_section_true,ES,0.65,0.65,False,False,True,9
6,Marco_de_Referencia_del_Bono_Verde_de_la_Ciuda...,UOP_section_false,ES,0.65,0.65,False,False,True,10
7,Nacional_Financiera_Green_Bond_MXN,Table,ES,0.65,0.65,False,False,True,2
8,Marco_de_Gestión_de_Bono_Verde,Table,ES,0.65,0.65,False,True,False,1
9,Bono_Verde_de_Bancoldex_Framework,UOP_section_true,ES,0.65,0.65,False,False,True,10
10,Chile_Sustainable_Bond_Framework,Table,EN,0.65,0.65,False,False,True,8
11,Genneia_Green_Financing_Framework,Table,EN,0.65,0.65,False,True,False,1
12,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,Table,ES,0.65,0.65,False,True,False,1
13,Green_social_bond_framework_series_ad_ae_2019,Table,EN,0.65,0.65,True,False,False,2
14,ISA_CTM_FRAMEWORK,Table,EN,0.65,0.65,False,False,True,2
15,SONDA_S_A__GREEN_BOND_FRAMEWORK,UOP_section_true,EN,0.65,0.65,False,False,True,4
16,CIFI_Green_Bond_Framework,UOP_section_true,EN,0.65,0.65,False,False,True,4
17,BTG_Sustainable_Financing_Framework,UOP_section_true,EN,0.65,0.65,False,False,True,10
18,CABEI_Green_Bond_Framework,Table,EN,0.65,0.65,False,False,True,3
19,Genneia_Green_Bond_Framework,UOP_section_true,EN,0.65,0.65,False,False,True,3
20,FS_Green_Bond_Framework_-_July_2021,UOP_section_false,EN,0.65,0.65,False,False,True,7
21,CAFs_GREEN_BOND_FRAMEWORK,Table,EN,0.65,0.65,False,False,True,4
22,"BTG_Pactual_Green,_Social_and_Sustainable_Fina...",Table,EN,0.65,0.65,False,False,True,6
23,ILAP_Green_Financing_Framework,UOP_section_false,EN,0.65,0.65,False,False,True,5
24,EGE_Haina_Green_Securities_Framework,UOP_section_true,EN,0.65,0.65,False,False,True,4
25,CADU_GREEN_BOND_FRAMEWORK,UOP_section_false,EN,0.65,0.65,False,False,True,7
26,Bci_Sustainable_Financing_Framework,UOP_section_false,EN,0.65,0.65,False,False,True,7
27,FS_Green_Bond_Framework_-_November_2020,UOP_section_false,EN,0.65,0.65,False,False,True,7
28,Sicredi_Green_Bond_Framework,Table,EN,0.65,0.65,False,False,True,2
29,Nacional_Financiera_Green_Bond_USD,UOP_section_true,EN,0.65,0.65,False,True,False,1
30,Green_Bond_Financing_Framework,Table,EN,0.65,0.65,False,False,True,2
31,Green_Bond_Framework_of_Banco_Guayaquil,Table,EN,0.65,0.65,False,False,True,2
32,Marco_de_referencia_de_Bonos_Verdes_Soberanos_...,UOP_section_true,EN,0.65,0.65,False,False,True,10
33,Green_Finance_Framework_Interchile,Table,EN,0.65,0.65,False,False,True,3

In [34]:
# write dataframes to csvfiles with versions in the filenames

dataframes = [results_df, table_df, UOP_df, UOP_Words_df, pred_train_rpts]
dfname_list = ['results_df', 'table_df', 'UOP_df', 'UOP_Words_df', 'pred_train_rpts']
csvname_list = ['results_csv', 'table_csv', 'UOP_csv', 'UOP_Words_csv', 'pred_train_rpts_csv']
filepath = '/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames/'
extention = '.csv'
version = '4.0'


results_csv = results_df.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames/results_csv_V4.csv')
table_csv = table_df.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames/table_csv_V4.csv')
UOP_csv = UOP_df.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames/UOP_csv_V4.csv')
UOP_Words_csv = UOP_Words_df.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames/UOP_Words_csv_V4.csv')
pred_train_rpts_csv = pred_train_rpts.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames/pred_train_rpts_V4.csv')