In [2]:
# import libraries

import pymupdf
import spacy
import re
import pandas as pd
import numpy as np
#import unicodedata
import os
from pathlib import Path
from translate import Translator

In [460]:
!python3 -m spacy download es_core_news_lg

^C
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/spacy/__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/spacy/errors.py", line 3, in <module>
    from .compat import Literal
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/spacy/compat.py", line 5, in <module>
    from thinc.util import copy_array
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/thinc/__init__.py", line 5, in <module>
    from .config import registry
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/thinc/config.py", line 5, in <module>
    from .types import Decorator
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/thinc/types.py", line 25, in <module>
    from .compat import cupy, has_cupy
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/thinc/compat.py", line 35, in <module>
    import torch
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/__init__.py", line 60, in <module>
    from torch.torch_version import __version__ as __version__
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1322, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1262, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1556, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1530, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1662, in find_spec
  File "<frozen importlib._bootstrap_external>", line 166, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 158, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 152, in _path_stat
KeyboardInterrupt

In [3]:
# nlp piplines from spacy for the 3 languages. large chosen for the higher dimension word vector libraries

nlp_en = spacy.load('en_core_web_lg')
nlp_pt = spacy.load('pt_core_news_lg')
nlp_es = spacy.load('es_core_news_lg')

In [4]:
# lists of green bond category words for usse in spacy similarity method 

not_re_cat_words_en = ['efficiency', 'retrofit', 'pollution', 'waste', 'land', 'agriculture', 'forestry', 'forest', 
                      'fisheries', 'food', 'terrestrial', 'aquatic', 'biodiversity', 'conservation', 'transportation', 
                      'electric', 'battery', 'EV', 'charger', 'bus', 'rail', 'train', 'car', 'vehicle', 'bicycle', 
                      'non-motorized', 'aviation', 'water', 'potable', 'wastewater', 'sanitation', 'treatment', 
                      'adaptation', 'disaster', 'circular', 'recycle', 'reuse','buildings', 'appliances', 'housing']

all_cat_words_en = ['renewable', 'solar', 'wind', 'bioenergy', 'biofuel', 'biomass', 'hydropower', 'hydrogen', 
                     'hydroelectric', 'power', 'grid', 'transmission', 'generation', 'geothermal', 'storage', 
                     'efficiency', 'retrofit', 'pollution', 'waste', 'land', 'agriculture', 'forestry', 'forest', 
                     'fisheries', 'food', 'terrestrial', 'aquatic', 'biodiversity', 'conservation', 'transportation',
                     'electric', 'battery', 'EV', 'charger', 'bus', 'rail', 'train', 'car', 'vehicle', 'bicycle', 
                     'non-motorized', 'aviation', 'water', 'potable', 'wastewater', 'sanitation', 'treatment', 
                     'adaptation', 'disaster', 'circular', 'recycle', 'reuse','buildings', 'appliances', 'housing']

renewable_energy_en = ['renewable', 'solar', 'wind', 'bioenergy', 'biofuel', 'biomass', 'hydropower', 'hydrogen', 'hydroelectric', 'power', 'grid', 'transmission', 'generation', 'geothermal', 'storage']
energy_efficiency_en = ['efficiency', 'retrofit']
pollution_prevention_and_control_en = ['pollution', 'waste']
environmentally_sustainable_management_of_living_natural_resources_and_land_use_en = ['land', 'agriculture', 'forestry', 'forest', 'fisheries', 'food']
terrestrial_and_aquatic_biodiversity_conservation_en = ['terrestrial', 'aquatic', 'biodiversity', 'conservation']
clean_transportation_en = ['transportation', 'electric', 'battery', 'EV', 'charger', 'bus', 'rail', 'train', 'car', 'vehicle', 'bicycle', 'non-motorized', 'aviation']
sustainable_water_and_wastewater_management_en = ['water', 'potable', 'wastewater', 'sanitation', 'treatment']
climate_change_adaptation_en = ['adaptation', 'disaster']
circular_economy_and_or_ecoefficient_projects_en = ['circular', 'recycle', 'reuse']
green_buildings_en = ['buildings', 'appliances', 'housing']

In [5]:
# iterate each word in the lists through the Translator from translate - English to Portuguese

not_re_cat_words_pt = []
all_cat_words_pt = []
renewable_energy_pt = []
energy_efficiency_pt = []
pollution_prevention_and_control_pt = []
environmentally_sustainable_management_of_living_natural_resources_and_land_use_pt = []
terrestrial_and_aquatic_biodiversity_conservation_pt = []
clean_transportation_pt = []
sustainable_water_and_wastewater_management_pt = []
climate_change_adaptation_pt = []
circular_economy_and_or_ecoefficient_projects_pt = []
green_buildings_pt = []


translator = Translator(to_lang='pt',from_lang='en')
# for word in not_re_cat_words_en:
    # translation = translator.translate(word)
    # not_re_cat_words_pt.append(translation)
for word in all_cat_words_en:
    translation = translator.translate(word)
    all_cat_words_pt.append(translation)
for word in renewable_energy_en:
    translation = translator.translate(word)
    renewable_energy_pt.append(translation)
for word in energy_efficiency_en:
    translation = translator.translate(word)
    energy_efficiency_pt.append(translation)
for word in pollution_prevention_and_control_en:
    translation = translator.translate(word)
    pollution_prevention_and_control_pt.append(translation)
for word in environmentally_sustainable_management_of_living_natural_resources_and_land_use_en:
    translation = translator.translate(word)
    environmentally_sustainable_management_of_living_natural_resources_and_land_use_pt.append(translation)
for word in terrestrial_and_aquatic_biodiversity_conservation_en:
    translation = translator.translate(word)
    terrestrial_and_aquatic_biodiversity_conservation_pt.append(translation)
for word in clean_transportation_en:
    translation = translator.translate(word)
    clean_transportation_pt.append(translation)
for word in sustainable_water_and_wastewater_management_en:
    translation = translator.translate(word)
    sustainable_water_and_wastewater_management_pt.append(translation)
for word in climate_change_adaptation_en:
    translation = translator.translate(word)
    climate_change_adaptation_pt.append(translation)
for word in circular_economy_and_or_ecoefficient_projects_en:
    translation = translator.translate(word)
    circular_economy_and_or_ecoefficient_projects_pt.append(translation)
for word in green_buildings_en:
    translation = translator.translate(word)
    green_buildings_pt.append(translation)

In [6]:
# iterate each word in the lists through the Translator from translate - English to Spanish

not_re_cat_words_es = []
all_cat_words_es = []
renewable_energy_es = []
energy_efficiency_es = []
pollution_prevention_and_control_es = []
environmentally_sustainable_management_of_living_natural_resources_and_land_use_es = []
terrestrial_and_aquatic_biodiversity_conservation_es = []
clean_transportation_es = []
sustainable_water_and_wastewater_management_es = []
climate_change_adaptation_es = []
circular_economy_and_or_ecoefficient_projects_es = []
green_buildings_es = []


translator = Translator(to_lang='es',from_lang='en')
# for word in not_re_cat_words_en:
    # translation = translator.translate(word)
    # not_re_cat_words_es.append(translation)
for word in all_cat_words_en:
    translation = translator.translate(word)
    all_cat_words_es.append(translation)
for word in renewable_energy_en:
    translation = translator.translate(word)
    renewable_energy_es.append(translation)
for word in energy_efficiency_en:
    translation = translator.translate(word)
    energy_efficiency_es.append(translation)
for word in pollution_prevention_and_control_en:
    translation = translator.translate(word)
    pollution_prevention_and_control_es.append(translation)
for word in environmentally_sustainable_management_of_living_natural_resources_and_land_use_en:
    translation = translator.translate(word)
    environmentally_sustainable_management_of_living_natural_resources_and_land_use_es.append(translation)
for word in terrestrial_and_aquatic_biodiversity_conservation_en:
    translation = translator.translate(word)
    terrestrial_and_aquatic_biodiversity_conservation_es.append(translation)
for word in clean_transportation_en:
    translation = translator.translate(word)
    clean_transportation_es.append(translation)
for word in sustainable_water_and_wastewater_management_en:
    translation = translator.translate(word)
    sustainable_water_and_wastewater_management_es.append(translation)
for word in climate_change_adaptation_en:
    translation = translator.translate(word)
    climate_change_adaptation_es.append(translation)
for word in circular_economy_and_or_ecoefficient_projects_en:
    translation = translator.translate(word)
    circular_economy_and_or_ecoefficient_projects_es.append(translation)
for word in green_buildings_en:
    translation = translator.translate(word)
    green_buildings_es.append(translation)

In [7]:
# find tables in the document and return table info
# pdfname: https://www.geeksforgeeks.org/python/get-filename-from-path-without-extension-using-python/

def catTable(document, tableStrategy):
    
    pdf = pymupdf.open(document) 
    filename = os.path.basename(document)
    pdfname = filename.split('.',1)[0]

    tableCount = 0
    tablePages = []
    tableHeaders = []
    tableDFs = []


    for page_idx in range(len(pdf)): 
        page = pdf[page_idx]

        find_tables = page.find_tables(strategy = tableStrategy)
        if find_tables.tables:
            table_count = len(find_tables.tables)
            tableheader = find_tables[0].header.names # assume only 1 table per page
            tableDF = find_tables[0].to_pandas()
            tableCount += table_count
            tablePages.append(page_idx)
            tableHeaders.append(tableheader)
            tableDFs.append(tableDF)

    return filename, pdfname, tableCount, tablePages, tableHeaders, tableDFs

In [8]:
# assess the tables found in the catTable function to identify the Category tables and extract unique list of category phrases

def tableAssess(language, tableCount, tablePages, tableHeaders, tableDFs):

    if language == 'PT':
        keywordsCAT = ['Categoria']
        nlp = nlp_pt
    elif language == 'ES':
        keywordsCAT = ['Categoría', 'Categorías']
        nlp = nlp_es
    elif language == 'EN':
        keywordsCAT = ['Category', 'Categories', 'Criteria', 'Criterion']
        nlp = nlp_en
    
    tablePageCurrent = 0
    tablePagePrior = 0
    tablepageCurrentTrue = 0
    uniqueCats = []
    uniqueCatsNoDupes = []
    table_idx = []

    if tableCount == 1: # applicable if only 1 table detected in whole pdf, noting that tables extending over page breaks get counted as more than 1find tabl
        dataFrame = tableDFs[0]
        header = tableHeaders[0]
        for keyword in keywordsCAT:
            if keyword.lower() in header[0].lower(): # assumes category col is always the first (LHS) col
                colName = header[0]
                uniqueC = dataFrame[colName].dropna().unique().tolist()
                for messyCat in uniqueC:
                    if messyCat:
                        tidyCat = messyCat.replace('\n',' ').lower()
                        uniqueCatsNoDupes.append(tidyCat)
                        table_idx.append(0)
    elif tableCount > 1:
        for idx in range(len(tableDFs)): # count of tableHeaders and DFs should be the same, based on the page level find_tables object
            tablePageCurrent = tablePages[idx]
            dataFrame = tableDFs[idx]
            header = tableHeaders[idx]
            for keyword in keywordsCAT:
                if keyword.lower() in header[0].lower():
                    colName = header[0]
                    uniqueC = dataFrame[colName].dropna().unique().tolist() # unique list of phrases in left hand col of table
                    tablepageCurrentTrue = tablePageCurrent
                    for messyCat in uniqueC:
                        if messyCat:
                            tidyCat = messyCat.replace('\n',' ').lower()
                            uniqueCats.append(tidyCat)
                            table_idx.append(idx)
                elif header[0] == 'Col0' and tablePageCurrent - tablepageCurrentTrue == 1: # the condition where the last keyword-compliant table processed was one page before the current table 
                    uniqueC = dataFrame['Col0'].dropna().unique().tolist()
                    if uniqueC:
                        for messyCat in uniqueC:
                            if messyCat:
                                tidyCat = messyCat.replace('\n',' ').lower()
                                uniqueCats.append(tidyCat)
                                table_idx.append(idx)
            tablePagePrior = tablePageCurrent
        uniqueCatsNoDupes = list(set(uniqueCats))

    return uniqueCatsNoDupes, table_idx

In [9]:
# clean up spurious table content and assess presence of enerygy systems

def tableClean(language, uniqueCatsNoDupes, sim_th_en, sim_th_pt, sim_th_es, cleanup_TH_en, cleanup_TH_pt, cleanup_TH_es):

    if language == 'PT':
        re = renewable_energy_pt
        not_re = not_re_cat_words_pt
        all = all_cat_words_pt
        nlp = nlp_pt
        cleanup_TH = cleanup_TH_pt
        similarity_threshold = sim_th_pt
    elif language == 'ES':
        re = renewable_energy_es
        not_re = not_re_cat_words_es
        all = all_cat_words_es
        nlp = nlp_es
        cleanup_TH = cleanup_TH_es
        similarity_threshold = sim_th_es
    elif language == 'EN':
        re = renewable_energy_en
        not_re = not_re_cat_words_en
        all = all_cat_words_en
        nlp = nlp_en
        cleanup_TH = cleanup_TH_en
        similarity_threshold = sim_th_en

    CatwordsFinal = []
    simScores_cln = {}
    notresimScores = {}
    resimScores = {}
    energy_system_tbl = ""

    if len(uniqueCatsNoDupes) > 0:
        for cat in uniqueCatsNoDupes: # phrases from tables' left hand cols
            docCat = nlp(cat) # run phrase through nlp pipeline
            for wordx in all:
                docx = nlp(wordx)
                simScore_cln = docCat.similarity(docx) # compare each cat phrase to all ref words
                if simScore_cln >= cleanup_TH: 
                    CatwordsFinal.append(cat)
                    simScores_cln[cat + ' ' + wordx] = simScore_cln 
                    dfsimScores_cln = pd.DataFrame.from_dict(simScores_cln, 'index')
                    CatwordsFFinal = list(set(CatwordsFinal))
        if len(CatwordsFinal) > 0: # cond based on attribute 'guaranteed' to exist (ie not None) to avoid runtime error but still logically sound
            for phrase in CatwordsFFinal: # only phrases that pass the cleanup TH and based on de-duped list
                docPhrase = nlp(phrase)
                for wordy in docPhrase:
                    if wordy.has_vector:
                        for worda in re: # for es noise clean up, none in RE list
                            doca = nlp(worda)
                            resimScore = wordy.similarity(doca) # compare each word (token) in each cat phrase to renewable energy ref words
                            if resimScore >= similarity_threshold:
                                resimScores[worda] = resimScore
                                dfresimScores = pd.DataFrame.from_dict(resimScores, 'index')
            if resimScores:                     
                energy_system_tbl = True
            else:
                energy_system_tbl = False
                dfresimScores = pd.DataFrame()
        else:
            CatwordsFFinal = []
            dfsimScores_cln = pd.DataFrame()
            dfresimScores = pd.DataFrame()
    else:
        CatwordsFFinal = []
        dfsimScores_cln = pd.DataFrame()
        dfresimScores = pd.DataFrame()

    return CatwordsFFinal, CatwordsFinal, dfsimScores_cln, simScores_cln, dfresimScores, resimScores, energy_system_tbl

In [36]:
# to find the Use of Proceeds portion of the document, returns font info for key phrases that typically indicate the start and end of that portion

def fontInfo(language, document):

    results_UOP = []
    results_SEEGP = []
    
    pdf = pymupdf.open(document)
    
    if language == 'PT':
        keywordsUOP = ['Usos dos Recursos', 'Uso de Recursos', 'Uso dos Recursos']
        keywordsSEEGP = ['Selection and Evaluation', 'Process for the Project Evaluation and Selection', 'Project Evaluation and Selection Process', 'Project Selection and Evaluation Process', 'Process for Project Evaluation and Selection', 'Project Selection and Assessment Process', 'Project Selection Criteria', 'Project evaluation & selection', 'Project Selection Process']
        keywordsSEEGP_test = ['Avaliação e Seleção de Ativos', 'Processo de Avaliação e Seleção de Projetos']
    elif language == 'ES':
        keywordsUOP = ['Uso de los Fondos', 'Uso de Fondos', 'Uso de Recursos', 'Destinos de Fondos', 'Uso de los Recursos']
        keywordsSEEGP_test = ['Proceso de Evaluación y Selección de Proyectos', 'Selección y Evaluación de Proyectos', 'Procedimiento Selección', 'Evaluación y selección de proyectos']
    elif language == 'EN':
        keywordsUOP = ['Use of Proceeds', 'Use of Funds', 'Use of the Proceeds']
        keywordsSEEGP = ['Selection and Evaluation', 'Process for the Project Evaluation and Selection', 'Project Evaluation and Selection Process', 'Project Selection and Evaluation Process', 'Process for Project Evaluation and Selection', 'Project Selection and Assessment Process', 'Project Selection Criteria', 'Project evaluation & selection', 'Project Selection Process']
        keywordsSEEGP_test = ['Selection and Evaluation', 'Process for', 'Evaluation and Selection', 'Project Evaluation', 'Assessment Process', 'Selection process', 'Project selection criteria']


    for page_idx in range(len(pdf)): 
        page = pdf[page_idx]
        dict = page.get_text("dict")
        blocks = dict["blocks"] 
        for block in blocks:
            if "lines" in block.keys():
                spans = block['lines']
                for span in spans:
                    data = span['spans']
                    for lines in data:
                        for keyword in keywordsUOP:
                            if keyword.lower() in lines['text'].lower().strip():
                                results_UOP.append((lines['text'], lines['size'], lines['bbox'], page_idx))
                        for keyword in keywordsSEEGP_test:
                            if keyword.lower() in lines['text'].lower().strip():
                                results_SEEGP.append((lines['text'], lines['size'], lines['bbox'], page_idx))

                            

    return results_UOP, results_SEEGP

In [45]:
# from the results of the previous function, returns the result index containing the highest font size, assuming this is a section header 

def find_max_font(results_UOP, results_SEEGP):
    
    max_font_size_UOP = 0
    if len(results_UOP) == 0:
        max_idx_UOP = 0
    else:
        for result_idx_UOP in range(len(results_UOP)):
            resultA = results_UOP[result_idx_UOP]
            if resultA[1] > max_font_size_UOP:
                max_font_size_UOP = resultA[1]
                max_idx_UOP = result_idx_UOP

    max_font_size_SEEGP = 0
    if len(results_SEEGP) == 0:
        max_idx_SEEGP = 0
    else:       
        for result_idx_SEEGP in range(len(results_SEEGP)):
            resultB = results_SEEGP[result_idx_SEEGP]
            if resultB[1] > max_font_size_SEEGP:
                max_font_size_SEEGP = resultB[1]
                max_idx_SEEGP = result_idx_SEEGP

    return max_idx_UOP, max_idx_SEEGP

In [12]:
# corrects the UOP portion in the cases where the functions above have returned the table of contents instances of the start and end key phrases 

def tocCheck(results_UOP, results_SEEGP, max_idx_UOP, max_idx_SEEGP):
    
    if len(results_SEEGP) == 0:
        areaUOP = results_UOP[max_idx_UOP]
        areaUOP_page = areaUOP[3]
        areaUOP_coords = areaUOP[2]
        areaUOP_y1 = areaUOP_coords[3]
        areaSEEGP_page = 0
        areaSEEGP_y0 = 0

    else:
        areaUOP = results_UOP[max_idx_UOP]
        areaSEEGP = results_SEEGP[max_idx_SEEGP]
        areaUOP_page = areaUOP[3]
        areaSEEGP_page = areaSEEGP[3]
        areaUOP_coords = areaUOP[2]
        areaSEEGP_coords = areaSEEGP[2]
        areaUOP_y1 = areaUOP_coords[3]
        areaSEEGP_y0 = areaSEEGP_coords[1]

        if areaUOP_page == areaSEEGP_page:
            if 0 < areaSEEGP_y0 - areaUOP_y1 < 40:
                results_UOP_remove = results_UOP.pop(max_idx_UOP)
                results_SEEGP_remove = results_SEEGP.pop(max_idx_SEEGP)

                max_idx_UOP, max_idx_SEEGP = find_max_font(results_UOP, results_SEEGP)

                areaUOP = results_UOP[max_idx_UOP]
                areaSEEGP = results_SEEGP[max_idx_SEEGP]
                areaUOP_page = areaUOP[3]
                areaSEEGP_page = areaSEEGP[3]
                areaUOP_coords = areaUOP[2]
                areaSEEGP_coords = areaSEEGP[2]
                areaUOP_y1 = areaUOP_coords[3]
                areaSEEGP_y0 = areaSEEGP_coords[1]

    return areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0

In [13]:
# discards the UOP end boundary in cases where it comes before the start boundary

def keepSEEGP(areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0):

    if areaSEEGP_page == areaUOP_page:
        if areaSEEGP_y0 < areaUOP_y1:
            keep_areaSEEGP = False
        elif areaSEEGP_y0 > areaUOP_y1:
            keep_areaSEEGP = True
    elif areaSEEGP_page > areaUOP_page:
        keep_areaSEEGP = True
    elif areaSEEGP_page < areaUOP_page:
        keep_areaSEEGP = False

    return keep_areaSEEGP

In [14]:
# page scenarios and extract words when keep_areaSEEGP = True
# function called by another function

def wordsUOP_endPage(document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0):

    pdf = pymupdf.open(document)
    extractUOPwords = []

    # iterate pages
    for page_idx in range(len(pdf)):
        page = pdf[page_idx]

       
# process four page scenarios and extract text as words
    # A: UOP all on a single page
        if page_idx == areaUOP_page and page_idx == areaSEEGP_page:
            for word in page.get_text('words'):
                x0, y0, x1, y1, messyText, *_ = word
                if y0 > areaUOP_y1 and y1 < areaSEEGP_y0:
                    tidyText = messyText.replace('\n',' ').lower()
                    extractUOPwords.append(tidyText)

    # UOP across >1 page
    # B: current page is start page
        elif page_idx == areaUOP_page:
            for word in page.get_text('words'):
                x0, y0, x1, y1, messyText, *_ = word
                if y0 > areaUOP_y1:
                    tidyText = messyText.replace('\n',' ').lower()
                    extractUOPwords.append(tidyText)

    # D: current page is neither start nor end page but is in the UOP area
        elif page_idx > areaUOP_page and page_idx < areaSEEGP_page:
            for word in page.get_text('words'):
                x0, y0, x1, y1, messyText, *_ = word
                tidyText = messyText.replace('\n',' ').lower()
                extractUOPwords.append(tidyText)

    # C: current page is end page
        elif page_idx == areaSEEGP_page:
                for word in page.get_text('words'):
                    x0, y0, x1, y1, messyText, *_ = word
                    if y1 < areaSEEGP_y0:
                        tidyText = messyText.replace('\n',' ').lower()
                        extractUOPwords.append(tidyText)

    return extractUOPwords

In [15]:
# iterate pages in the pdf and extract words, preferrably between the UOP and SEEGP sections or else from UOP to end

def wordsUOP(keep_areaSEEGP, document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0):
    # language = language

    pdf = pymupdf.open(document)

    if keep_areaSEEGP == True:
        extractUOPwords = wordsUOP_endPage(document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0) # calls function in cell above
        UOPwordsNoDupes = list(set(extractUOPwords))

    elif keep_areaSEEGP == False:
        extractUOPwords = [] # deals with page scenarios when word search area extends beyond UOP to the end of the pdf   

# iterate pages
        for page_idx in range(len(pdf)):
            page = pdf[page_idx]
       
    # process two page scenarios and extract text as words

        # assume UOP across > 1 page
        # B: current page is start page
            if page_idx == areaUOP_page:
                for word in page.get_text('words'):
                    x0, y0, x1, y1, messyText, *_ = word
                    if y0 > areaUOP_y1:
                        tidyText = messyText.replace('\n',' ').lower()
                        extractUOPwords.append(tidyText)

        # E: current page is after the UOP start page
            elif page_idx > areaUOP_page:
                for word in page.get_text('words'):
                    x0, y0, x1, y1, messyText, *_ = word
                    tidyText = messyText.replace('\n',' ').lower()
                    extractUOPwords.append(tidyText)
    
        UOPwordsNoDupes = list(set(extractUOPwords))
    
    return UOPwordsNoDupes

In [16]:
# process words into category word dictionaries where doc.similarity score passes threshold

def UOPwords_to_Catwords(language, UOPwordsNoDupes, sim_th_en, sim_th_pt, sim_th_es):

    es_noise = ['.', 'y', 'la', 'de', 'no', 'red', 'dis', 'non']

    if language == 'EN':
        nlp = nlp_en
        re = renewable_energy_en
        ee = energy_efficiency_en
        ppc = pollution_prevention_and_control_en
        esml = environmentally_sustainable_management_of_living_natural_resources_and_land_use_en
        tabc = terrestrial_and_aquatic_biodiversity_conservation_en
        ct = clean_transportation_en
        swwm = sustainable_water_and_wastewater_management_en
        cca = climate_change_adaptation_en
        ce = circular_economy_and_or_ecoefficient_projects_en
        gb = green_buildings_en
        similarity_threshold = sim_th_en
    elif language == 'PT':
        nlp = nlp_pt
        re = renewable_energy_pt
        ee = energy_efficiency_pt
        ppc = pollution_prevention_and_control_pt
        esml = environmentally_sustainable_management_of_living_natural_resources_and_land_use_pt
        tabc = terrestrial_and_aquatic_biodiversity_conservation_pt
        ct = clean_transportation_pt
        swwm = sustainable_water_and_wastewater_management_pt
        cca = climate_change_adaptation_pt
        ce = circular_economy_and_or_ecoefficient_projects_pt
        gb = green_buildings_pt
        similarity_threshold = sim_th_pt
    elif language == 'ES':
        nlp = nlp_es
        re = renewable_energy_es
        ee = energy_efficiency_es
        ppc = pollution_prevention_and_control_es
        esml = environmentally_sustainable_management_of_living_natural_resources_and_land_use_es
        tabc = terrestrial_and_aquatic_biodiversity_conservation_es
        ct = clean_transportation_es
        swwm = sustainable_water_and_wastewater_management_es
        cca = climate_change_adaptation_es
        ce = circular_economy_and_or_ecoefficient_projects_es
        gb = green_buildings_es
        similarity_threshold = sim_th_es

    # outputs
    simsre = {}
    energy_system_uop = ""
    simsee = {}
    simsppc = {}
    simsesml = {}
    simstabc = {}
    simsct = {}
    simsswwm = {}
    simscca = {}
    simsce = {}
    simsgb = {}
    cat_count_uop = 0
    

    for wordb in UOPwordsNoDupes:
        docb = nlp(wordb)
        for token in docb: # expect each docb has only 1 token
            if token.has_vector:
                   
        # renewable_energy
                for worda in re:
                    doca = nlp(worda)
                    for token in doca:
                        if token.text not in es_noise:
                            sim = doca.similarity(docb)
                            if sim >= similarity_threshold:
                                simsre[doca[0].text + ' ' + docb[0].text] = sim

        # energy_efficiency
                for wordc in ee:
                    docc = nlp(wordc)
                    for token in docc:
                        if token.text not in es_noise:
                            sim = docc.similarity(docb)
                            if sim >= similarity_threshold:
                                simsee[docc[0].text + ' ' + docb[0].text] = sim
        
        # pollution_prevention_and_control
                for wordd in ppc:
                    docd = nlp(wordd)
                    for token in docd:
                        if token.text not in es_noise:
                            sim = docd.similarity(docb)
                            if sim >= similarity_threshold:
                                simsppc[docd[0].text + ' ' + docb[0].text] = sim

        # environmentally_sustainable_management_of_living_natural_resources_and_land_use
                for worde in esml:
                    doce = nlp(worde)
                    for token in doce:
                        if token.text not in es_noise:
                            sim = doce.similarity(docb)
                            if sim >= similarity_threshold:
                                simsesml[doce[0].text + ' ' + docb[0].text] = sim

        # terrestrial_and_aquatic_biodiversity_conservation
                for wordf in tabc:
                    docf = nlp(wordf)
                    for token in docf:
                        if token.text not in es_noise:
                            sim = docf.similarity(docb)
                            if sim >= similarity_threshold:
                                simstabc[docf[0].text + ' ' + docb[0].text] = sim

        # clean_transportation
                for wordg in ct:
                    docg = nlp(wordg)
                    for token in docg:
                        if token.text not in es_noise:
                            sim = docg.similarity(docb)
                            if sim >= similarity_threshold:
                                simsct[docg[0].text + ' ' + docb[0].text] = sim

        # sustainable_water_and_wastewater_management
                for wordh in swwm:
                    doch = nlp(wordh)
                    for token in doch:
                        if token.text not in es_noise:
                            sim = doch.similarity(docb)
                            if sim >= similarity_threshold:
                                simsswwm[doch[0].text + ' ' + docb[0].text] = sim

        # climate_change_adaptation
                for wordi in cca:
                    doci = nlp(wordi)
                    for token in doci:
                        if token.text not in es_noise:
                            sim = doci.similarity(docb)
                            if sim >= similarity_threshold:
                                simscca[doci[0].text + ' ' + docb[0].text] = sim
        
        # circular_economy_and_or_ecoefficient_projects
                for wordj in ce:
                    docj = nlp(wordj)
                    for token in docj:
                        if token.text not in es_noise:
                            sim = docj.similarity(docb)
                            if sim >= similarity_threshold:
                                simsce[docj[0].text + ' ' + docb[0].text] = sim
        
        # green_buildings
                for wordk in gb:
                    dock = nlp(wordk)
                    for token in dock:
                        if token.text not in es_noise:
                            sim = dock.similarity(docb)
                            if sim >= similarity_threshold:
                                simsgb[dock[0].text + ' ' + docb[0].text] = sim

    if simsre:
        energy_system_uop = True
        cat_count_uop +=1
    else:
        energy_system_uop = False
    if simsee:
        cat_count_uop +=1
    if simsppc:
        cat_count_uop +=1
    if simsesml:
        cat_count_uop +=1
    if simstabc:
        cat_count_uop +=1
    if simsct:
        cat_count_uop +=1
    if simsswwm:
        cat_count_uop +=1
    if simscca:
        cat_count_uop +=1
    if simsce:
        cat_count_uop +=1
    if simsgb:
        cat_count_uop +=1

    return simsre, simsee, simsppc, simsesml, simstabc, simsct, simsswwm, simscca, simsce, simsgb, energy_system_uop, cat_count_uop

In [133]:
# list of pdf filenames

pdf_en = ['Bci_Sustainable_Financing_Framework','BTG_Pactual_Green,_Social_and_Sustainable_Financing_Framework',
          'BTG_Sustainable_Financing_Framework','CABEI_Green_Bond_Framework','CADU_GREEN_BOND_FRAMEWORK',
          'CAFs_GREEN_BOND_FRAMEWORK','CIFI_Green_Bond_Framework','EGE_Haina_Green_Securities_Framework',
          'FS_Green_Bond_Framework_-_July_2021','FS_Green_Bond_Framework_-_November_2020','Genneia_Green_Bond_Framework', 
          'Green_Bond_Financing_Framework','Green_Bond_Framework_of_Banco_Guayaquil',
          'Green_Finance_Framework_Interchile','Green_social_bond_framework_series_ad_ae_2019',
          'ILAP_Green_Financing_Framework','ISA_CTM_FRAMEWORK','Marco_de_referencia_de_Bonos_Verdes_Soberanos_de_Colombia',
          'Nacional_Financiera_Green_Bond_USD','Sicredi_Green_Bond_Framework','SONDA_S_A__GREEN_BOND_FRAMEWORK']
pdf_en_lines =['Chile_Sustainable_Bond_Framework', 'Genneia_Green_Financing_Framework']
pdf_es = ['Bono_Azul_-_Framework','Bono_Verde_de_Bancoldex_Framework','Cartilla_Bonos_Verdes','Marco_de_Gestión_de_Bono_Verde',
          'Marco_de_referencia_de_bono_verde_Coopeguanacaste,_R_L_','Marco_de_Referencia_del_Bono_Verde_de_la_Ciudad_de_Mexico',
          'Nacional_Financiera_Green_Bond_MXN']
pdf_es_lines = ['Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos_Verdes,_Sociales_o_Sostenibles_BDP_I']
pdf_pt = ['Green_Bond_Framework', 'Green_Bonds_Framework_Athon_2020']


# manual baseline pdfs
pdf_man_base_en = ['BNDES_Green_Bond_Framework','Climate_Bond_Framework_of_Athon_in_2021','Framework,_Green_Bond_Protisa_Peru',
                   'Green_Bond_Framework', 'Green_social_bond_framework_series_ab_ac_2018',
                   'greenbondsprogramme','Rumo_Green_Bond_2028_Framework','Sustainability_Bond_Framework',
                   'wcc-green-bond-second-party-opinion-05222019']
pdf_man_base_en_lines = ['FEFA_20V_Green_Bond_Framework', 'FEFA_Green_Bond_Framework']
pdf_man_base_en_test = ['']
pdf_man_base_es = ['Green_Bonds_Framework_-_Banco_Pichincha', 'Marco_de_la_Primera_Emision', 'Marco_del_Bono_Verde']
pdf_man_base_pt = ['Framework_ISA_CTEEP']

# 'Integrated-Report-2017'

In [145]:
# run the pdf through the pipeline - first pdf, initialise the dataframes
# run4 TH's=0.65
# run5 STH =0.80, CTH=0.65
# run6 STH =0.88, CTH=0.70
# run7 fixes from testing / STH =0.97, CTH=0.77 (2nd Pass)
# run8 EN .97 & .77, ES .8 & .65, PT .88 & .70 (because training on v low number of rpts, risk of overfitting)
# manual baseline

# input parameters
document = '/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/PDF1/Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__in_2021.pdf'
language = 'EN'
tableStrategy = 'lines_strict'

#similarity_th = 0.97
#cleanup_th = 0.77

# set thresholds - set by language for run 8 and manual baseline
sim_th_en = 0.97
sim_th_es = 0.8
sim_th_pt = 0.88
cleanup_TH_en = 0.77
cleanup_TH_es = 0.65
cleanup_TH_pt = 0.70

# call the functions in sequence
filename, pdfname, tableCount, tablePages, tableHeaders, tableDFs = catTable(document, tableStrategy)
uniqueCatsNoDupes, table_idx = tableAssess(language, tableCount, tablePages, tableHeaders, tableDFs)
CatwordsFFinal, CatwordsFinal, dfsimScores_cln, simScores_cln, dfresimScores, resimScores, energy_system_tbl = tableClean(language, uniqueCatsNoDupes, sim_th_en, sim_th_pt, sim_th_es, cleanup_TH_en, cleanup_TH_pt, cleanup_TH_es)
results_UOP, results_SEEGP = fontInfo(language, document)
max_idx_UOP, max_idx_SEEGP = find_max_font(results_UOP, results_SEEGP)
areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0 = tocCheck(results_UOP, results_SEEGP, max_idx_UOP, max_idx_SEEGP)
keep_areaSEEGP = keepSEEGP(areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0)
UOPwordsNoDupes = wordsUOP(keep_areaSEEGP, document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0)

# dataframe output for transparency on how pipeline has processed the pdf
columns = ['pdfname', 'language', 'tableCount', 'areaUOP_page', 'areaUOP_y1', 'areaSEEGP_page', 'areaSEEGP_y0', 'keep_areaSEEGP', 'countUOP_words']
results_df = pd.DataFrame(columns=columns)
results_df.loc[len(results_df)] = [pdfname, language, tableCount, areaUOP_page, areaUOP_y1, areaSEEGP_page,areaSEEGP_y0, keep_areaSEEGP, len(UOPwordsNoDupes)]

# table info
columns = ['pdfname', 'tablePages_list', 'table.Headers_list', 'countCat_words', 'unique compliant Categories_list', 'energy_system_tbl', 'unique Cats all', 'simScores_cln', 'resimScores']
table_df = pd.DataFrame(columns=columns)

# UOP start and end info
columns = ['pdfname', 'results_UOP_list (text, fontSize, bbox, page_idx)', 'max_idx_UOP', 'results_SEEGP_list (text, fontSize, bbox, page_idx)', 'max_idx_SEEGP']
UOP_df = pd.DataFrame(columns=columns)
UOP_df.loc[len(UOP_df)] = [pdfname, results_UOP, max_idx_UOP, results_SEEGP, max_idx_SEEGP]

# initialise sim score dicts
ttlsimsre = {}
ttlsimsee = {}
ttlsimsppc = {}
ttlsimsesml = {}
ttlsimstabc = {}
ttlsimsct = {}
ttlsimsswwm = {}
ttlsimscca = {}
ttlsimsce = {}
ttlsimsgb = {}
ttlresimScores = {}
ttlsimScores_cln = {}

# final Cateogory info
if len(CatwordsFinal) == 0:
    print('')
    print(pdfname)
    print('categories from UOP portion')
    simsre, simsee, simsppc, simsesml, simstabc, simsct, simsswwm, simscca, simsce, simsgb, energy_system_uop, cat_count_uop = UOPwords_to_Catwords(language, UOPwordsNoDupes, sim_th_en, sim_th_pt, sim_th_es)
    columns = ['pdfname', 'energy_system_uop', 'simsre', 'simsee', 'simsppc', 'simsesml', 'simstabc', 'simsct', 'simsswwm', 'simscca', 'simsce', 'simsgb']
    UOP_Words_df = pd.DataFrame(columns=columns)
    UOP_Words_df.loc[len(UOP_Words_df)] = [pdfname, energy_system_uop, simsre, simsee, simsppc, simsesml, simstabc, simsct, simsswwm, simscca, simsce, simsgb]
    
    ttlsimsre |= simsre
    ttlsimsee |= simsee
    ttlsimsppc |= simsppc
    ttlsimsesml |= simsesml
    ttlsimstabc |= simstabc
    ttlsimsct |= simsct
    ttlsimsswwm |= simsswwm
    ttlsimscca |= simscca
    ttlsimsce |= simsce
    ttlsimsgb |= simsgb

else:
    print('')
    print(pdfname)
    print('categories from tables')
    table_df.loc[len(table_df)] = [pdfname, tablePages, tableHeaders, len(CatwordsFFinal), CatwordsFFinal, energy_system_tbl, uniqueCatsNoDupes, simScores_cln, resimScores]

    ttlresimScores |= resimScores
    ttlsimScores_cln |= simScores_cln

# data table with results, for evaluation to ground truth
# nlp_path 
nlp_path = ""
if len(CatwordsFinal)>0:
    nlp_path = 'Table'
elif len(CatwordsFinal)==0 and keep_areaSEEGP == True:
    nlp_path = 'UOP_section_true'
elif len(CatwordsFinal)==0 and keep_areaSEEGP == False:
    nlp_path = 'UOP_section_false'

# ES percent oucomes - setting booleans and class label
ES_0_percent = False
ES_100_percent = False
ES_partial = False
ES_percent_pred = ''

if energy_system_tbl == False or energy_system_uop == False:
    ES_0_percent = True
    ES_percent_pred = 'ES 0%'

elif energy_system_tbl == True:
    if len(CatwordsFFinal) == 1: # CatwordsFFinal is the de-duped list of words that pass cleanup-threshold sim, originally the unique phrases from LHCol of qualifying tables 
        ES_100_percent = True
        ES_percent_pred = 'ES 100%'
    elif len(CatwordsFFinal) > 1:
        ES_partial = True
        ES_percent_pred = 'ES partial'

elif energy_system_uop == True:
    if cat_count_uop == 1:
        ES_100_percent = True
        ES_percent_pred = 'ES 100%'
    elif cat_count_uop > 1:
        ES_partial = True
        ES_percent_pred = 'ES partial'

# number of cats
number_of_cats = 0
if len(CatwordsFinal)>0:
    number_of_cats = len(CatwordsFFinal)
else:
    number_of_cats = cat_count_uop

# threshold params
similarity_threshold = 0.0
cleanup_threshold = 0.0
if language == 'EN':
    similarity_threshold = sim_th_en
    cleanup_threshold = cleanup_TH_en
elif language == 'ES':
    similarity_threshold = sim_th_es
    cleanup_threshold = cleanup_TH_es
elif language == 'PT':
    similarity_threshold = sim_th_pt
    cleanup_threshold = cleanup_TH_pt    

columns = ['pdfname', 'nlp_path', 'language', 'similarity_threshold', 'cleanup_threshold', 'ES_0_percent', 'ES_100_percent', 'ES_partial', 'number_of_cats']
pred_man_base_rpts = pd.DataFrame(columns=columns)
pred_man_base_rpts.loc[len(pred_man_base_rpts)] = [pdfname, nlp_path, language, similarity_threshold, cleanup_threshold, ES_0_percent, ES_100_percent, ES_partial, number_of_cats]

Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__in_2021
categories from UOP portion

In [150]:
# run the pdf through the pipeline - subsequent pdfs, populate the dataframes


# input parameters
filepath = '/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/PDFs/' # refinement runs
filepath_mb = '/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/eval_FW_rpts/'
extention = '.pdf'
language = 'PT'
tableStrategy = 'lines_strict'

if language == 'EN':
    pdf_list_name = pdf_en
elif language == 'ES':
    pdf_list_name = pdf_es
elif language == 'PT':
    pdf_list_name = pdf_pt

#similarity_th = 0.97
#cleanup_th = 0.77

# set thresholds - possible to set by language if required
sim_th_en = 0.97
sim_th_es = 0.8
sim_th_pt = 0.88
cleanup_TH_en = 0.77
cleanup_TH_es = 0.65
cleanup_TH_pt = 0.70

for pdf in pdf_list_name:
    document = filepath + pdf + extention
    energy_system_uop = ""

    # call the functions in sequence
    filename, pdfname, tableCount, tablePages, tableHeaders, tableDFs = catTable(document, tableStrategy)
    uniqueCatsNoDupes, table_idx = tableAssess(language, tableCount, tablePages, tableHeaders, tableDFs)
    CatwordsFFinal, CatwordsFinal, dfsimScores_cln, simScores_cln, dfresimScores, resimScores, energy_system_tbl, = tableClean(language, uniqueCatsNoDupes, sim_th_en, sim_th_pt, sim_th_es, cleanup_TH_en, cleanup_TH_pt, cleanup_TH_es) 
    results_UOP, results_SEEGP = fontInfo(language, document)
    max_idx_UOP, max_idx_SEEGP = find_max_font(results_UOP, results_SEEGP)
    areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0 = tocCheck(results_UOP, results_SEEGP, max_idx_UOP, max_idx_SEEGP)
    keep_areaSEEGP = keepSEEGP(areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0)
    UOPwordsNoDupes = wordsUOP(keep_areaSEEGP, document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0)

    # dataframe outputs for transparency on how pipeline has processed the pdf
    results_df.loc[len(results_df)] = [pdfname, language, tableCount, areaUOP_page, areaUOP_y1, areaSEEGP_page,areaSEEGP_y0, keep_areaSEEGP, len(UOPwordsNoDupes)]
    UOP_df.loc[len(UOP_df)] = [pdfname, results_UOP, max_idx_UOP, results_SEEGP, max_idx_SEEGP]

    # final Cateogory info
    if len(CatwordsFinal) == 0:
        print('')
        print(pdfname)
        print('categories from UOP portion')
        simsre, simsee, simsppc, simsesml, simstabc, simsct, simsswwm, simscca, simsce, simsgb, energy_system_uop, cat_count_uop = UOPwords_to_Catwords(language, UOPwordsNoDupes, sim_th_en, sim_th_pt, sim_th_es)
        UOP_Words_df.loc[len(UOP_Words_df)] = [pdfname, energy_system_uop, simsre, simsee, simsppc, simsesml, simstabc, simsct, simsswwm, simscca, simsce, simsgb]

        ttlsimsre |= simsre
        ttlsimsee |= simsee
        ttlsimsppc |= simsppc
        ttlsimsesml |= simsesml
        ttlsimstabc |= simstabc
        ttlsimsct |= simsct
        ttlsimsswwm |= simsswwm
        ttlsimscca |= simscca
        ttlsimsce |= simsce
        ttlsimsgb |= simsgb

    else:
        print('')
        print(pdfname)
        print('categories from tables')
        table_df.loc[len(table_df)] = [pdfname, tablePages, tableHeaders, len(CatwordsFFinal), CatwordsFFinal, energy_system_tbl, uniqueCatsNoDupes, simScores_cln, resimScores]

        ttlresimScores |= resimScores
        ttlsimScores_cln |= simScores_cln


    # data table with results for evaluation to ground truth
    # nlp_path 
    nlp_path = ""
    if len(CatwordsFinal)>0:
        nlp_path = 'Table'
    elif len(CatwordsFinal)==0 and keep_areaSEEGP == True:
        nlp_path = 'UOP_section_true'
    elif len(CatwordsFinal)==0 and keep_areaSEEGP == False:
        nlp_path = 'UOP_section_false'

    # ES percent oucomes
    ES_0_percent = False
    ES_100_percent = False
    ES_partial = False
    ES_percent_pred = ''

    if energy_system_tbl == False or energy_system_uop == False:
        ES_0_percent = True
        ES_percent_pred = 'ES 0%'

    elif energy_system_tbl == True:
        if len(CatwordsFFinal) == 1:
            ES_100_percent = True
            ES_percent_pred = 'ES 100%'
        elif len(CatwordsFFinal) > 1:
            ES_partial = True
            ES_percent_pred = 'ES partial'

    elif energy_system_uop == True:
        if cat_count_uop == 1:
            ES_100_percent = True
            ES_percent_pred = 'ES 100%'
        elif cat_count_uop > 1:
            ES_partial = True
            ES_percent_pred = 'ES partial'

    # number of cats
    number_of_cats = 0
    if len(CatwordsFinal)>0:
        number_of_cats = len(CatwordsFFinal)
    else:
        number_of_cats = cat_count_uop

    # threshold params
    similarity_threshold = 0.0
    cleanup_threshold = 0.0
    if language == 'EN':
        similarity_threshold = sim_th_en
        cleanup_threshold = cleanup_TH_en
    elif language == 'ES':
        similarity_threshold = sim_th_es
        cleanup_threshold = cleanup_TH_es
    elif language == 'PT':
        similarity_threshold = sim_th_pt
        cleanup_threshold = cleanup_TH_pt

    
    pred_man_base_rpts.loc[len(pred_man_base_rpts)] = [pdfname, nlp_path, language, similarity_threshold, cleanup_threshold, ES_0_percent, ES_100_percent, ES_partial, number_of_cats]

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_9598/1605589733.py:38: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simScore_cln = docCat.similarity(docx) # compare each cat phrase to all ref words

Green_Bond_Framework
categories from tables

Green_Bonds_Framework_Athon_2020
categories from UOP portion

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_9598/3521956168.py:81: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = docc.similarity(docb)

In [151]:
results_df

,pdfname,language,tableCount,areaUOP_page,areaUOP_y1,areaSEEGP_page,areaSEEGP_y0,keep_areaSEEGP,countUOP_words
0,Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__i...,EN,1,1,420.328369,2,354.484863,True,188
1,Bci_Sustainable_Financing_Framework,EN,0,7,110.545990,1,28.432018,False,909
2,"BTG_Pactual_Green,_Social_and_Sustainable_Fina...",EN,4,14,406.338043,18,499.063019,True,327
3,BTG_Sustainable_Financing_Framework,EN,1,20,80.458229,31,60.549740,True,1311
4,CABEI_Green_Bond_Framework,EN,5,7,441.189972,11,81.259979,True,387
5,CADU_GREEN_BOND_FRAMEWORK,EN,0,6,140.128403,0,758.464783,False,578
6,CAFs_GREEN_BOND_FRAMEWORK,EN,6,7,262.438385,9,336.903778,True,271
7,CIFI_Green_Bond_Framework,EN,0,7,569.777405,8,169.974762,True,66
8,EGE_Haina_Green_Securities_Framework,EN,1,10,492.464996,12,428.401001,True,275
9,FS_Green_Bond_Framework_-_July_2021,EN,0,11,455.748077,5,223.619537,False,679
10,FS_Green_Bond_Framework_-_November_2020,EN,0,7,546.994019,7,403.429993,False,653
11,Genneia_Green_Bond_Framework,EN,0,8,110.361000,9,104.296997,True,169
12,Green_Bond_Financing_Framework,EN,3,7,179.089981,8,559.180054,True,186
13,Green_Bond_Framework_of_Banco_Guayaquil,EN,16,6,109.511734,11,71.712212,True,622
14,Green_Finance_Framework_Interchile,EN,1,7,321.529999,9,111.740021,True,210
15,Green_social_bond_framework_series_ad_ae_2019,EN,3,1,98.540031,1,87.500031,False,927
16,ILAP_Green_Financing_Framework,EN,0,0,481.347198,0,470.681610,False,910
17,ISA_CTM_FRAMEWORK,EN,11,8,271.757019,3,201.050018,False,503
18,Marco_de_referencia_de_Bonos_Verdes_Soberanos_...,EN,1,14,479.131409,19,351.234100,True,731
19,Nacional_Financiera_Green_Bond_USD,EN,1,3,123.770012,3,356.360016,True,84
20,Sicredi_Green_Bond_Framework,EN,2,3,402.529999,4,579.070007,True,236
21,SONDA_S_A__GREEN_BOND_FRAMEWORK,EN,0,4,124.099983,4,435.190002,True,124
22,Chile_Sustainable_Bond_Framework,EN,13,18,217.077713,3,216.104080,False,1443
23,Genneia_Green_Financing_Framework,EN,2,1,600.482239,0,0.000000,False,1267
24,Bono_Azul_-_Framework,ES,5,1,336.792603,1,390.216888,True,15
25,Bono_Verde_de_Bancoldex_Framework,ES,1,1,492.789978,3,365.630005,True,325
26,Cartilla_Bonos_Verdes,ES,0,10,433.616699,16,464.230499,True,497
27,Marco_de_Gestión_de_Bono_Verde,ES,3,7,411.209991,2,210.830017,False,400
28,Marco_de_referencia_de_bono_verde_Coopeguanaca...,ES,18,15,89.151588,16,541.706238,True,271
29,Marco_de_Referencia_del_Bono_Verde_de_la_Ciuda...,ES,0,0,490.869995,0,395.050018,False,818
30,Nacional_Financiera_Green_Bond_MXN,ES,6,3,188.569992,3,534.459961,True,99
31,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,ES,43,5,102.917595,32,535.163818,True,2949
32,Green_Bond_Framework,PT,5,1,304.611969,15,133.837967,True,1602
33,Green_Bonds_Framework_Athon_2020,PT,2,4,428.291565,6,551.981140,True,379

In [152]:
table_df

,pdfname,tablePages_list,table.Headers_list,countCat_words,unique compliant Categories_list,energy_system_tbl,unique Cats all,simScores_cln,resimScores
0,"BTG_Pactual_Green,_Social_and_Sustainable_Fina...","[15, 16, 17, 19]","[[Green\nProject\nCategory, Use of\nProceeds, ...",4,"[green buildings, afof rdable housing, renewab...",True,"[afof rdable basic infrastructure, renewable e...",{'renewable energy renewable': 0.9201155304908...,{'renewable': 1.0}
1,CABEI_Green_Bond_Framework,"[7, 8, 9, 10, 12]","[[Eligible\nGreen\nProjects\nCategories, Sub-c...",2,"[renewable energy, water management]",True,"[clean transport, renewable energy, water mana...",{'renewable energy renewable': 0.9201155304908...,{'renewable': 1.0}
2,CAFs_GREEN_BOND_FRAMEWORK,"[1, 2, 8, 9]","[[Measure of Units, Col1], [Graphics, Content]...",3,"[waste management, renewable energy, clean tra...",True,[sustainable management of living natural reso...,"{'waste management waste': 0.8286465406417847,...",{'renewable': 1.0}
3,Green_Bond_Financing_Framework,"[7, 8, 10]",[[Eligible Category aligned\nwith ICMA Green B...,2,"[energy efficiency, clean transportation]",False,"[energy efficiency, clean transportation]",{'energy efficiency efficiency': 0.90048879384...,{}
4,Green_Bond_Framework_of_Banco_Guayaquil,"[6, 7, 8, 9, 10, 18, 19, 29, 30, 31, 38, 39]","[[GBP Eligible\nGreen Assets\nCategory, Banco ...",2,"[energy efficiency, renewable energy]",True,"[energy efficiency, renewable energy]",{'energy efficiency efficiency': 0.90048879384...,{'renewable': 1.0}
5,Green_Finance_Framework_Interchile,[8],"[[Eligible Project Category, Questions, Alignm...",2,"[energy efficiency, renewable energy]",True,"[renewable energy, energy efficiency, climate ...",{'renewable energy renewable': 0.9201155304908...,{'renewable': 1.0}
6,Green_social_bond_framework_series_ad_ae_2019,"[3, 6, 7]","[[Category, Project name, Goal], [Categories o...",2,"[potable water supply, sanitation]",False,"[resilient infrastructure, potable water suppl...",{'potable water supply water': 0.8469440937042...,{}
7,ISA_CTM_FRAMEWORK,"[4, 5, 7, 8, 9, 15, 16, 17, 18]","[[Eligible Project Category, Questions, Alignm...",2,"[energy efficiency, renewable energy]",True,"[energy efficiency, renewable energy]",{'energy efficiency efficiency': 0.90048879384...,{'renewable': 1.0}
8,Sicredi_Green_Bond_Framework,"[4, 6]","[[Eligible\nCategories, Description, Objective...",2,"[energy efficiency, renewable energy]",True,"[energy efficiency, renewable energy]",{'energy efficiency efficiency': 0.90048879384...,{'renewable': 1.0}
9,Chile_Sustainable_Bond_Framework,"[0, 19, 20, 21, 22, 23, 24, 25, 26, 30, 37, 38...","[[Col0, Ministry of\nFinance\nGovernment of Ch...",5,"[food security, green buildings (ecological bu...",True,"[food security, green buildings (ecological bu...","{'food security food': 0.7798810005187988, 'gr...",{'renewable': 1.0}
10,Genneia_Green_Financing_Framework,"[5, 7]","[[Col0, 20161, 20202, 20251, 20301], [Eligible...",1,[renewable energy],True,[renewable energy],{'renewable energy renewable': 0.9201155304908...,{'renewable': 1.0}
11,Marco_de_Gestión_de_Bono_Verde,"[5, 8, 9]","[[Norma de\nDesempeño, Estatus1, Descripción],...",1,[proyecto de energías renovables (energía hidr...,True,[proyecto de energías renovables (energía hidr...,{'proyecto de energías renovables (energía hid...,"{'cuadrícula (sólo)': 0.9524129033088684, 'bio..."
12,Nacional_Financiera_Green_Bond_MXN,"[3, 9, 10, 11, 17]","[[Categoría, Actividades elegibles], [Col0, Pr...",2,"[centrales eólicas (solo terrestres), pequeñas...",True,"[centrales eólicas (solo terrestres), pequeñas...",{'centrales eólicas (solo terrestres) cuadrícu...,"{'cuadrícula (sólo)': 0.9524129033088684, 'hid..."
13,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,"[3, 4, 8, 16, 18, 19, 20, 21, 22, 23, 24, 25, ...",[[Contribuciones Nacionales Determinadas (NDCs...,1,[energías renovables],False,"[eficiencia energética49 50, verdes, energías ...",{'energías renovables renovable': 0.7062243223...,{}
14,Green_Bond_Framework,"[10, 14, 19, 21, 22]","[[Categoria, Descrição], [Projeto, Capaci\nda ...",1,[energia renovável],True,"[transmissão de energia, energia renovável]",{'energia renovável energia': 0.91402691602706...,"{'energia': 1.0, 'energia hidráulica': 0.90849..."

In [153]:
UOP_df

,pdfname,"results_UOP_list (text, fontSize, bbox, page_idx)",max_idx_UOP,"results_SEEGP_list (text, fontSize, bbox, page_idx)",max_idx_SEEGP
0,Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__i...,"[(Use of Proceeds , 11.039999961853027, (85.1...",0,[(Selection and Evaluation of Eligible Green P...,0
1,Bci_Sustainable_Financing_Framework,"[(Green Use of Proceeds instruments: , 9.0, (6...",10,"[(Process for , 9.0, (277.7300109863281, 28.43...",0
2,"BTG_Pactual_Green,_Social_and_Sustainable_Fina...","[(Use of Proceeds , 12.0, (184.590087890625, 6...",3,"[(Process for Project , 12.0, (184.59008789062...",5
3,BTG_Sustainable_Financing_Framework,"[(Use of Proceeds, 13.0, (241.72439575195312, ...",2,[(Process for Project Selection and Evaluation...,4
4,CABEI_Green_Bond_Framework,[(Use of Proceeds ...............................,1,[(Process for Project Evaluation and Selection...,3
5,CADU_GREEN_BOND_FRAMEWORK,"[(Use of Proceeds , 11.039999961853027, (84.98...",0,"[(selection processes; and, the reporting meth...",0
6,CAFs_GREEN_BOND_FRAMEWORK,[(1. Use of Proceeds ............................,2,[(2. Process for Project Evaluation and Select...,6
7,CIFI_Green_Bond_Framework,"[(a. Use of Proceeds, 12.531599998474121, (69....",0,"[(b. Project Selection Criteria , 12.531599998...",0
8,EGE_Haina_Green_Securities_Framework,"[(• Use of Proceeds\t, 10.0, (259.912902832031...",5,[(• Project Selection and Evaluation Process\t...,1
9,FS_Green_Bond_Framework_-_July_2021,"[(Use of Proceeds , 12.000450134277344, (110.6...",0,"[(theme within the company. Furthermore, in th...",0
10,FS_Green_Bond_Framework_-_November_2020,"[(Use of Proceeds , 12.0, (110.66000366210938,...",0,[(Capital Markets Association are voluntary pr...,0
11,Genneia_Green_Bond_Framework,"[( Use of Proceeds, 13.0, (253.3719940185547,...",1,"[(Process for Project Evaluation , 13.0, (269...",2
12,Green_Bond_Financing_Framework,"[(Use of Proceeds , 11.039999961853027, (108.0...",1,[(5.2 Process of Project Evaluation and S...,5
13,Green_Bond_Framework_of_Banco_Guayaquil,[(First Principle – Use of Proceeds .............,3,[(Second Principle – Process for Project Evalu...,6
14,Green_Finance_Framework_Interchile,[(4.1 Use of Proceeds ...........................,2,[(4.2 Process for Project Evaluation and Selec...,5
15,Green_social_bond_framework_series_ad_ae_2019,"[(SBPs: Use of Funds, Evaluation and Selection...",0,"[(SBPs: Use of Funds, Evaluation and Selection...",0
16,ILAP_Green_Financing_Framework,"[(1. Use of proceeds , 8.800000190734863, (77....",0,[( 2. Process for project evaluation and selec...,0
17,ISA_CTM_FRAMEWORK,"[(Use of the proceeds , 11.039999961853027, (1...",4,"[(Process for Evaluation and Selection , 11.03...",0
18,Marco_de_referencia_de_Bonos_Verdes_Soberanos_...,"[(Use of proceeds , 11.0, (360.3396911621094, ...",3,"[(Process for Project Evaluation and , 11.0, (...",5
19,Nacional_Financiera_Green_Bond_USD,"[(3.1 Use of Proceeds , 11.039999961853027, (9...",2,"[(3.2 Project Selection Process , 11.039999961...",1
20,Sicredi_Green_Bond_Framework,[(2.1 Use of Proceeds ...........................,2,[(2.2 Project evaluation & selection ............,3
21,SONDA_S_A__GREEN_BOND_FRAMEWORK,[(3.1 Use of Proceeds ...........................,1,[(3.2 Project Selection and Assessment Process...,1
22,Chile_Sustainable_Bond_Framework,"[(Use of Proceeds, 8.0, (311.42449951171875, 5...",2,"[(Project Evaluation , 11.0, (123.502014160156...",0
23,Genneia_Green_Financing_Framework,"[(Use of proceeds, 9.0, (73.48359680175781, 58...",0,[],0
24,Bono_Azul_-_Framework,"[(2.1 Uso de los recursos , 12.0, (41.13280105...",0,[(2.2 Proceso de evaluación y selección de pr...,0
25,Bono_Verde_de_Bancoldex_Framework,"[(Uso de los recursos , 12.0, (113.41999816894...",0,[(ingresos o recursos; (ii) proceso de evaluac...,2
26,Cartilla_Bonos_Verdes,"[(Uso de Fondos Proyectos Verdes Elegibles , 1...",3,"[(Procedimiento Selección y Evaluación , 12.0,...",2
27,Marco_de_Gestión_de_Bono_Verde,[(Uso de los Fondos .............................,2,[(Proceso de Selección y Evaluación de Proyect...,1
28,Marco_de_referencia_de_bono_verde_Coopeguanaca...,[(Destinos de Fondos. ...........................,1,[(Proceso de evaluación y selección de proyect...,2
29,Marco_de_Referencia_del_Bono_Verde_de_la_Ciuda...,"[(1. Uso de los Recursos , 12.0, (49.680000305...",0,[(2. Proceso de Evaluación y Selección de proy...,0
30,Nacional_Financiera_Green_Bond_MXN,"[(3.1. Uso de los Fondos , 11.039999961853027,...",1,[(3.2. Proceso de Evaluación y Selección de Pr...,2
31,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,[(Marco de uso de fondos para las emisiones de...,7,[(3.2. Selección y Evaluación de Proyectos ......,2
32,Green_Bond_Framework,"[(Usos dos Recursos , 12.0, (115.25, 291.32797...",0,"[(Avaliação e Seleção de Ativos , 12.0, (103.2...",0
33,Green_Bonds_Framework_Athon_2020,[(Uso de Recursos ...............................,2,[(Processo de Avaliação e Seleção de Projetos ...,1

In [154]:
UOP_Words_df

,pdfname,energy_system_uop,simsre,simsee,simsppc,simsesml,simstabc,simsct,simsswwm,simscca,simsce,simsgb
0,Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__i...,True,"{'transmission transmission': 1.0, 'power powe...",{},{},{},{},{},{},{},{},{}
1,Bci_Sustainable_Financing_Framework,True,"{'transmission transmission': 1.0, 'power powe...",{'efficiency efficiency': 1.0},{'waste waste': 1.0},{},{},"{'car car': 1.0, 'electric electric': 1.0, 'tr...","{'treatment treatment': 1.0, 'wastewater waste...",{},{},{'buildings buildings': 1.0}
2,BTG_Sustainable_Financing_Framework,True,"{'transmission transmission': 1.0, 'renewable ...",{'efficiency efficiency': 1.0},"{'waste waste': 1.0, 'pollution pollution': 1.0}","{'land land': 1.0, 'agriculture agriculture': ...","{'biodiversity biodiversity': 1.0, 'terrestria...","{'transportation transportation': 1.0, 'vehicl...","{'wastewater wastewater': 1.0, 'water water': ...",{'adaptation adaptation': 1.0},{},"{'buildings buildings': 1.0, 'housing housing'..."
3,CADU_GREEN_BOND_FRAMEWORK,False,{},{'efficiency efficiency': 1.0},{'waste waste': 1.0},{},{},{},{'water water': 1.0},{},{},"{'housing housing': 1.0, 'buildings buildings'..."
4,CIFI_Green_Bond_Framework,True,"{'hydropower hydropower': 1.0, 'power power': ...",{},{'waste waste': 1.0},{},{},{},"{'treatment treatment': 1.0, 'wastewater waste...",{},{},{}
5,EGE_Haina_Green_Securities_Framework,True,"{'transmission transmission': 1.0, 'storage st...",{},{},{'land land': 1.0},{},{'electric electric': 1.0},{'water water': 1.0},{},{},{}
6,FS_Green_Bond_Framework_-_July_2021,True,"{'biomass biomass': 1.0, 'biofuel biofuel': 1....",{},{},"{'land land': 1.0, 'forestry forestry': 1.0, '...",{},{'car car': 1.0},{'water water': 1.0},{},{},{}
7,FS_Green_Bond_Framework_-_November_2020,True,"{'biomass biomass': 1.0, 'biofuel biofuel': 1....",{},{},"{'land land': 1.0, 'agriculture agriculture': ...",{},{'car car': 1.0},{'water water': 1.0},{},{},{}
8,Genneia_Green_Bond_Framework,True,"{'storage storage': 1.0, 'solar solar': 1.0, '...",{},{},{},{},{'battery battery': 1.0},{},{},{},{}
9,ILAP_Green_Financing_Framework,True,"{'transmission transmission': 1.0, 'power powe...",{},{'pollution pollution': 1.0},{},{'biodiversity biodiversity': 1.0},{},{},{},{},{}
10,Marco_de_referencia_de_Bonos_Verdes_Soberanos_...,True,"{'transmission transmission': 1.0, 'power powe...",{'efficiency efficiency': 1.0},"{'pollution pollution': 1.0, 'waste waste': 1.0}","{'agriculture agriculture': 1.0, 'forest fores...","{'biodiversity biodiversity': 1.0, 'conservati...","{'non non': 1.0, 'electric electric': 1.0, 'tr...","{'treatment treatment': 1.0, 'wastewater waste...","{'disaster disaster': 1.0, 'adaptation adaptat...","{'circular circular': 1.0, 'reuse reuse': 1.0}",{'buildings buildings': 1.0}
11,Nacional_Financiera_Green_Bond_USD,True,"{'transmission transmission': 1.0, 'wind wind'...",{},{},{},{},{},{},{},{},{}
12,SONDA_S_A__GREEN_BOND_FRAMEWORK,True,"{'biomass biomass': 1.0, 'solar solar': 1.0, '...",{'efficiency efficiency': 1.0},{'waste waste': 1.0},{},{},{},{},{},{},{'buildings buildings': 1.0}
13,Bono_Azul_-_Framework,False,{},{},{'de de': 0.9079835414886475},{},{},{},{},{},{},{'y y': 0.9070735573768616}
14,Bono_Verde_de_Bancoldex_Framework,True,{'hidroelectricidad hidroeléctricas': 0.815316...,{},"{'de de': 0.9079835414886475, 'contaminación c...",{},{'conservación mitigación': 0.8037376403808594...,"{'transporte transporte': 1.0, 'eléctricos elé...",{},{'adecuación modernización': 0.800734460353851...,{},"{'construcciones construcciones': 1.0, 'y y': ..."
15,Cartilla_Bonos_Verdes,True,"{'cuadrícula iii': 0.8252873420715332, 'almace...",{},{'de de': 0.9079835414886475},{'Arboricultura acuicultura': 0.80385744571685...,{'conservación restauración': 0.84490346908569...,"{'transporte transporte': 1.0, 'eléctricos elé...",{'saneamiento mantenimiento': 0.80645078420639...,"{'adecuación utilización': 0.8224044442176819,...",{},{'construcciones plantaciones': 0.830609500408...
16,Marco_de_referencia_de_bono_verde_Coopeguanaca...,True,"{'cuadrícula (': 0.8166618943214417, 'solar so...",{},"{'de de': 0.9079835414886475, 'contaminación d...",{},{'conservación gasificación': 0.80118459463119...,"{'eléctricos eléctricos': 1.0, 'no no': 0.9680...",{},{'adecuación fiscalización': 0.811488270759582...,{},"{'y y': 0.9070735573768616, 'la la': 0.9470204..."
17,Marco_de_Referencia_del_Bono_Verde_de_la_Ciuda...,True,"{'cuadrícula (': 0.9177074432373047, 'cuadrícu...",{},"{'de de': 0.9079835414886475, 'contaminación c...",{},{'conservación reforestación': 0.8358405828475...,"{'transporte transporte': 1.0, 'no no': 0.9680...",{'saneamiento mantenimiento': 0.8064507842063904},{'adecuación transformación': 0.80157572031021...,{},{'construcciones edificaciones': 0.96057081222...
18,Green_Bonds_Framework_Athon_2020,True,"{'geração geração': 1.0, 'energia energia': 0....",{},{},{},{},{},{},{},{},{}

In [155]:
pred_man_base_rpts

,pdfname,nlp_path,language,similarity_threshold,cleanup_threshold,ES_0_percent,ES_100_percent,ES_partial,number_of_cats
0,Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__i...,UOP_section_true,EN,0.97,0.77,False,True,False,1
1,Bci_Sustainable_Financing_Framework,UOP_section_false,EN,0.97,0.77,False,False,True,6
2,"BTG_Pactual_Green,_Social_and_Sustainable_Fina...",Table,EN,0.97,0.77,False,False,True,4
3,BTG_Sustainable_Financing_Framework,UOP_section_true,EN,0.97,0.77,False,False,True,9
4,CABEI_Green_Bond_Framework,Table,EN,0.97,0.77,False,False,True,2
5,CADU_GREEN_BOND_FRAMEWORK,UOP_section_false,EN,0.97,0.77,True,False,False,4
6,CAFs_GREEN_BOND_FRAMEWORK,Table,EN,0.97,0.77,False,False,True,3
7,CIFI_Green_Bond_Framework,UOP_section_true,EN,0.97,0.77,False,False,True,3
8,EGE_Haina_Green_Securities_Framework,UOP_section_true,EN,0.97,0.77,False,False,True,4
9,FS_Green_Bond_Framework_-_July_2021,UOP_section_false,EN,0.97,0.77,False,False,True,4
10,FS_Green_Bond_Framework_-_November_2020,UOP_section_false,EN,0.97,0.77,False,False,True,4
11,Genneia_Green_Bond_Framework,UOP_section_true,EN,0.97,0.77,False,False,True,2
12,Green_Bond_Financing_Framework,Table,EN,0.97,0.77,True,False,False,2
13,Green_Bond_Framework_of_Banco_Guayaquil,Table,EN,0.97,0.77,False,False,True,2
14,Green_Finance_Framework_Interchile,Table,EN,0.97,0.77,False,False,True,2
15,Green_social_bond_framework_series_ad_ae_2019,Table,EN,0.97,0.77,True,False,False,2
16,ILAP_Green_Financing_Framework,UOP_section_false,EN,0.97,0.77,False,False,True,3
17,ISA_CTM_FRAMEWORK,Table,EN,0.97,0.77,False,False,True,2
18,Marco_de_referencia_de_Bonos_Verdes_Soberanos_...,UOP_section_true,EN,0.97,0.77,False,False,True,10
19,Nacional_Financiera_Green_Bond_USD,UOP_section_true,EN,0.97,0.77,False,True,False,1
20,Sicredi_Green_Bond_Framework,Table,EN,0.97,0.77,False,False,True,2
21,SONDA_S_A__GREEN_BOND_FRAMEWORK,UOP_section_true,EN,0.97,0.77,False,False,True,4
22,Chile_Sustainable_Bond_Framework,Table,EN,0.97,0.77,False,False,True,5
23,Genneia_Green_Financing_Framework,Table,EN,0.97,0.77,False,True,False,1
24,Bono_Azul_-_Framework,UOP_section_true,ES,0.80,0.65,True,False,False,2
25,Bono_Verde_de_Bancoldex_Framework,UOP_section_true,ES,0.80,0.65,False,False,True,6
26,Cartilla_Bonos_Verdes,UOP_section_true,ES,0.80,0.65,False,False,True,8
27,Marco_de_Gestión_de_Bono_Verde,Table,ES,0.80,0.65,False,True,False,1
28,Marco_de_referencia_de_bono_verde_Coopeguanaca...,UOP_section_true,ES,0.80,0.65,False,False,True,6
29,Marco_de_Referencia_del_Bono_Verde_de_la_Ciuda...,UOP_section_false,ES,0.80,0.65,False,False,True,7
30,Nacional_Financiera_Green_Bond_MXN,Table,ES,0.80,0.65,False,False,True,2
31,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,Table,ES,0.80,0.65,True,False,False,1
32,Green_Bond_Framework,Table,PT,0.88,0.70,False,True,False,1
33,Green_Bonds_Framework_Athon_2020,UOP_section_true,PT,0.88,0.70,False,True,False,1

In [156]:
# write dataframes to csvfiles with versions in the filenames

dataframes = [results_df, table_df, UOP_df, UOP_Words_df, pred_man_base_rpts]
dfname_list = ['results_df', 'table_df', 'UOP_df', 'UOP_Words_df', 'pred_train_rpts']
csvname_list = ['results_csv', 'table_csv', 'UOP_csv', 'UOP_Words_csv', 'pred_train_rpts_csv']
filepath = '/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames_2ndPass/'
extention = '.csv'
version = 'V9'


results_csv = results_df.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames_2ndPass/results_csv_V9.csv')
table_csv = table_df.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames_2ndPass/table_csv_V9.csv')
UOP_csv = UOP_df.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames_2ndPass/UOP_csv_V9.csv')
UOP_Words_csv = UOP_Words_df.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames_2ndPass/UOP_Words_csv_V9.csv')
pred_V9_rpts_csv = pred_man_base_rpts.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames_2ndPass/pred_train_rpts_V9.csv')

## diagnostic area

In [162]:
# run the pdf to be checked through the table functions of the pipeline


# input parameters
filepath = '/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/PDFs/' # refinement runs
filepath_mb = '/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/eval_FW_rpts/'
extention = '.pdf'
language = 'ES'
tableStrategy = 'lines_strict'

if language == 'EN':
    pdf_list_name = pdf_man_base_en_test
elif language == 'ES':
    pdf_list_name = pdf_es_lines
elif language == 'PT':
    pdf_list_name = pdf_man_base_pt

#similarity_th = 0.97
#cleanup_th = 0.77

# set thresholds - possible to set by language if required
sim_th_en = 0.97
sim_th_es = 0.8
sim_th_pt = 0.88
cleanup_TH_en = 0.77
cleanup_TH_es = 0.65
cleanup_TH_pt = 0.70

for pdf in pdf_list_name:
    document = filepath + pdf + extention

    # call the functions in sequence
    filename, pdfname, tableCount, tablePages, tableHeaders, tableDFs = catTable(document, tableStrategy)
    uniqueCatsNoDupes, table_idx = tableAssess(language, tableCount, tablePages, tableHeaders, tableDFs)
    CatwordsFFinal, CatwordsFinal, dfsimScores_cln, simScores_cln, dfresimScores, resimScores, energy_system_tbl, = tableClean(language, uniqueCatsNoDupes, sim_th_en, sim_th_pt, sim_th_es, cleanup_TH_en, cleanup_TH_pt, cleanup_TH_es) 

    print('categories from tables')
    table_df.loc[len(table_df)] = [pdfname, tablePages, tableHeaders, len(CatwordsFFinal), CatwordsFFinal, energy_system_tbl, uniqueCatsNoDupes, simScores_cln, resimScores]
    
    ttlresimScores |= resimScores
    ttlsimScores_cln |= simScores_cln

categories from tables

In [163]:
table_df

,pdfname,tablePages_list,table.Headers_list,countCat_words,unique compliant Categories_list,energy_system_tbl,unique Cats all,simScores_cln,resimScores
0,"BTG_Pactual_Green,_Social_and_Sustainable_Fina...","[15, 16, 17, 19]","[[Green\nProject\nCategory, Use of\nProceeds, ...",4,"[green buildings, afof rdable housing, renewab...",True,"[afof rdable basic infrastructure, renewable e...",{'renewable energy renewable': 0.9201155304908...,{'renewable': 1.0}
1,CABEI_Green_Bond_Framework,"[7, 8, 9, 10, 12]","[[Eligible\nGreen\nProjects\nCategories, Sub-c...",2,"[renewable energy, water management]",True,"[clean transport, renewable energy, water mana...",{'renewable energy renewable': 0.9201155304908...,{'renewable': 1.0}
2,CAFs_GREEN_BOND_FRAMEWORK,"[1, 2, 8, 9]","[[Measure of Units, Col1], [Graphics, Content]...",3,"[waste management, renewable energy, clean tra...",True,[sustainable management of living natural reso...,"{'waste management waste': 0.8286465406417847,...",{'renewable': 1.0}
3,Green_Bond_Financing_Framework,"[7, 8, 10]",[[Eligible Category aligned\nwith ICMA Green B...,2,"[energy efficiency, clean transportation]",False,"[energy efficiency, clean transportation]",{'energy efficiency efficiency': 0.90048879384...,{}
4,Green_Bond_Framework_of_Banco_Guayaquil,"[6, 7, 8, 9, 10, 18, 19, 29, 30, 31, 38, 39]","[[GBP Eligible\nGreen Assets\nCategory, Banco ...",2,"[energy efficiency, renewable energy]",True,"[energy efficiency, renewable energy]",{'energy efficiency efficiency': 0.90048879384...,{'renewable': 1.0}
5,Green_Finance_Framework_Interchile,[8],"[[Eligible Project Category, Questions, Alignm...",2,"[energy efficiency, renewable energy]",True,"[renewable energy, energy efficiency, climate ...",{'renewable energy renewable': 0.9201155304908...,{'renewable': 1.0}
6,Green_social_bond_framework_series_ad_ae_2019,"[3, 6, 7]","[[Category, Project name, Goal], [Categories o...",2,"[potable water supply, sanitation]",False,"[resilient infrastructure, potable water suppl...",{'potable water supply water': 0.8469440937042...,{}
7,ISA_CTM_FRAMEWORK,"[4, 5, 7, 8, 9, 15, 16, 17, 18]","[[Eligible Project Category, Questions, Alignm...",2,"[energy efficiency, renewable energy]",True,"[energy efficiency, renewable energy]",{'energy efficiency efficiency': 0.90048879384...,{'renewable': 1.0}
8,Sicredi_Green_Bond_Framework,"[4, 6]","[[Eligible\nCategories, Description, Objective...",2,"[energy efficiency, renewable energy]",True,"[energy efficiency, renewable energy]",{'energy efficiency efficiency': 0.90048879384...,{'renewable': 1.0}
9,Chile_Sustainable_Bond_Framework,"[0, 19, 20, 21, 22, 23, 24, 25, 26, 30, 37, 38...","[[Col0, Ministry of\nFinance\nGovernment of Ch...",5,"[food security, green buildings (ecological bu...",True,"[food security, green buildings (ecological bu...","{'food security food': 0.7798810005187988, 'gr...",{'renewable': 1.0}
10,Genneia_Green_Financing_Framework,"[5, 7]","[[Col0, 20161, 20202, 20251, 20301], [Eligible...",1,[renewable energy],True,[renewable energy],{'renewable energy renewable': 0.9201155304908...,{'renewable': 1.0}
11,Marco_de_Gestión_de_Bono_Verde,"[5, 8, 9]","[[Norma de\nDesempeño, Estatus1, Descripción],...",1,[proyecto de energías renovables (energía hidr...,True,[proyecto de energías renovables (energía hidr...,{'proyecto de energías renovables (energía hid...,"{'cuadrícula (sólo)': 0.9524129033088684, 'bio..."
12,Nacional_Financiera_Green_Bond_MXN,"[3, 9, 10, 11, 17]","[[Categoría, Actividades elegibles], [Col0, Pr...",2,"[centrales eólicas (solo terrestres), pequeñas...",True,"[centrales eólicas (solo terrestres), pequeñas...",{'centrales eólicas (solo terrestres) cuadrícu...,"{'cuadrícula (sólo)': 0.9524129033088684, 'hid..."
13,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,"[3, 4, 8, 16, 18, 19, 20, 21, 22, 23, 24, 25, ...",[[Contribuciones Nacionales Determinadas (NDCs...,1,[energías renovables],False,"[eficiencia energética49 50, verdes, energías ...",{'energías renovables renovable': 0.7062243223...,{}
14,Green_Bond_Framework,"[10, 14, 19, 21, 22]","[[Categoria, Descrição], [Projeto, Capaci\nda ...",1,[energia renovável],True,"[transmissão de energia, energia renovável]",{'energia renovável energia': 0.91402691602706...,"{'energia': 1.0, 'energia hidráulica': 0.90849..."
15,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,"[3, 4, 8, 16, 18, 19, 20, 21, 22, 23, 24, 25, ...",[[Contribuciones Nacionales Determinadas (NDCs...,1,[energías renovables],False,"[eficiencia energética49 50, verdes, energías ...",{'energías renovables renovable': 0.7062243223...,{}
16,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,"[4, 16, 38, 52, 53, 54, 55, 56, 57, 58, 59]","[[Acrónimos\nAbreviatura, Descripción], [1) Us...",0,[],,[],{},{}

In [158]:
marco_de_uso_headers = table_df.iloc[13].loc['table.Headers_list']
print(marco_de_uso_headers)
marco_de_uso = table_df.iloc[13].loc['unique Cats all']
print(marco_de_uso)
marco_de_uso_sim_dict_65 = table_df.iloc[13].loc['simScores_cln']
print(marco_de_uso_sim_dict_65)

[['Contribuciones Nacionales Determinadas (NDCs, por sus siglas en inglés).', 'Col1'], ['Acrónimos\nAbreviatura', 'Descripción'], ['Objetivo Estratégico', 'Col1', 'Lineamientos estratégicos propuestos', 'Col3'], ['Col0', 'Componente', 'Col2', 'Col3', 'Descripción', 'Col5'], ['Col0', 'Col1', 'Tabla 5 Uso de los Fondos para financiar Proyectos verdes.'], ['Energías\nrenovables', 'Promover el desarrollo de Energía solar11 Mitigación del cambio\ntecnologías de energías Instalación de parque climático.\nrenovables. solares fotovoltaicos: Provisión de\nLos proyectos verdes elegibles -Paneles Solares infraestructura de bajo\nincluyen: carbono a largo plazo.\n-Inversores\n1.- Proyectos de generación de -Baterías Reducción de gases de\nenergía 23 (eléctrica y térmica) efecto invernadero.\n-Instalaciones\nmediante fuentes de energía\nrenovable, conectados a la red o -Transformadores\nen sistemas aislados, tales -Sistema de control y\ncomo: automatización\na) Energía eólica4, Infraestructura de\nTransmisión totalmente\nb) Energía solar 5, dedicada para\nd) Energía a partir de biomasa 6 instalaciones de\n7 8, generación de\nelectricidad solar 12.\ne) Generación de biogás 6 7 8,\nEnergía solar Térmica13\nf) Cogeneración a partir de Instalaciones de\nresiduos agrícolas y forestales 6 calefones solares\n7 8.\nEnergía eólica\n2.- Proyectos de reconversión Instalación de\ndel uso de energía hacia generación de parques\nenergías renovables 6 7 8. eólicos terrestres:\n3.- Proyectos de producción de - Aerogeneradores\nhidrógeno verde sujeto al marco - Sistema de Instalación\nregulatorio del país 9 10.\n- Sistema de Control\n4.- Proyectos de producción de - Sistema de\nbiocombustibles sujeto al marco almacenamiento.\nregulatorio del país.\nInfraestructura de\n5. Producción de hidrógeno transmisión y soporte\nverde, sujeto al marco especializada.\nregulatorio del país.\nGeneración de energía\na partir de biomasa\nInstalaciones de\nproducción de biomasa\npara la producción de'], ['Col0', 'electricidad.\nGeneración de Biogás\nInstalación de\nManufactura dedicada\nal desarrollo de\nbioenergía.\nReconversión del uso\nde energía hacia\nenergías renovables.\n-Construcción de la\nplanta\n-Sistemas de control y\nAutomatización\n-Líneas de transmisión\nProducción de\nbiocombustible sujeto\nal marco regulatorio del\npaís\n-Construcción y\nejecución de la planta\n-Sistema de control y\nautomatización\nProducción de\nhidrógeno verde\n-Instalación de la\nplanta.\n-Sistema de control y\nautomatización'], ['Col0', 'LED. tecnología VRF y\n3.- Proyectos de Inverter\nimplementación de procesos -Línea Blanca con\nproductivos eficientes, tales Certificación A (Norma\ncomo: líneas de producción, Brasileña y Chile)\nmaquinaria, etc.\n-Maquinaria Textil\n4.- Proyectos en sistemas de\neficiente, incluyendo:\nautomatización y gestión que\nBordadoras y tejedoras\nofrezcan sistemas de energía\ncon motor SERVO\nmás eficientes.\n(>700 rpm)\n5.- Implementación de\ntecnologías eficientes -Sistema de\nenergéticamente, que Iluminación LED\nrepresenten un ahorro de al Maquinaria o equipos\nmenos el 20%. Tanto para la utilizados en sectores\nrenovación de maquinaria productivos que\nantigua como para la ampliación cumplan con un ahorro\nde maquinaria nueva. de energía > 20%.\nHorno tipo túnel y\nHoffman 16'], ['Col0', 'funcionamiento, utilizadas\ndentro o como servicio\ncomplementario de la actividad\nproductiva.\n6.- Proyectos de Energías\nRenovables para el Transporte:\nDesarrollo de estaciones de\ncarga alimentadas por energía\nsolar o eólica. Integración de\nfuentes de energía renovable\npara alimentar sistemas de\ntransporte público17.'], ['Col0', 'del suelo. -Dispositivos de\n2.- Proyectos para la reducción Selección\nde las emisiones de metano y Acuicultura Sostenible\nóxido nitroso provenientes del -Sistemas de\nganado y fertilizantes, Recirculación de Agua\nrespectivamente.\n-Alimentación\n3.- Proyectos que minimicen los Sostenible\nimpactos ambientales en las\n-Certificación de Pesca\ncadenas de valor agrícolas.\ny Acuicultura\nC.- Silvicultura:\nSostenible\n1.- Proyectos de gestión\nsostenible de bosques: esto\nincluye (aunque no limitado) a)\nforestación, b) reforestación, c)\nrehabilitación de bosques.\nD.- Pesca y acuicultura:\n1.- Proyectos de pesca\nsostenible.\n2.- Proyectos de acuicultura\nsostenible.\n3.- Proyectos que minimicen los\nimpactos ambientales en las\ncadenas de valor alimentarias.'], ['Col0', 'hasta una gestión activa e\npueden incluir la protección\ncontra el riesgo de\ndeforestación, reservas\nvoluntarias y obligatorias, y\nesfuerzos activos de\nconservación.\n4.- Restauración y rehabilitación\nforestal: actividades forestales\nno comerciales diseñadas para\naumentar el área o mejorar la\ncalidad del hábitat forestal\nexistente, o establecer nuevos\nrodales forestales. Las\nactividades van desde\nintervenciones mínimas hasta\nrestauración activa, que incluye\nfacilitar la regeneración y\nrestauración mediante medios\nnaturales o artificiales. 1'], ['Col0', 'y disposición de los desechos y\nresiduos sólidos (incluidos los\nde la digestión anaeróbica) 19.\n2.- Proyectos de control de\ncontaminación, incluyendo la\nseparación, recolección y\ntratamiento de efluentes\nlíquidos.\nD.- Producción más Limpia\n1. Tecnologías que hacen el uso\neficiente de un recurso en\nespecífico.\n2. Prácticas/ uso de insumos\nque desplacen el uso de\nproductos contaminantes o\naltamente peligrosos.\n3. Recuperación/reutilización de\ninsumos y materiales.\n4. Modificación de procesos,\nesto incluye (aunque no\nlimitado): a) mejoras en los\ncontroles de procesos, b)\nrediseño de las operaciones, c)\nactualizaciones en los equipos,\ny d) la incorporación de\ntecnologías avanzadas que\nconduzcan a una menor\ngeneración de residuos.'], ['Col0', 'productos y equipos que textiles\nincentiven la economía circular, - Maquinaria para el\nincrementando su funcionalidad, reciclaje tales como:\ndurabilidad, modularidad y fácil\n\uf0b7 Peletizadoras\nreparación.\n, agflutinadora\n3.- Proyectos que sustituyan la\n\uf0b7 Prensas\nutilización de materiales\nhidráulicas\nvírgenes con materiales\nsecundarios y subproductos. -Procesos productivos\nmin de empresas que\nutilicen plástico, papel,\nB.- Uso circular:\nmetal y otro tipo de\n1.- Proyectos de fabricación de\nmaterial reciclado.\nnuevos productos o equipos a\n-Sistemas de\ntravés de productos o equipos\ncompostaje de residuos\nredundantes que han sido\norgánicos.\nreconvertidos, refaccionados o\nremanufacturados.\nC.- Recuperación del valor\ncircular:\n1.- Proyectos de desarrollo,\naprovechamiento y producción\nsostenible de nuevos materiales\n(materia prima secundaria) a\npartir de materiales secundarios,\nsubproductos y/o desechos.\n2.- Proyectos de recuperación,\nrecirculación y valorización de\ndesechos biodegradables y/o\nsubproductos para la fabricación\nde comida, nutrientes, fibras,\nfertilizantes, cosméticos y\nmedicamentos.\nD.- Soporte circular:\n1.- Proyectos que den soporte a\nla circularidad a través de\nherramientas y servicios\n(infraestructura digital / software)\nque permitan elaborar\nestrategias y modelos de\nnegocio para la reutilización y/o\ncolaboración conjunta.\n2.- Proyectos de fabricación de\nproductos ecoeficientes.'], ['Col0', 'eviten los daños relacionados -Bioestimulantes\ncon el cambio en la temperatura (Nombres comerciales\nambiente. referenciales: Bioles,\nB.- Relacionado con viento: Bombardier, Basfoliar,\nVigortop, Prophos,\n1.- Proyectos que reduzcan o\nProMicro, entre otros)\neviten los daños relacionados\ncon el cambio en la intensidad -Plantación de cultivos\nde los vientos y tormentas. tolerantes a la sequía\ncuyas raíces pueden\nC.- Relacionado con agua:\nretener agua en el\n1.- Proyectos que reduzcan o suelo.\neviten los daños relacionados\n-Uso de sensores de\ncon el cambio en la intensidad\nhumedad y\nde las lluvias.\ntemperatura.\n2.- Proyectos que incrementen\n-Mallas antihelada y\nla disponibilidad de agua y uso\nantigranizo\nmás eficiente.\n-Estufas con paneles\nD.- Relacionado con suelo:\nsolares (Avícolas)\n1.- Proyectos que reduzcan o\n-Uso de cubiertas\neviten los daños relacionados\nprotectoras o refugios\ncon el cambio en la integridad de\ntérmicos\nlos suelos (deslizamientos,\nhundimientos, etc.).\n2.- Proyectos que incrementen\nla productividad agrícola.\n\uf0b7'], ['Col0', 'a servicios de salud por parte de la Mejora de la seguridad y\npoblación. resiliencia financiera de la\n5.- Proyectos que introduzcan registros población.\nmédicos electrónicos y órdenes médicas Expansión del acceso de\na través de sistemas digitales. sistemas financieros a las\n6.- Proyectos de innovación médica y familias de bajos recursos.\nfarmacéutica. Mejora en el PIB.\n7.- Proyectos que mejoren la atención\nmaterno-infantil.\nB.- Relacionado a la educación:\n1.- Proyectos que incrementen la tasa de\ninscripción en colegios y/o reduzcan la\ntasa de abandono.\n2.- Proyectos que incrementen la\nparticipación de mujeres en los colegios\ny en las universidades.\n3.- Proyectos que incrementen la\nparticipación de estudiantes con\nnecesidades especiales de educación en\nclases regulares.\n4.- Proyectos que promuevan la\nparticipación de educadores,\nespecialmente en las profesiones de\nmayor demanda.\nC.- Relacionado a servicios financieros:\n1.- Proyectos que incrementen los\ningresos, ahorros y coberturas de\nseguros.\n2.- Proyectos que incrementen la\n“alfabetización” financiera.\n3.- Proyectos que incrementen el acceso\na los mercados financieros.\n4.- Proyectos que refuercen la inclusión\nfinanciera.'], ['Col0', 'acceso a la tecnología. políticos.\nLos proyectos sociales elegibles Mejora en las oportunidades\nincluyen: de las mujeres o disminución\nA.- Relacionado al empoderamiento de en la discriminación de\nla mujer: género.\n1.- Proyectos que incrementen el acceso Mejora en las dotaciones de\na la información por parte de las mujeres las mujeres o acceso a\no reduzcan las asimetrías de la recursos, habilidades y\ninformación manejada por género. conocimiento.\n2.- Proyectos que incrementen la Decremento en la\nseguridad de las mujeres. desigualdad de salarios en\nfunción del género.\n3.- Proyectos que mejoren la equidad de\ngénero en posiciones directivas. Decremento en la violencia de\ngénero.\n4.- Proyectos que incrementen la\nparticipación de mujeres en los Incremento de la seguridad\nhumana o decremento del\nestablecimientos laborales.\nriesgo de conflicto.\n5.- Proyectos que mejoren la calidad de\nvida de las mujeres y reduzcan el riego Decremento del número de\nde lesiones o condiciones crónicas de trabajadores expuestos a\nsalud de las mujeres en los inseguridad laboral o social.\nestablecimientos laborales. Refuerzo de la resiliencia al\n6.- Proyectos que reduzcan las tasas de cambio climático.\naccidentes, tasas de mortalidad y tasas Mejora de la justicia climática\nde enfermedades ocupacionales de las para la población vulnerable\nmujeres. económicamente y en riesgo\n7.- Proyectos que incrementen los de los desastres climáticos.\ningresos salariales de las mujeres. Mejora en el PIB.\n8.- Proyectos que incrementen la tasa de Mejora en la calidad de vida.\nretención del personal laboral femenino. Mejora en la productividad.\nB.- Relacionado con la inclusión social\npara los más desaventajados:\n1.- Proyectos que reduzcan la tasa de\npobreza.\n2.- Proyectos que reduzcan la tasa de\ndesempleo juvenil.\n3.- Proyectos que incrementen la razón\nde ingresos.\n4.- Proyectos que reduzcan el trabajo\ninfantil.\nC.- Relacionado con el acceso a la\ntecnología:\n1.- Proyectos que incrementen el acceso\na redes móviles por parte de la\npoblación.\n2.- Proyectos que incrementen el acceso\na información o recursos a través de\nproductos o servicios tecnológicos o\ndigitales.\n3.- Proyectos que incrementen el acceso\na los mercados financieros a través de\nplataformas digitales.\n4.- Proyectos que mejoren el acceso al\naprendizaje remoto.'], ['Col0', 'Col1', 'Col2', 'Col3'], ['Col0', 'Col1', 'Tabla 9 Métricas de impacto. Proyectos verdes.'], ['Col0', 'orgánicos volátiles distintos al metano\n(NMVOCs).'], ['Col0', 'escapes en los criaderos de peces, en\nporcentaje de operaciones cubiertas con\nmejoras de nuevo diseño que mitiguen el\nriesgo de escape.'], ['Col0', 'de desechos no reciclables para mejorar estos.\nla eficiencia de las instalaciones, en 4.- Número de personas\nMWh/GWh (para electricidad) y GJ/TJ beneficiadas por la\n(para otro tipo de energía). recolección selectiva de\n2.- Energía recuperada de los desechos reciclables.\n(menos cualquier combustible de 5.- Porcentaje de reducción de\nsoporte) en MWh, GWh o KJ de la contaminantes locales.\nenergía neta generada por año.\n6.- Toneladas de residuos\n3.- Emisiones anuales de GEI reducidas reducidos.\no evitadas, en toneladas de CO2\nequivalente.\nC.- Desechos recolectados y tratados, o\ndispuestos:\n1.- Cantidad de desechos separados y\nrecolectados, tratados o dispuestos en\ntoneladas por año y en porcentaje de los\ndesechos totales.'], ['Col0', '2.- Cantidad absoluta anual de materiales\nsecundarios, productos y desechos\nrecuperados en toneladas.\n3.- Cantidad absoluta anual de desechos\nbiodegradables, digestibles y compost\nrecuperados en toneladas.\n4.- Cantidad de comida, productos\nnutrientes, fibras o fertilizantes\nproducidos de desechos biodegradables\nen toneladas por año.\nD.- Soporte circular:\n1.- Porcentaje anual de incremento de\ningresos derivados de herramientas y\nservicios que permiten una economía\ncircular.\n2.- Incremento del número de productos\nreconocidos internacionalmente con\netiquetado eco u otros certificados\nmedioambientales.'], ['i', 'debidos a deslizamientos de tierra.\n2.- Reducción del número de días\noperativos perdidos por la ruptura de\nredes de transporte u otras\nnfraestructuras.\n3.- Reducción de los cambios de\nnutrientes y niveles de pH de suelos\nagrícolas.\n4.- Aumento del uso de tierras agrícolas\ncon cultivos más resistentes a las\nsequías en hectáreas.\n5.- Aumento de áreas cultivadas con\nagricultura de precisión en kilómetros\ncuadrados.'], ['Col0', 'áreas de bajos recursos.\n2.- Número de personas provistas con\nacceso a servicios financieros.\n3.- Número de personas con bajos\nrecursos provistos con acceso a\nmicrocréditos.\n4.- Número de personas con bajos\nrecursos provistos con acceso a micro\nseguros.'], ['Col0', 'medianas empresas con soporte para\nmodernizar sus equipos e instalaciones.\n2.- Número de préstamos para personas\ncon bajos recursos para mejorar las\ntecnologías de sus instalaciones.\n3.- Número de primeras conexiones de\ninternet.\n4.- Número de beneficiarios de productos\ntecnológicos (portátiles o tabletas) para\npermitir el aprendizaje remoto.'], ['Col0', 'Sector', 'ODS', 'Meta', 'Col4'], ['Col0', 'Gestión sostenible de\nrecursos naturales y\nuso de la tierra', '2', '2.4', 'Para 2030, asegurar la sostenibilidad de los sistemas de producción de\nalimentos y aplicar prácticas agrícolas resilientes que aumenten la\nproductividad y la producción, contribuyan al mantenimiento de los\necosistemas, fortalezcan la capacidad de adaptación al cambio climático, los\nfenómenos meteorológicos extremos, las sequías, las inundaciones y otros\ndesastres, y mejoren progresivamente la calidad del suelo y la tierra'], ['Col0', 'Col1', 'Col2', '6.5', 'De aquí a 2030, implementar la gestión integrada de los recursos hídricos a\ntodos los niveles, incluso mediante la cooperación transfronteriza, según\nproceda'], ['Col0', 'Col1', 'Col2', '15b', 'Movilizar un volumen apreciable de recursos procedentes de todas las\nfuentes y a todos los niveles para financiar la gestión forestal sostenible y\nproporcionar incentivos adecuados a los países en desarrollo para que\npromuevan dicha gestión, en particular con miras a la conservación y la\nreforestación'], ['Col0', 'Col1', 'Col2', '1.4', 'Para 2030, garantizar que todos los hombres y mujeres, en particular los\npobres y los más vulnerables, tengan los mismos derechos a los recursos\neconómicos, así como acceso a los servicios básicos, la propiedad y el\ncontrol de las tierras y otros bienes, la herencia, los recursos naturales, las\nnuevas tecnologías y los servicios económicos, incluida la micro financiación'], ['Col0', 'Col1', 'Col2', '4.1', 'De aquí a 2030, asegurar que todas las niñas y todos los niños terminen la\nenseñanza primaria y secundaria, que ha de ser gratuita, equitativa y de\ncalidad y producir resultados de aprendizaje pertinentes y efectivos'], ['Col0', 'Col1', 'Col2', '10.2', 'De aquí a 2030, potenciar y promover la inclusión social, económica y política\nde todas las personas, independientemente de su edad, sexo, discapacidad,\nraza, etnia, origen, religión o situación económica u otra condición'], ['Col0', 'Col1', '2\n4', '2.5', 'Para 2030, mantener la diversidad genética de las semillas, las plantas\ncultivadas y los animales de granja y domesticados y sus especies silvestres\nconexas, entre otras cosas mediante una buena gestión y diversificación de\nlos bancos de semillas y plantas a nivel nacional, regional e internacional, y\npromover el acceso a los beneficios que se deriven de la utilización de los\nrecursos genéticos y los conocimientos tradicionales y su distribución justa y\nequitativa, como se ha convenido internacionalmente'], ['Sector', 'Col1', 'Col2', 'Monto\ndesembolsado', 'Col4', 'Impacto (Toneladas', 'Col6', 'Col7', 'Ahorro anual de', 'Col9', 'Ahorro anual de\nagua (m3/año)'], ['Categorías', 'Col1', 'Ejemplos de Beneficios Contribuciones a\nCriterios de Elegibilidad\nproyectos 36 Medioambientales los ODS'], ['Col0', '- Sistema de\n4.- Proyectos de producción de\nbiocombustibles sujeto al marco almacenamiento.\nregulatorio del país. Infraestructura de\n5. Producción de hidrógeno transmisión y soporte\nverde, sujeto al marco especializada.\nregulatorio del país. Generación de energía\na partir de biomasa\nInstalaciones de\nproducción de biomasa\npara la producción de\nelectricidad.\nGeneración de Biogás\nInstalación de\nManufactura dedicada\nal desarrollo de\nbioenergía.\nReconversión del uso\nde energía hacia\nenergías renovables.\n-Construcción de la\nplanta\n-Sistemas de control y\nAutomatización\n-Líneas de transmisión\nProducción de\nbiocombustible sujeto\nal marco regulatorio del\npaís\n-Construcción y\nejecución de la planta\n-Sistema de control y\nautomatización\nProducción de\nhidrógeno verde\n-Instalación de la\nplanta.\n-Sistema de control y\nautomatización'], ['Col0', 'aislamiento térmico, c) -Aislamiento Térmico\nactualizaciones del sistema de -Instalación de\naire acondicionado, d) Sensores de Presencia\nalmacenamiento de energía, e)\n-Remplazo del\nredes inteligentes.\nquemador de las\n2.- Proyectos en recambio de\ncalderas\nequipos y luminarias eficientes,\ntales como: instalación, -Equipos para\nactualización y mantenimiento climatización (Aires\nde proyectos de iluminación Acondicionados –\nLED. Calefacción) con\n3.- Proyectos de tecnología VRF y\nimplementación de procesos Inverter\nproductivos eficientes, tales -Línea Blanca con\ncomo: líneas de producción, Certificación A (Norma\nmaquinaria, etc. Brasileña y Chile)\n4.- Proyectos en sistemas de\n-Maquinaria Textil\nautomatización y gestión que\neficiente, incluyendo:\nofrezcan sistemas de energía\nBordadoras y tejedoras\nmás eficientes.\ncon motor SERVO\n5.- Implementación de\n(>700 rpm)\ntecnologías eficientes\nenergéticamente, que -Sistema de\nrepresenten un ahorro de al Iluminación LED\nmenos el 20%. Tanto para la Maquinaria o equipos\nrenovación de maquinaria utilizados en sectores\nantigua como para la ampliación productivos que\nde maquinaria nueva. cumplan con un ahorro\nde energía > 20%.\nHorno tipo túnel y\nHoffman 51'], ['Prevención y\ncontrol de la\ncontaminación', 'Promover la prevención, control -Reducción del Mitigación del cambio\nde la contaminación y consumo de agua climático.\nProducción Más Limpia, -Recuperación, 

In [ ]:
UOP_Words_df

In [ ]:
re = UOP_Words_df.iloc[5].loc['simsppc']
re

## running sims dicts and medians for refinement / optimisation

In [723]:
import statistics
import numpy as np

In [834]:

cleanup_th_med = np.percentile(list(ttlsimScores_cln.values()), 50)
cleanup_th_25 = np.percentile(list(ttlsimScores_cln.values()), 25)
re_tbl_th_med = np.percentile(list(ttlresimScores.values()), 50)
re_tbl_th_25 = np.percentile(list(ttlresimScores.values()),25)
re_uop_th_med = np.percentile(list(ttlsimsre.values()), 50)
re_uop_th_25 = np.percentile(list(ttlsimsre.values()),25)
ee_uop_th_med = np.percentile(list(ttlsimsee.values()), 50)
ee_uop_th_25 = np.percentile(list(ttlsimsee.values()), 25)
cca_uop_th_med = np.percentile(list(ttlsimscca.values()), 50)
cca_uop_th_25 = np.percentile(list(ttlsimscca.values()), 25)
ppc_uop_th_med = np.percentile(list(ttlsimsppc.values()), 50)
ppc_uop_th_25 = np.percentile(list(ttlsimsppc.values()), 25)
tabc_uop_th_med = np.percentile(list(ttlsimstabc.values()), 50)
tabc_uop_th_25 = np.percentile(list(ttlsimstabc.values()), 25)
esml_uop_th_med = np.percentile(list(ttlsimsesml.values()), 50)
esml_uop_th_25 = np.percentile(list(ttlsimsesml.values()), 25)
ct_uop_th_med = np.percentile(list(ttlsimsct.values()), 50)
ct_uop_th_25 = np.percentile(list(ttlsimsct.values()), 25)
ce_uop_th_med = np.percentile(list(ttlsimsce. values()), 50)
ce_uop_th_25 = np.percentile(list(ttlsimsce. values()), 25)
swwm_uop_th_med = np.percentile(list(ttlsimsswwm.values()), 50)
swwm_uop_th_25 = np.percentile(list(ttlsimsswwm.values()), 25)
gb_uop_th_med = np.percentile(list(ttlsimsgb.values()), 50)
gb_uop_th_25 = np.percentile(list(ttlsimsgb.values()), 25)

In [ ]:
MB_th_list = ['cleanup', len(ttlsimScores_cln), cleanup_th_med, cleanup_th_25, 're_tbl', len(ttlresimScores), 
              re_tbl_th_med, re_tbl_th_25, 're_uop', len(ttlsimsre), re_uop_th_med, re_uop_th_25, 'ee_uop', 
              len(ttlsimsee), ee_uop_th_med, ee_uop_th_25, 'cca_uop', len(ttlsimscca), cca_uop_th_med, cca_uop_th_25, 
              'ppc_uop', len(ttlsimsppc), ppc_uop_th_med, ppc_uop_th_25, 'tabc_uop', len(ttlsimstabc), tabc_uop_th_med, 
              tabc_uop_th_25,'esml_uop', len(ttlsimsesml), esml_uop_th_med, esml_uop_th_25, 'ct_uop', len(ttlsimsct), 
              ct_uop_th_med, ct_uop_th_25, 'ce_uop', len(ttlsimsce), ce_uop_th_med, ce_uop_th_25, 'swwm_uop', 
              len(ttlsimsswwm), swwm_uop_th_med, swwm_uop_th_25, 'gb_uop', len(ttlsimsgb), gb_uop_th_med, gb_uop_th_25]

MB_th_list

['cleanup',
 24,
 np.float64(0.8143185973167419),
 np.float64(0.7206014096736908),
 're_tbl',
 7,
 np.float64(0.9084943532943726),
 np.float64(0.8335189819335938),
 're_uop',
 36,
 np.float64(0.9736778736114502),
 np.float64(0.8254124224185944),
 'ee_uop',
 1,
 np.float64(1.0),
 np.float64(1.0),
 'cca_uop',
 22,
 np.float64(0.8256032466888428),
 np.float64(0.8093428611755371),
 'ppc_uop',
 7,
 np.float64(0.9332984685897827),
 np.float64(0.8823587000370026),
 'tabc_uop',
 0,
 np.float64(0.8325821757316589),
 np.float64(0.8076858669519424),
 'esml_uop',
 7,
 np.float64(1.0),
 np.float64(0.901928722858429),
 'ct_uop',
 11,
 np.float64(1.0),
 np.float64(1.0),
 'ce_uop',
 2,
 np.float64(1.0),
 np.float64(1.0),
 'swwm_uop',
 8,
 np.float64(1.0),
 np.float64(0.9619378596544266),
 'gb_uop',
 9,
 np.float64(0.947020411491394),
 np.float64(0.8306095004081726)]

In [ ]:
columns = ['ttlsimScores_cln', 'ttlresimScores', 'ttlsimsre', 'ttlsimsee', 'ttlsimsppc', 'ttlsimsesml', 'ttlsimstabc', 'ttlsimsct', 'ttlsimscca', 'ttlsimsce', 'ttlsimsswwm', 'ttlsimsgb', 'MB_th_list']
sims_dicts_MB = pd.DataFrame(columns=columns)
sims_dicts_MB.loc[len(sims_dicts_MB)] = [ttlsimScores_cln, ttlresimScores, ttlsimsre, ttlsimsee, ttlsimsppc, ttlsimsesml, ttlsimstabc, ttlsimsct, ttlsimscca, ttlsimsce, ttlsimsswwm, ttlsimsgb, MB_th_list]
sims_dicts_MB.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames_2ndPass/sims_dicts_MB.csv')

In [822]:
ttlsimScores_cln

{'clean transportation transportation': 0.8166900873184204,
 'renewable energy renewable': 0.9201155304908752,
 'green buildings buildings': 0.839942991733551,
 'afof rdable housing housing': 1.0,
 'water management water': 0.8119471073150635,
 'waste management waste': 0.8286465406417847,
 'energy efficiency efficiency': 0.9004887938499451,
 'potable water supply water': 0.8469440937042236,
 'potable water supply potable': 0.8287600874900818,
 'sanitation sanitation': 1.0,
 'green buildings (ecological buildings) buildings': 0.8016582131385803,
 'food security food': 0.7798810005187988,
 'proyecto de energías renovables (energía hidroeléctrica – contribución a mitigación del cambio climático) de alimentos': 0.6540133953094482,
 'pequeñas centrales hidroeléctricas hidroelectricidad': 0.7128672003746033,
 'pequeñas centrales hidroeléctricas construcciones': 0.7090030908584595,
 'centrales eólicas (solo terrestres) cuadrícula (sólo)': 0.8724079728126526,
 'energías renovables renovable': 0.7062243223190308,
 'energías renovables bioenergía': 0.7306941151618958,
 'energías renovables hidroelectricidad': 0.6826406717300415,
 'energia renovável energia': 0.9140269160270691,
 'energia renovável bioenergia': 0.72825026512146,
 'energia renovável biocombustível': 0.7220384478569031,
 'energia renovável biomassa': 0.716290295124054,
 'energia renovável energia hidráulica': 0.8522579669952393}

In [823]:
ttlresimScores

{'renewable': 1.0,
 'cuadrícula (sólo)': 0.9524129033088684,
 'bioenergía': 0.8198481798171997,
 'hidroelectricidad': 0.8153159618377686,
 'Hidroeléctrico': 0.8471897840499878,
 'energia': 1.0,
 'energia hidráulica': 0.9084943532943726}

In [824]:
ttlsimsre

{'generation generation': 1.0,
 'power power': 1.0,
 'renewable renewable': 1.0,
 'solar solar': 1.0,
 'transmission transmission': 1.0,
 'storage storage': 1.0,
 'hydrogen hydrogen': 1.0,
 'grid grid': 1.0,
 'biofuel biofuel': 1.0,
 'wind wind': 1.0,
 'hydropower hydropower': 1.0,
 'biomass biomass': 1.0,
 'geothermal geothermal': 1.0,
 'hidroelectricidad hidroeléctricas': 0.8153160214424133,
 'generación generación': 1.0,
 'almacenamiento almacenamiento': 1.0,
 'bioenergía energía': 0.8198480606079102,
 'potencia capacidad': 0.8051767349243164,
 'generación cogeneración': 0.8619147539138794,
 'cuadrícula atmosféricas': 0.807408332824707,
 'renovable renovable': 1.0,
 'biocombustible combustible': 0.8335129022598267,
 'cuadrícula (': 0.9473557472229004,
 'cuadrícula iii': 0.8252873420715332,
 'cuadrícula plasma': 0.8057650327682495,
 'cuadrícula futuros': 0.8777064085006714,
 'generación transformación': 0.8076272010803223,
 'cuadrícula totales': 0.892815351486206,
 'cuadrícula vehículos': 0.8071877360343933,
 'biomasa biomasa': 1.0,
 'cuadrícula tecnología': 0.8814537525177002,
 'cuadrícula financiamiento': 0.8732093572616577,
 'cuadrícula )': 0.8254541158676147,
 'hidroelectricidad hidroeléctricos': 0.8131045699119568,
 'energia energia': 0.9084944128990173,
 'geração geração': 1.0}

In [825]:
ttlsimscca

{'adaptation adaptation': 1.0,
 'disaster disaster': 1.0,
 'adecuación adecuaciones': 0.806394100189209,
 'adecuación implementación': 0.8621118664741516,
 'adecuación integración': 0.8163694739341736,
 'adecuación optimización': 0.8359052538871765,
 'adecuación renovación': 0.8079515099525452,
 'adecuación modernización': 0.8007344603538513,
 'adecuación incorporación': 0.8026008009910583,
 'adecuación evaluación': 0.8495463132858276,
 'adecuación planeación': 0.808627724647522,
 'adecuación utilización': 0.8224044442176819,
 'adecuación habilitación': 0.8525652289390564,
 'adecuación fiscalización': 0.8114882707595825,
 'adecuación realización': 0.8257564902305603,
 'adecuación gasificación': 0.8322635889053345,
 'adecuación reutilización': 0.829303503036499,
 'adecuación transformación': 0.8015757203102112,
 'adecuación asignación': 0.8254500031471252,
 'adecuación adaptación': 0.816444456577301,
 'adecuación validación': 0.8463414311408997,
 'adecuación regulación': 0.8415524363517761}

In [826]:
ttlsimsppc

{'waste waste': 1.0,
 'pollution pollution': 1.0,
 'de de': 0.9079835414886475,
 'contaminación contaminación': 1.0,
 'contaminación contaminantes': 0.8567338585853577,
 'contaminación descarbonización': 0.8036044239997864,
 'contaminación descontaminación': 0.9332984685897827}

In [827]:
ttlsimsct

{'electric electric': 1.0,
 'car car': 1.0,
 'transportation transportation': 1.0,
 'rail rail': 1.0,
 'battery battery': 1.0,
 'vehicle vehicle': 1.0,
 'non non': 1.0,
 'la la': 0.939012348651886,
 'transporte transporte': 1.0,
 'eléctricos eléctricos': 1.0,
 'no no': 0.9680165648460388}

In [828]:
ttlsimsee

{'efficiency efficiency': 1.0}

In [829]:
ttlsimsce

{'reuse reuse': 1.0, 'circular circular': 1.0}

In [830]:
ttlsimsesml

{'food food': 1.0,
 'agriculture agriculture': 1.0,
 'forest forest': 1.0,
 'land land': 1.0,
 'forestry forestry': 1.0,
 'Arboricultura acuicultura': 0.8038574457168579,
 'pesquerías pesquería': 0.8017709255218506}

In [831]:
ttlsimsswwm

{'water water': 1.0,
 'potable potable': 1.0,
 'treatment treatment': 1.0,
 'wastewater wastewater': 1.0,
 'sanitation sanitation': 1.0,
 'saneamiento mantenimiento': 0.8064507842063904,
 '  potable': 1.0000001192092896,
 'saneamiento abastecimiento': 0.8477514386177063}

In [832]:
ttlsimstabc

{'biodiversity biodiversity': 1.0,
 'conservation conservation': 1.0,
 'terrestrial terrestrial': 1.0,
 'conservación aprovechamiento': 0.8383619785308838,
 'conservación mitigación': 0.8037376403808594,
 'conservación implementación': 0.8000835180282593,
 'conservación construcción': 0.806158721446991,
 'conservación contribución': 0.8010097742080688,
 'conservación recuperación': 0.8293237686157227,
 'conservación utilización': 0.817090630531311,
 'conservación restauración': 0.8449034690856934,
 'terrestre terrestres': 0.8388893604278564,
 'conservación realización': 0.8137819766998291,
 'conservación gasificación': 0.8011845946311951,
 'conservación reutilización': 0.8417978286743164,
 'conservación observación': 0.8122673034667969,
 'conservación reforestación': 0.8358405828475952,
 'biodiversidad biodiversidad': 1.0}

In [833]:
ttlsimsgb

{'buildings buildings': 1.0,
 'housing housing': 1.0,
 'y y': 0.9070735573768616,
 'la la': 0.947020411491394,
 'construcciones adecuaciones': 0.8131966590881348,
 'construcciones construcciones': 1.0,
 'construcciones plantaciones': 0.8306095004081726,
 'construcciones instalaciones': 0.807640016078949,
 'construcciones edificaciones': 0.9605708122253418}

In [112]:
# write dataframes to csvfiles with versions in the filenames

dataframes = [results_df, table_df, UOP_df, UOP_Words_df, pred_man_base_rpts]
dfname_list = ['results_df', 'table_df', 'UOP_df', 'UOP_Words_df', 'pred_train_rpts']
csvname_list = ['results_csv', 'table_csv', 'UOP_csv', 'UOP_Words_csv', 'pred_train_rpts_csv']
filepath = '/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames_man_base/'
extention = '.csv'
version = 'MB'


results_csv = results_df.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames_man_base/results_csv_MB.csv')
table_csv = table_df.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames_man_base/table_csv_MB.csv')
UOP_csv = UOP_df.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames_man_base/UOP_csv_MB.csv')
UOP_Words_csv = UOP_Words_df.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames_man_base/UOP_Words_csv_MB.csv')
pred_man_base_rpts_csv = pred_man_base_rpts.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames_man_base/pred_train_rpts_MB.csv')