In [292]:
# import libraries

import pymupdf
import spacy
import re
import pandas as pd
import numpy as np
#import unicodedata
import os
from pathlib import Path
from translate import Translator

In [4]:
!python3 -m spacy download es_core_news_lg

Collecting es-core-news-lg==3.8.0
  Downloading es_core_news_lg-3.8.0-py3-none-any.whl (568.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 568.0/568.0 MB 4.2 MB/s  0:02:080:00:0100:04

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
✔ Download and installation successful
You can now load the package via spacy.load('es_core_news_lg')

In [2]:
# nlp piplines from spacy for the 3 languages. large chosen for the higher dimension word vector libraries

nlp_en = spacy.load('en_core_web_lg')
nlp_pt = spacy.load('pt_core_news_lg')
nlp_es = spacy.load('es_core_news_lg')

In [293]:
# lists of green bond category words for usse in spacy similarity method 

not_re_cat_words_en = ['efficiency', 'retrofit', 'pollution', 'waste', 'land', 'agriculture', 'forestry', 'forest', 
                      'fisheries', 'food', 'terrestrial', 'aquatic', 'biodiversity', 'conservation', 'transportation', 
                      'electric', 'battery', 'EV', 'charger', 'bus', 'rail', 'train', 'car', 'vehicle', 'bicycle', 
                      'non-motorized', 'aviation', 'water', 'potable', 'wastewater', 'sanitation', 'treatment', 
                      'adaptation', 'disaster', 'circular', 'recycle', 'reuse','buildings', 'appliances', 'housing']

all_cat_words_en = ['renewable', 'solar', 'wind', 'bioenergy', 'biofuel', 'biomass', 'hydropower', 'hydrogen', 
                     'hydroelectric', 'power', 'grid', 'transmission', 'generation', 'geothermal', 'storage', 
                     'efficiency', 'retrofit', 'pollution', 'waste', 'land', 'agriculture', 'forestry', 'forest', 
                     'fisheries', 'food', 'terrestrial', 'aquatic', 'biodiversity', 'conservation', 'transportation',
                     'electric', 'battery', 'EV', 'charger', 'bus', 'rail', 'train', 'car', 'vehicle', 'bicycle', 
                     'non-motorized', 'aviation', 'water', 'potable', 'wastewater', 'sanitation', 'treatment', 
                     'adaptation', 'disaster', 'circular', 'recycle', 'reuse','buildings', 'appliances', 'housing']

renewable_energy_en = ['renewable', 'solar', 'wind', 'bioenergy', 'biofuel', 'biomass', 'hydropower', 'hydrogen', 'hydroelectric', 'power', 'grid', 'transmission', 'generation', 'geothermal', 'storage']
energy_efficiency_en = ['efficiency', 'retrofit']
pollution_prevention_and_control_en = ['pollution', 'waste']
environmentally_sustainable_management_of_living_natural_resources_and_land_use_en = ['land', 'agriculture', 'forestry', 'forest', 'fisheries', 'food']
terrestrial_and_aquatic_biodiversity_conservation_en = ['terrestrial', 'aquatic', 'biodiversity', 'conservation']
clean_transportation_en = ['transportation', 'electric', 'battery', 'EV', 'charger', 'bus', 'rail', 'train', 'car', 'vehicle', 'bicycle', 'non-motorized', 'aviation']
sustainable_water_and_wastewater_management_en = ['water', 'potable', 'wastewater', 'sanitation', 'treatment']
climate_change_adaptation_en = ['adaptation', 'disaster']
circular_economy_and_or_ecoefficient_projects_en = ['circular', 'recycle', 'reuse']
green_buildings_en = ['buildings', 'appliances', 'housing']

In [294]:
# iterate each word in the lists through the Translator from translate - English to Portuguese

not_re_cat_words_pt = []
all_cat_words_pt = []
renewable_energy_pt = []
energy_efficiency_pt = []
pollution_prevention_and_control_pt = []
environmentally_sustainable_management_of_living_natural_resources_and_land_use_pt = []
terrestrial_and_aquatic_biodiversity_conservation_pt = []
clean_transportation_pt = []
sustainable_water_and_wastewater_management_pt = []
climate_change_adaptation_pt = []
circular_economy_and_or_ecoefficient_projects_pt = []
green_buildings_pt = []


translator = Translator(to_lang='pt',from_lang='en')
# for word in not_re_cat_words_en:
    # translation = translator.translate(word)
    # not_re_cat_words_pt.append(translation)
for word in all_cat_words_en:
    translation = translator.translate(word)
    all_cat_words_pt.append(translation)
for word in renewable_energy_en:
    translation = translator.translate(word)
    renewable_energy_pt.append(translation)
for word in energy_efficiency_en:
    translation = translator.translate(word)
    energy_efficiency_pt.append(translation)
for word in pollution_prevention_and_control_en:
    translation = translator.translate(word)
    pollution_prevention_and_control_pt.append(translation)
for word in environmentally_sustainable_management_of_living_natural_resources_and_land_use_en:
    translation = translator.translate(word)
    environmentally_sustainable_management_of_living_natural_resources_and_land_use_pt.append(translation)
for word in terrestrial_and_aquatic_biodiversity_conservation_en:
    translation = translator.translate(word)
    terrestrial_and_aquatic_biodiversity_conservation_pt.append(translation)
for word in clean_transportation_en:
    translation = translator.translate(word)
    clean_transportation_pt.append(translation)
for word in sustainable_water_and_wastewater_management_en:
    translation = translator.translate(word)
    sustainable_water_and_wastewater_management_pt.append(translation)
for word in climate_change_adaptation_en:
    translation = translator.translate(word)
    climate_change_adaptation_pt.append(translation)
for word in circular_economy_and_or_ecoefficient_projects_en:
    translation = translator.translate(word)
    circular_economy_and_or_ecoefficient_projects_pt.append(translation)
for word in green_buildings_en:
    translation = translator.translate(word)
    green_buildings_pt.append(translation)

In [ ]:
# manually inspect the pt lists for periods and aritcles
# correct for : ., dis, la, de, no, y, red

['renovable',
 'solar',
 'viento',
 'bioenergía',
 'biocombustible',
 'biomasa ',
 'hidroelectricidad',
 'hydrogen',
 'Hidroeléctrico',
 'potencia',
 'cuadrícula (sólo)',
 'Transporte',
 'generación',
 'geotérmica',
 'almacenamiento ',
 'red de rutas',
 'acondicionar',
 'contaminación',
 'de alimentos',
 'terreno',
 '.',
 'Arboricultura',
 'bosque',
 'pesquerías',
 'alimentos',
 'terrestre',
 'acuático',
 'biodiversidad',
 'conservación ',
 'transporte',
 'eléctricos',
 'batería',
 'EV',
 'cargador',
 'autobús',
 'riel',
 'tren',
 'dis',
 'vehículo',
 'la bicicleta',
 'no motorizado',
 'la aviación',
 'de agua',
 ' potable',
 'Aguas residuales',
 'saneamiento',
 'subterraneas',
 'adecuación',
 'desastre',
 'circular',
 'reciclar',
 'reutilizar',
 'construcciones',
 'y electrónicos',
 'la vivienda']

In [295]:
# iterate each word in the lists through the Translator from translate - English to Spanish

not_re_cat_words_es = []
all_cat_words_es = []
renewable_energy_es = []
energy_efficiency_es = []
pollution_prevention_and_control_es = []
environmentally_sustainable_management_of_living_natural_resources_and_land_use_es = []
terrestrial_and_aquatic_biodiversity_conservation_es = []
clean_transportation_es = []
sustainable_water_and_wastewater_management_es = []
climate_change_adaptation_es = []
circular_economy_and_or_ecoefficient_projects_es = []
green_buildings_es = []


translator = Translator(to_lang='es',from_lang='en')
# for word in not_re_cat_words_en:
    # translation = translator.translate(word)
    # not_re_cat_words_es.append(translation)
for word in all_cat_words_en:
    translation = translator.translate(word)
    all_cat_words_es.append(translation)
for word in renewable_energy_en:
    translation = translator.translate(word)
    renewable_energy_es.append(translation)
for word in energy_efficiency_en:
    translation = translator.translate(word)
    energy_efficiency_es.append(translation)
for word in pollution_prevention_and_control_en:
    translation = translator.translate(word)
    pollution_prevention_and_control_es.append(translation)
for word in environmentally_sustainable_management_of_living_natural_resources_and_land_use_en:
    translation = translator.translate(word)
    environmentally_sustainable_management_of_living_natural_resources_and_land_use_es.append(translation)
for word in terrestrial_and_aquatic_biodiversity_conservation_en:
    translation = translator.translate(word)
    terrestrial_and_aquatic_biodiversity_conservation_es.append(translation)
for word in clean_transportation_en:
    translation = translator.translate(word)
    clean_transportation_es.append(translation)
for word in sustainable_water_and_wastewater_management_en:
    translation = translator.translate(word)
    sustainable_water_and_wastewater_management_es.append(translation)
for word in climate_change_adaptation_en:
    translation = translator.translate(word)
    climate_change_adaptation_es.append(translation)
for word in circular_economy_and_or_ecoefficient_projects_en:
    translation = translator.translate(word)
    circular_economy_and_or_ecoefficient_projects_es.append(translation)
for word in green_buildings_en:
    translation = translator.translate(word)
    green_buildings_es.append(translation)

In [306]:
# find tables in the document and return table info
# pdfname: https://www.geeksforgeeks.org/python/get-filename-from-path-without-extension-using-python/

def catTable(document, tableStrategy):
    
    pdf = pymupdf.open(document) 
    filename = os.path.basename(document)
    pdfname = filename.split('.',1)[0]

    tableCount = 0
    tablePages = []
    tableHeaders = []
    tableDFs = []


    for page_idx in range(len(pdf)): 
        page = pdf[page_idx]

        find_tables = page.find_tables(strategy = tableStrategy)
        if find_tables.tables:
            table_count = len(find_tables.tables)
            tableheader = find_tables[0].header.names # assume only 1 table per page
            tableDF = find_tables[0].to_pandas()
            tableCount += table_count
            tablePages.append(page_idx)
            tableHeaders.append(tableheader)
            tableDFs.append(tableDF)

    return filename, pdfname, tableCount, tablePages, tableHeaders, tableDFs

In [305]:
# assess the tables found in the catTable function to identify the Category tables and extract unique list of category phrases

def tableAssess(language, tableCount, tablePages, tableHeaders, tableDFs):

    if language == 'PT':
        keywordsCAT = ['Categoria']
        nlp = nlp_pt
    elif language == 'ES':
        keywordsCAT = ['Categoría', 'Categorías']
        nlp = nlp_es
    elif language == 'EN':
        keywordsCAT = ['Category', 'Categories', 'Criteria', 'Criterion']
        nlp = nlp_en
    
    tablePageCurrent = 0
    tablePagePrior = 0
    tablepageCurrentTrue = 0
    uniqueCats = []
    uniqueCatsNoDupes = []
    table_idx = []

    if tableCount == 1: # applicable if only 1 table detected in whole pdf
        dataFrame = tableDFs[0]
        header = tableHeaders[0]
        for keyword in keywordsCAT:
            if keyword.lower() in header[0].lower(): # assumes category col is always the first (LHS) col
                colName = header[0]
                uniqueC = dataFrame[colName].dropna().unique().tolist()
                for messyCat in uniqueC:
                    if messyCat:
                        tidyCat = messyCat.replace('\n',' ').lower()
                        uniqueCatsNoDupes.append(tidyCat)
                        table_idx.append(0)
    elif tableCount > 1:
        for idx in range(len(tableDFs)): # count of tableHeaders and DFs should be the same, based on the page level find_tables object
            tablePageCurrent = tablePages[idx]
            dataFrame = tableDFs[idx]
            header = tableHeaders[idx]
            for keyword in keywordsCAT:
                if keyword.lower() in header[0].lower():
                    colName = header[0]
                    uniqueC = dataFrame[colName].dropna().unique().tolist() # unique list of phrases in left hand col of table
                    tablepageCurrentTrue = tablePageCurrent
                    for messyCat in uniqueC:
                        if messyCat:
                            tidyCat = messyCat.replace('\n',' ').lower()
                            uniqueCats.append(tidyCat)
                            table_idx.append(idx)
                elif header[0] == 'Col0' and tablePageCurrent - tablepageCurrentTrue == 1: # the condition where the last keyword-compliant table processed was one page before the current table 
                    uniqueC = dataFrame['Col0'].dropna().unique().tolist()
                    if uniqueC:
                        for messyCat in uniqueC:
                            if messyCat:
                                tidyCat = messyCat.replace('\n',' ').lower()
                                uniqueCats.append(tidyCat)
                                table_idx.append(idx)
            tablePagePrior = tablePageCurrent
        uniqueCatsNoDupes = list(set(uniqueCats))

    return uniqueCatsNoDupes, table_idx

In [344]:
# clean up spurious table content and assess presence of enerygy systems

def tableClean(language, uniqueCatsNoDupes):

    sim_th_en = 0.97
    sim_th_pt = 0.97
    sim_th_es = 0.97
    cleanup_TH_en = 0.77
    cleanup_TH_pt = 0.77
    cleanup_TH_es = 0.77

    if language == 'PT':
        re = renewable_energy_pt
        not_re = not_re_cat_words_pt
        all = all_cat_words_pt
        nlp = nlp_pt
        cleanup_TH = cleanup_TH_pt
        similarity_threshold = sim_th_pt
    elif language == 'ES':
        re = renewable_energy_es
        not_re = not_re_cat_words_es
        all = all_cat_words_es
        nlp = nlp_es
        cleanup_TH = cleanup_TH_es
        similarity_threshold = sim_th_es
    elif language == 'EN':
        re = renewable_energy_en
        not_re = not_re_cat_words_en
        all = all_cat_words_en
        nlp = nlp_en
        cleanup_TH = cleanup_TH_en
        similarity_threshold = sim_th_en

    CatwordsFinal = []
    simScores_cln = {}
    notresimScores = {}
    resimScores = {}
    energy_system_tbl = ""

    if len(uniqueCatsNoDupes) > 0:
        for cat in uniqueCatsNoDupes: # phrases from tables' left hand cols
            docCat = nlp(cat) # run phrase through nlp pipeline
            for wordx in all:
                docx = nlp(wordx)
                simScore_cln = docCat.similarity(docx) # compare each cat phrase to all ref words
                if simScore_cln >= cleanup_TH: 
                    CatwordsFinal.append(cat)
                    simScores_cln[cat + ' ' + wordx] = simScore_cln 
                    dfsimScores_cln = pd.DataFrame.from_dict(simScores_cln, 'index')
                    CatwordsFFinal = list(set(CatwordsFinal))
        if len(CatwordsFinal) > 0: # True cond based on attribute 'guaranteed' to exist
            for phrase in CatwordsFFinal: # only phrases that pass the cleanup TH and based on de-duped list
                docPhrase = nlp(phrase)
                for wordy in docPhrase:
                    if wordy.has_vector:
                        for worda in re: # for es noise clean up, none in RE list
                            doca = nlp(worda)
                            resimScore = wordy.similarity(doca) # compare each word (token) in each cat phrase to renewable energy ref words
                            if resimScore >= similarity_threshold:
                                resimScores[worda] = resimScore
                                dfresimScores = pd.DataFrame.from_dict(resimScores, 'index')
            if resimScores:                     
                energy_system_tbl = True
            else:
                energy_system_tbl = False
                dfresimScores = pd.DataFrame()
        else:
            CatwordsFFinal = []
            dfsimScores_cln = pd.DataFrame()
            dfresimScores = pd.DataFrame()
    else:
        CatwordsFFinal = []
        dfsimScores_cln = pd.DataFrame()
        dfresimScores = pd.DataFrame()

    return CatwordsFFinal, CatwordsFinal, dfsimScores_cln, simScores_cln, dfresimScores, resimScores, energy_system_tbl, cleanup_TH_en, cleanup_TH_es, cleanup_TH_pt

In [303]:
# to find the Use of Proceeds portion of the document, returns font info for key phrases that typically indicate the start and end of that portion

def fontInfo(language, document):

    results_UOP = []
    results_SEEGP = []
    
    pdf = pymupdf.open(document)
    
    if language == 'PT':
        keywordsUOP = ['Usos dos Recursos', 'Uso de Recursos']
        keywordsSEEGP = ['Selection and Evaluation', 'Process for the Project Evaluation and Selection', 'Project Evaluation and Selection Process', 'Project Selection and Evaluation Process', 'Process for Project Evaluation and Selection', 'Project Selection and Assessment Process', 'Project Selection Criteria', 'Project evaluation & selection', 'Project Selection Process']
        keywordsSEEGP_test = ['Avaliação e Seleção de Ativos', 'Processo de Avaliação e Seleção de Projetos']
    elif language == 'ES':
        keywordsUOP = ['Uso de los Fondos', 'Uso de Fondos', 'Uso de Recursos', 'Destinos de Fondos', 'Uso de los Recursos']
        keywordsSEEGP_test = ['Proceso de Evaluación y Selección de Proyectos', 'Selección y Evaluación de Proyectos', 'Procedimiento Selección', 'Evaluación y selección de proyectos']
    elif language == 'EN':
        keywordsUOP = ['Use of Proceeds', 'Use of Funds', 'Use of the Proceeds']
        keywordsSEEGP = ['Selection and Evaluation', 'Process for the Project Evaluation and Selection', 'Project Evaluation and Selection Process', 'Project Selection and Evaluation Process', 'Process for Project Evaluation and Selection', 'Project Selection and Assessment Process', 'Project Selection Criteria', 'Project evaluation & selection', 'Project Selection Process']
        keywordsSEEGP_test = ['Selection and Evaluation', 'Process for', 'Evaluation and Selection', 'Project Evaluation', 'Assessment Process', 'Selection process', 'Project selection criteria']


    for page_idx in range(len(pdf)): 
        page = pdf[page_idx]
        dict = page.get_text("dict")
        blocks = dict["blocks"] 
        for block in blocks:
            if "lines" in block.keys():
                spans = block['lines']
                for span in spans:
                    data = span['spans']
                    for lines in data:
                        for keyword in keywordsUOP:
                            if keyword.lower() in lines['text'].lower().strip():
                                results_UOP.append((lines['text'], lines['size'], lines['bbox'], page_idx))
                        for keyword in keywordsSEEGP_test:
                            if keyword.lower() in lines['text'].lower().strip():
                                results_SEEGP.append((lines['text'], lines['size'], lines['bbox'], page_idx))

                            

    return results_UOP, results_SEEGP

In [302]:
# from the results of the previous function, returns the result index containing the highest font size, assuming this is a section header 

def find_max_font(results_UOP, results_SEEGP):
    
    max_font_size_UOP = 0
    for result_idx_UOP in range(len(results_UOP)):
        resultA = results_UOP[result_idx_UOP]
        if resultA[1] > max_font_size_UOP:
            max_font_size_UOP = resultA[1]
            max_idx_UOP = result_idx_UOP

    max_font_size_SEEGP = 0
    if len(results_SEEGP) == 0:
        max_idx_SEEGP = 0
    else:       
        for result_idx_SEEGP in range(len(results_SEEGP)):
            resultB = results_SEEGP[result_idx_SEEGP]
            if resultB[1] > max_font_size_SEEGP:
                max_font_size_SEEGP = resultB[1]
                max_idx_SEEGP = result_idx_SEEGP

    return max_idx_UOP, max_idx_SEEGP

In [301]:
# corrects the UOP portion in the cases where the functions above have returned the table of contents instances of the start and end key phrases 

def tocCheck(results_UOP, results_SEEGP, max_idx_UOP, max_idx_SEEGP):
    
    if len(results_SEEGP) == 0:
        areaUOP = results_UOP[max_idx_UOP]
        areaUOP_page = areaUOP[3]
        areaUOP_coords = areaUOP[2]
        areaUOP_y1 = areaUOP_coords[3]
        areaSEEGP_page = 0
        areaSEEGP_y0 = 0

    else:
        areaUOP = results_UOP[max_idx_UOP]
        areaSEEGP = results_SEEGP[max_idx_SEEGP]
        areaUOP_page = areaUOP[3]
        areaSEEGP_page = areaSEEGP[3]
        areaUOP_coords = areaUOP[2]
        areaSEEGP_coords = areaSEEGP[2]
        areaUOP_y1 = areaUOP_coords[3]
        areaSEEGP_y0 = areaSEEGP_coords[1]

        if areaUOP_page == areaSEEGP_page:
            if 0 < areaSEEGP_y0 - areaUOP_y1 < 40:
                results_UOP_remove = results_UOP.pop(max_idx_UOP)
                results_SEEGP_remove = results_SEEGP.pop(max_idx_SEEGP)

                max_idx_UOP, max_idx_SEEGP = find_max_font(results_UOP, results_SEEGP)

                areaUOP = results_UOP[max_idx_UOP]
                areaSEEGP = results_SEEGP[max_idx_SEEGP]
                areaUOP_page = areaUOP[3]
                areaSEEGP_page = areaSEEGP[3]
                areaUOP_coords = areaUOP[2]
                areaSEEGP_coords = areaSEEGP[2]
                areaUOP_y1 = areaUOP_coords[3]
                areaSEEGP_y0 = areaSEEGP_coords[1]

    return areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0

In [300]:
# discards the UOP end boundary in cases where it comes before the start boundary

def keepSEEGP(areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0):

    if areaSEEGP_page == areaUOP_page:
        if areaSEEGP_y0 < areaUOP_y1:
            keep_areaSEEGP = False
        elif areaSEEGP_y0 > areaUOP_y1:
            keep_areaSEEGP = True
    elif areaSEEGP_page > areaUOP_page:
        keep_areaSEEGP = True
    elif areaSEEGP_page < areaUOP_page:
        keep_areaSEEGP = False

    return keep_areaSEEGP

In [241]:
# page scenarios and extract words when keep_areaSEEGP = True
# function called by another function

def wordsUOP_endPage(document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0):

    pdf = pymupdf.open(document)
    extractUOPwords = []

    # iterate pages
    for page_idx in range(len(pdf)):
        page = pdf[page_idx]

       
# process four page scenarios and extract text as words
    # A: UOP all on a single page
        if page_idx == areaUOP_page and page_idx == areaSEEGP_page:
            for word in page.get_text('words'):
                x0, y0, x1, y1, messyText, *_ = word
                if y0 > areaUOP_y1 and y1 < areaSEEGP_y0:
                    tidyText = messyText.replace('\n',' ').lower()
                    extractUOPwords.append(tidyText)

    # UOP across >1 page
    # B: current page is start page
        elif page_idx == areaUOP_page:
            for word in page.get_text('words'):
                x0, y0, x1, y1, messyText, *_ = word
                if y0 > areaUOP_y1:
                    tidyText = messyText.replace('\n',' ').lower()
                    extractUOPwords.append(tidyText)

    # D: current page is neither start nor end page but is in the UOP area
        elif page_idx > areaUOP_page and page_idx < areaSEEGP_page:
            for word in page.get_text('words'):
                x0, y0, x1, y1, messyText, *_ = word
                tidyText = messyText.replace('\n',' ').lower()
                extractUOPwords.append(tidyText)

    # C: current page is end page
        elif page_idx == areaSEEGP_page:
                for word in page.get_text('words'):
                    x0, y0, x1, y1, messyText, *_ = word
                    if y1 < areaSEEGP_y0:
                        tidyText = messyText.replace('\n',' ').lower()
                        extractUOPwords.append(tidyText)

    return extractUOPwords

In [242]:
# iterate pages in the pdf and extract words, preferrably between the UOP and SEEGP sections or else from UOP to end

def wordsUOP(keep_areaSEEGP, document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0):
    # language = language

    pdf = pymupdf.open(document)

    if keep_areaSEEGP == True:
        extractUOPwords = wordsUOP_endPage(document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0)
        UOPwordsNoDupes = list(set(extractUOPwords))

    elif keep_areaSEEGP == False:
        extractUOPwords = []

# iterate pages
        for page_idx in range(len(pdf)):
            page = pdf[page_idx]
       
    # process two page scenarios and extract text as words

        # assume UOP across > 1 page
        # B: current page is start page
            if page_idx == areaUOP_page:
                for word in page.get_text('words'):
                    x0, y0, x1, y1, messyText, *_ = word
                    if y0 > areaUOP_y1:
                        tidyText = messyText.replace('\n',' ').lower()
                        extractUOPwords.append(tidyText)

        # E: current page is after the UOP start page
            elif page_idx > areaUOP_page:
                for word in page.get_text('words'):
                    x0, y0, x1, y1, messyText, *_ = word
                    tidyText = messyText.replace('\n',' ').lower()
                    extractUOPwords.append(tidyText)
    
        UOPwordsNoDupes = list(set(extractUOPwords))
    
    return UOPwordsNoDupes

In [346]:
# process words into category word dictionaries where doc.similarity score passes threshold

def UOPwords_to_Catwords(language, UOPwordsNoDupes):

    sim_th_en = 0.97
    sim_th_pt = 0.97
    sim_th_es = 0.97

    es_noise = ['.', 'y', 'la', 'de', 'no', 'red', 'dis', 'non']

    if language == 'EN':
        nlp = nlp_en
        re = renewable_energy_en
        ee = energy_efficiency_en
        ppc = pollution_prevention_and_control_en
        esml = environmentally_sustainable_management_of_living_natural_resources_and_land_use_en
        tabc = terrestrial_and_aquatic_biodiversity_conservation_en
        ct = clean_transportation_en
        swwm = sustainable_water_and_wastewater_management_en
        cca = climate_change_adaptation_en
        ce = circular_economy_and_or_ecoefficient_projects_en
        gb = green_buildings_en
        similarity_threshold = sim_th_en
    elif language == 'PT':
        nlp = nlp_pt
        re = renewable_energy_pt
        ee = energy_efficiency_pt
        ppc = pollution_prevention_and_control_pt
        esml = environmentally_sustainable_management_of_living_natural_resources_and_land_use_pt
        tabc = terrestrial_and_aquatic_biodiversity_conservation_pt
        ct = clean_transportation_pt
        swwm = sustainable_water_and_wastewater_management_pt
        cca = climate_change_adaptation_pt
        ce = circular_economy_and_or_ecoefficient_projects_pt
        gb = green_buildings_pt
        similarity_threshold = sim_th_pt
    elif language == 'ES':
        nlp = nlp_es
        re = renewable_energy_es
        ee = energy_efficiency_es
        ppc = pollution_prevention_and_control_es
        esml = environmentally_sustainable_management_of_living_natural_resources_and_land_use_es
        tabc = terrestrial_and_aquatic_biodiversity_conservation_es
        ct = clean_transportation_es
        swwm = sustainable_water_and_wastewater_management_es
        cca = climate_change_adaptation_es
        ce = circular_economy_and_or_ecoefficient_projects_es
        gb = green_buildings_es
        similarity_threshold = sim_th_es

    # outputs
    simsre = {}
    energy_system_uop = ""
    simsee = {}
    simsppc = {}
    simsesml = {}
    simstabc = {}
    simsct = {}
    simsswwm = {}
    simscca = {}
    simsce = {}
    simsgb = {}
    cat_count_uop = 0
    

    for wordb in UOPwordsNoDupes:
        docb = nlp(wordb)
        for token in docb: # expect each docb has only 1 token
            if token.text not in es_noise:
                if token.has_vector:
        # renewable_energy
                    for worda in re:
                        doca = nlp(worda)
                        sim = doca.similarity(docb)
                        if sim >= similarity_threshold:
                            simsre[doca[0].text + ' ' + docb[0].text] = sim

        # energy_efficiency
                    for wordc in ee:
                        docc = nlp(wordc)
                        sim = docc.similarity(docb)
                        if sim >= similarity_threshold:
                            simsee[docc[0].text + ' ' + docb[0].text] = sim
        
        # pollution_prevention_and_control
                    for wordd in ppc:
                        docd = nlp(wordd)
                        sim = docd.similarity(docb)
                        if sim >= similarity_threshold:
                            simsppc[docd[0].text + ' ' + docb[0].text] = sim

        # environmentally_sustainable_management_of_living_natural_resources_and_land_use
                    for worde in esml:
                        doce = nlp(worde)
                        sim = doce.similarity(docb)
                        if sim >= similarity_threshold:
                            simsesml[doce[0].text + ' ' + docb[0].text] = sim

        # terrestrial_and_aquatic_biodiversity_conservation
                    for wordf in tabc:
                        docf = nlp(wordf)
                        sim = docf.similarity(docb)
                        if sim >= similarity_threshold:
                            simstabc[docf[0].text + ' ' + docb[0].text] = sim

        # clean_transportation
                    for wordg in ct:
                        docg = nlp(wordg)
                        sim = docg.similarity(docb)
                        if sim >= similarity_threshold:
                            simsct[docg[0].text + ' ' + docb[0].text] = sim

        # sustainable_water_and_wastewater_management
                    for wordh in swwm:
                        doch = nlp(wordh)
                        sim = doch.similarity(docb)
                        if sim >= similarity_threshold:
                            simsswwm[doch[0].text + ' ' + docb[0].text] = sim

        # climate_change_adaptation
                    for wordi in cca:
                        doci = nlp(wordi)
                        sim = doci.similarity(docb)
                        if sim >= similarity_threshold:
                            simscca[doci[0].text + ' ' + docb[0].text] = sim
        
        # circular_economy_and_or_ecoefficient_projects
                    for wordj in ce:
                        docj = nlp(wordj)
                        sim = docj.similarity(docb)
                        if sim >= similarity_threshold:
                            simsce[docj[0].text + ' ' + docb[0].text] = sim
        
        # green_buildings
                    for wordk in gb:
                        dock = nlp(wordk)
                        sim = dock.similarity(docb)
                        if sim >= similarity_threshold:
                            simsgb[dock[0].text + ' ' + docb[0].text] = sim

    if simsre:
        energy_system_uop = True
        cat_count_uop +=1
    else:
        energy_system_uop = False
    if simsee:
        cat_count_uop +=1
    if simsppc:
        cat_count_uop +=1
    if simsesml:
        cat_count_uop +=1
    if simstabc:
        cat_count_uop +=1
    if simsct:
        cat_count_uop +=1
    if simsswwm:
        cat_count_uop +=1
    if simscca:
        cat_count_uop +=1
    if simsce:
        cat_count_uop +=1
    if simsgb:
        cat_count_uop +=1

    return simsre, simsee, simsppc, simsesml, simstabc, simsct, simsswwm, simscca, simsce, simsgb, sim_th_en, sim_th_es, sim_th_pt, energy_system_uop, cat_count_uop

In [ ]:
# list of pdf filenames

pdf_en = ['Bci_Sustainable_Financing_Framework','BTG_Pactual_Green,_Social_and_Sustainable_Financing_Framework',
          'BTG_Sustainable_Financing_Framework','CABEI_Green_Bond_Framework','CADU_GREEN_BOND_FRAMEWORK',
          'CAFs_GREEN_BOND_FRAMEWORK','CIFI_Green_Bond_Framework','EGE_Haina_Green_Securities_Framework',
          'FS_Green_Bond_Framework_-_July_2021','FS_Green_Bond_Framework_-_November_2020','Genneia_Green_Bond_Framework', 
          'Green_Bond_Financing_Framework','Green_Bond_Framework_of_Banco_Guayaquil',
          'Green_Finance_Framework_Interchile','Green_social_bond_framework_series_ad_ae_2019',
          'ILAP_Green_Financing_Framework','ISA_CTM_FRAMEWORK','Marco_de_referencia_de_Bonos_Verdes_Soberanos_de_Colombia',
          'Nacional_Financiera_Green_Bond_USD','Sicredi_Green_Bond_Framework','SONDA_S_A__GREEN_BOND_FRAMEWORK']
pdf_en_lines =['Chile_Sustainable_Bond_Framework', 'Genneia_Green_Financing_Framework']
pdf_es = ['Marco_de_Gestión_de_Bono_Verde',
          'Marco_de_referencia_de_bono_verde_Coopeguanacaste,_R_L_','Marco_de_Referencia_del_Bono_Verde_de_la_Ciudad_de_Mexico',
          'Nacional_Financiera_Green_Bond_MXN']
pdf_es_lines = ['Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos_Verdes,_Sociales_o_Sostenibles_BDP_I']
pdf_pt = ['Green_Bond_Framework', 'Green_Bonds_Framework_Athon_2020']

In [347]:
# run the pdf through the pipeline - first pdf, initialise the dataframes

# input parameters
document = '/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/PDF1/Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__in_2021.pdf'
language = 'EN'
tableStrategy = 'lines_strict'

# call the functions in sequence
filename, pdfname, tableCount, tablePages, tableHeaders, tableDFs = catTable(document, tableStrategy)
uniqueCatsNoDupes, table_idx = tableAssess(language, tableCount, tablePages, tableHeaders, tableDFs)
CatwordsFFinal, CatwordsFinal, dfsimScores_cln, simScores_cln, dfresimScores, resimScores, energy_system_tbl, cleanup_TH_en, cleanup_TH_es, cleanup_TH_pt = tableClean(language, uniqueCatsNoDupes)
results_UOP, results_SEEGP = fontInfo(language, document)
max_idx_UOP, max_idx_SEEGP = find_max_font(results_UOP, results_SEEGP)
areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0 = tocCheck(results_UOP, results_SEEGP, max_idx_UOP, max_idx_SEEGP)
keep_areaSEEGP = keepSEEGP(areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0)
UOPwordsNoDupes = wordsUOP(keep_areaSEEGP, document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0)

# dataframe output for transparency on how pipeline has processed the pdf
columns = ['pdfname', 'language', 'tableCount', 'areaUOP_page', 'areaUOP_y1', 'areaSEEGP_page', 'areaSEEGP_y0', 'keep_areaSEEGP', 'countUOP_words']
results_df = pd.DataFrame(columns=columns)
results_df.loc[len(results_df)] = [pdfname, language, tableCount, areaUOP_page, areaUOP_y1, areaSEEGP_page,areaSEEGP_y0, keep_areaSEEGP, len(UOPwordsNoDupes)]

# table info
columns = ['pdfname', 'tablePages_list', 'table.Headers_list', 'countCat_words', 'unique compliant Categories_list', 'energy_system_tbl', 'table_idx_list', 'unique Cats all', 'simScores_cln', 'resimScores']
table_df = pd.DataFrame(columns=columns)

# UOP start and end info
columns = ['pdfname', 'results_UOP_list (text, fontSize, bbox, page_idx)', 'max_idx_UOP', 'results_SEEGP_list (text, fontSize, bbox, page_idx)', 'max_idx_SEEGP']
UOP_df = pd.DataFrame(columns=columns)
UOP_df.loc[len(UOP_df)] = [pdfname, results_UOP, max_idx_UOP, results_SEEGP, max_idx_SEEGP]

# initialise sim score dicts
ttlsimsre = {}
ttlsimsee = {}
ttlsimsppc = {}
ttlsimsesml = {}
ttlsimstabc = {}
ttlsimsct = {}
ttlsimsswwm = {}
ttlsimscca = {}
ttlsimsce = {}
ttlsimsgb = {}
ttlresimScores = {}
ttlsimScores_cln = {}

# final Cateogory info
if len(CatwordsFinal) == 0:
    print('')
    print(pdfname)
    print('categories from UOP portion')
    simsre, simsee, simsppc, simsesml, simstabc, simsct, simsswwm, simscca, simsce, simsgb, sim_th_en, sim_th_es, sim_th_pt, energy_system_uop, cat_count_uop = UOPwords_to_Catwords(language, UOPwordsNoDupes)
    columns = ['pdfname', 'energy_system_uop', 'simsre', 'simsee', 'simsppc', 'simsesml', 'simstabc', 'simsct', 'simsswwm', 'simscca', 'simsce', 'simsgb']
    UOP_Words_df = pd.DataFrame(columns=columns)
    UOP_Words_df.loc[len(UOP_Words_df)] = [pdfname, energy_system_uop, simsre, simsee, simsppc, simsesml, simstabc, simsct, simsswwm, simscca, simsce, simsgb]
    
    ttlsimsre |= simsre
    ttlsimsee |= simsee
    ttlsimsppc |= simsppc
    ttlsimsesml |= simsesml
    ttlsimstabc |= simstabc
    ttlsimsct |= simsct
    ttlsimsswwm |= simsswwm
    ttlsimscca |= simscca
    ttlsimsce |= simsce
    ttlsimsgb |= simsgb

else:
    print('')
    print(pdfname)
    print('categories from tables')
    table_df.loc[len(table_df)] = [pdfname, tablePages, tableHeaders, len(CatwordsFFinal), CatwordsFFinal, energy_system_tbl, table_idx, uniqueCatsNoDupes, simScores_cln, resimScores]

    ttlresimScores |= resimScores
    ttlsimScores_cln |= simScores_cln

# data table with results, for evaluation to ground truth
# nlp_path 
nlp_path = ""
if len(CatwordsFinal)>0:
    nlp_path = 'Table'
elif len(CatwordsFinal)==0 and keep_areaSEEGP == True:
    nlp_path = 'UOP_section_true'
elif len(CatwordsFinal)==0 and keep_areaSEEGP == False:
    nlp_path = 'UOP_section_false'

# ES percent oucomes
ES_0_percent = False
ES_100_percent = False
ES_partial = False

if energy_system_tbl == False or energy_system_uop == False:
    ES_0_percent = True

elif energy_system_tbl == True:
    if len(CatwordsFFinal) == 1: # CatwordsFFinal is the de-duped list of words that pass cleanup-threshold sim, originally the unique phrases from LHCol of qualifying tables 
        ES_100_percent = True
    elif len(CatwordsFFinal) > 1:
        ES_partial = True

elif energy_system_uop == True:
    if cat_count_uop == 1:
        ES_100_percent = True
    elif cat_count_uop > 1:
        ES_partial = True

# number of cats
number_of_cats = 0
if len(CatwordsFinal)>0:
    number_of_cats = len(CatwordsFFinal)
else:
    number_of_cats = cat_count_uop

# threshold params
similarity_threshold = 0.0
cleanup_threshold = 0.0
if language == 'EN':
    similarity_threshold = sim_th_en
    cleanup_threshold = cleanup_TH_en
elif language == 'ES':
    similarity_threshold = sim_th_es
    cleanup_threshold = cleanup_TH_es
elif language == 'PT':
    similarity_threshold = sim_th_pt
    cleanup_threshold = cleanup_TH_pt    

columns = ['pdfname', 'nlp_path', 'language', 'similarity_threshold', 'cleanup_threshold', 'ES_0_percent', 'ES_100_percent', 'ES_partial', 'number_of_cats']
pred_train_rpts = pd.DataFrame(columns=columns)
pred_train_rpts.loc[len(pred_train_rpts)] = [pdfname, nlp_path, language, similarity_threshold, cleanup_threshold, ES_0_percent, ES_100_percent, ES_partial, number_of_cats]

Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__in_2021
categories from UOP portion

In [353]:
# run the pdf through the pipeline - subsequent pdfs, populate the dataframes


# input parameters
filepath = '/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/PDFs/'
extention = '.pdf'
language = 'ES'
tableStrategy = 'lines'

for pdf in pdf_es_lines:
    document = filepath + pdf + extention

    # call the functions in sequence
    filename, pdfname, tableCount, tablePages, tableHeaders, tableDFs = catTable(document, tableStrategy)
    uniqueCatsNoDupes, table_idx = tableAssess(language, tableCount, tablePages, tableHeaders, tableDFs)
    CatwordsFFinal, CatwordsFinal, dfsimScores_cln, simScores_cln, dfresimScores, resimScores, energy_system_tbl, cleanup_TH_en, cleanup_TH_es, cleanup_TH_pt = tableClean(language, uniqueCatsNoDupes) 
    results_UOP, results_SEEGP = fontInfo(language, document)
    max_idx_UOP, max_idx_SEEGP = find_max_font(results_UOP, results_SEEGP)
    areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0 = tocCheck(results_UOP, results_SEEGP, max_idx_UOP, max_idx_SEEGP)
    keep_areaSEEGP = keepSEEGP(areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0)
    UOPwordsNoDupes = wordsUOP(keep_areaSEEGP, document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0)

    # dataframe outputs for transparency on how pipeline has processed the pdf
    results_df.loc[len(results_df)] = [pdfname, language, tableCount, areaUOP_page, areaUOP_y1, areaSEEGP_page,areaSEEGP_y0, keep_areaSEEGP, len(UOPwordsNoDupes)]
    UOP_df.loc[len(UOP_df)] = [pdfname, results_UOP, max_idx_UOP, results_SEEGP, max_idx_SEEGP]

    # final Cateogory info
    if len(CatwordsFinal) == 0:
        print('')
        print(pdfname)
        print('categories from UOP portion')
        simsre, simsee, simsppc, simsesml, simstabc, simsct, simsswwm, simscca, simsce, simsgb, sim_th_en, sim_th_es, sim_th_pt, energy_system_uop, cat_count_uop = UOPwords_to_Catwords(language, UOPwordsNoDupes)
        UOP_Words_df.loc[len(UOP_Words_df)] = [pdfname, energy_system_uop, simsre, simsee, simsppc, simsesml, simstabc, simsct, simsswwm, simscca, simsce, simsgb]

        ttlsimsre |= simsre
        ttlsimsee |= simsee
        ttlsimsppc |= simsppc
        ttlsimsesml |= simsesml
        ttlsimstabc |= simstabc
        ttlsimsct |= simsct
        ttlsimsswwm |= simsswwm
        ttlsimscca |= simscca
        ttlsimsce |= simsce
        ttlsimsgb |= simsgb

    else:
        print('')
        print(pdfname)
        print('categories from tables')
        table_df.loc[len(table_df)] = [pdfname, tablePages, tableHeaders, len(CatwordsFFinal), CatwordsFFinal, energy_system_tbl, table_idx, uniqueCatsNoDupes, simScores_cln, resimScores]

        ttlresimScores |= resimScores
        ttlsimScores_cln |= simScores_cln


    # data table with results for evaluation to ground truth
    # nlp_path 
    nlp_path = ""
    if len(CatwordsFinal)>0:
        nlp_path = 'Table'
    elif len(CatwordsFinal)==0 and keep_areaSEEGP == True:
        nlp_path = 'UOP_section_true'
    elif len(CatwordsFinal)==0 and keep_areaSEEGP == False:
        nlp_path = 'UOP_section_false'

    # ES percent oucomes
    ES_0_percent = False
    ES_100_percent = False
    ES_partial = False

    if energy_system_tbl == False or energy_system_uop == False:
        ES_0_percent = True

    elif energy_system_tbl == True:
        if len(CatwordsFFinal) == 1:
            ES_100_percent = True
        elif len(CatwordsFFinal) > 1:
            ES_partial = True

    elif energy_system_uop == True:
        if cat_count_uop == 1:
            ES_100_percent = True
        elif cat_count_uop > 1:
            ES_partial = True

    # number of cats
    number_of_cats = 0
    if len(CatwordsFinal)>0:
        number_of_cats = len(CatwordsFFinal)
    else:
        number_of_cats = cat_count_uop

    # threshold params
    similarity_threshold = 0.0
    cleanup_threshold = 0.0
    if language == 'EN':
        similarity_threshold = sim_th_en
        cleanup_threshold = cleanup_TH_en
    elif language == 'ES':
        similarity_threshold = sim_th_es
        cleanup_threshold = cleanup_TH_es
    elif language == 'PT':
        similarity_threshold = sim_th_pt
        cleanup_threshold = cleanup_TH_pt

    
    pred_train_rpts.loc[len(pred_train_rpts)] = [pdfname, nlp_path, language, similarity_threshold, cleanup_threshold, ES_0_percent, ES_100_percent, ES_partial, number_of_cats]

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/3663279129.py:45: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simScore_cln = docCat.similarity(docx) # compare each cat phrase to all ref words

Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos_Verdes,_Sociales_o_Sostenibles_BDP_I
categories from UOP portion

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_6510/666106245.py:74: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = doca.similarity(docb)

In [354]:
results_df

,pdfname,language,tableCount,areaUOP_page,areaUOP_y1,areaSEEGP_page,areaSEEGP_y0,keep_areaSEEGP,countUOP_words
0,Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__i...,EN,1,1,420.328369,2,354.484863,True,188
1,Bci_Sustainable_Financing_Framework,EN,0,7,110.545990,1,28.432018,False,909
2,"BTG_Pactual_Green,_Social_and_Sustainable_Fina...",EN,4,14,406.338043,18,499.063019,True,327
3,BTG_Sustainable_Financing_Framework,EN,1,20,80.458229,31,60.549740,True,1311
4,CABEI_Green_Bond_Framework,EN,5,7,441.189972,11,81.259979,True,387
5,CADU_GREEN_BOND_FRAMEWORK,EN,0,6,140.128403,0,758.464783,False,578
6,CAFs_GREEN_BOND_FRAMEWORK,EN,6,7,262.438385,9,336.903778,True,271
7,CIFI_Green_Bond_Framework,EN,0,7,569.777405,8,169.974762,True,66
8,EGE_Haina_Green_Securities_Framework,EN,1,10,492.464996,12,428.401001,True,275
9,FS_Green_Bond_Framework_-_July_2021,EN,0,11,455.748077,5,223.619537,False,679
10,FS_Green_Bond_Framework_-_November_2020,EN,0,7,546.994019,7,403.429993,False,653
11,Genneia_Green_Bond_Framework,EN,0,8,110.361000,9,104.296997,True,169
12,Green_Bond_Financing_Framework,EN,3,7,179.089981,8,559.180054,True,186
13,Green_Bond_Framework_of_Banco_Guayaquil,EN,16,6,109.511734,11,71.712212,True,622
14,Green_Finance_Framework_Interchile,EN,1,7,321.529999,9,111.740021,True,210
15,Green_social_bond_framework_series_ad_ae_2019,EN,3,1,98.540031,1,87.500031,False,927
16,ILAP_Green_Financing_Framework,EN,0,0,481.347198,0,470.681610,False,910
17,ISA_CTM_FRAMEWORK,EN,11,8,271.757019,3,201.050018,False,503
18,Marco_de_referencia_de_Bonos_Verdes_Soberanos_...,EN,1,14,479.131409,19,351.234100,True,731
19,Nacional_Financiera_Green_Bond_USD,EN,1,3,123.770012,3,356.360016,True,84
20,Sicredi_Green_Bond_Framework,EN,2,3,402.529999,4,579.070007,True,236
21,SONDA_S_A__GREEN_BOND_FRAMEWORK,EN,0,4,124.099983,4,435.190002,True,124
22,Chile_Sustainable_Bond_Framework,EN,13,18,217.077713,3,216.104080,False,1443
23,Genneia_Green_Financing_Framework,EN,2,1,600.482239,0,0.000000,False,1267
24,Bono_Azul_-_Framework,ES,5,1,336.792603,1,390.216888,True,15
25,Bono_Verde_de_Bancoldex_Framework,ES,1,1,492.789978,3,365.630005,True,325
26,Cartilla_Bonos_Verdes,ES,0,10,433.616699,16,464.230499,True,497
27,Marco_de_Gestión_de_Bono_Verde,ES,3,7,411.209991,2,210.830017,False,400
28,Marco_de_referencia_de_bono_verde_Coopeguanaca...,ES,18,15,89.151588,16,541.706238,True,271
29,Marco_de_Referencia_del_Bono_Verde_de_la_Ciuda...,ES,0,0,490.869995,0,395.050018,False,818
30,Nacional_Financiera_Green_Bond_MXN,ES,6,3,188.569992,3,534.459961,True,99
31,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,ES,43,5,102.917595,32,535.163818,True,2949
32,Green_Bond_Framework,PT,5,1,304.611969,15,133.837967,True,1602
33,Green_Bonds_Framework_Athon_2020,PT,2,4,428.291565,6,551.981140,True,379
34,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,ES,43,5,102.917595,32,535.163818,True,2949

In [355]:
table_df

,pdfname,tablePages_list,table.Headers_list,countCat_words,unique compliant Categories_list,energy_system_tbl,table_idx_list,unique Cats all,simScores_cln,resimScores
0,"BTG_Pactual_Green,_Social_and_Sustainable_Fina...","[15, 16, 17, 19]","[[Green\nProject\nCategory, Use of\nProceeds, ...",4,"[clean transportation, green buildings, renewa...",True,"[0, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 3, 3]","[clean transportation, sustainable water and w...",{'clean transportation transportation': 0.8166...,{'renewable': 1.0}
1,CABEI_Green_Bond_Framework,"[7, 8, 9, 10, 12]","[[Eligible\nGreen\nProjects\nCategories, Sub-c...",2,"[renewable energy, water management]",True,"[0, 4, 4, 4, 4]","[clean transport, renewable energy, sustainabl...",{'renewable energy renewable': 0.9201155304908...,{'renewable': 1.0}
2,CAFs_GREEN_BOND_FRAMEWORK,"[1, 2, 8, 9]","[[Measure of Units, Col1], [Graphics, Content]...",3,"[clean transportation, renewable energy, waste...",True,"[2, 2, 2, 2]","[clean transportation, renewable energy, waste...",{'clean transportation transportation': 0.8166...,{'renewable': 1.0}
3,Green_Bond_Financing_Framework,"[7, 8, 10]",[[Eligible Category aligned\nwith ICMA Green B...,2,"[clean transportation, energy efficiency]",False,"[0, 2, 2]","[clean transportation, energy efficiency]",{'clean transportation transportation': 0.8166...,{}
4,Green_Bond_Framework_of_Banco_Guayaquil,"[6, 7, 8, 9, 10, 18, 19, 29, 30, 31, 38, 39]","[[GBP Eligible\nGreen Assets\nCategory, Banco ...",2,"[energy efficiency, renewable energy]",True,"[0, 1, 1, 1, 1]","[energy efficiency, renewable energy]",{'energy efficiency efficiency': 0.90048879384...,{'renewable': 1.0}
5,Green_Finance_Framework_Interchile,[8],"[[Eligible Project Category, Questions, Alignm...",2,"[energy efficiency, renewable energy]",True,"[0, 0, 0]","[renewable energy, energy efficiency, climate ...",{'renewable energy renewable': 0.9201155304908...,{'renewable': 1.0}
6,Green_social_bond_framework_series_ad_ae_2019,"[3, 6, 7]","[[Category, Project name, Goal], [Categories o...",2,"[potable water supply, sanitation]",False,"[0, 0, 0, 1, 1, 1]","[potable water supply, sanitation, resilient i...",{'potable water supply water': 0.8469440937042...,{}
7,ISA_CTM_FRAMEWORK,"[4, 5, 7, 8, 9, 15, 16, 17, 18]","[[Eligible Project Category, Questions, Alignm...",2,"[energy efficiency, renewable energy]",True,"[0, 0]","[energy efficiency, renewable energy]",{'energy efficiency efficiency': 0.90048879384...,{'renewable': 1.0}
8,Sicredi_Green_Bond_Framework,"[4, 6]","[[Eligible\nCategories, Description, Objective...",2,"[energy efficiency, renewable energy]",True,"[0, 0]","[energy efficiency, renewable energy]",{'energy efficiency efficiency': 0.90048879384...,{'renewable': 1.0}
9,Chile_Sustainable_Bond_Framework,"[0, 19, 20, 21, 22, 23, 24, 25, 26, 30, 37, 38...","[[Col0, Ministry of\nFinance\nGovernment of Ch...",5,"[energy efficiency, renewable energy, green bu...",True,"[5, 5, 5, 5, 6, 6, 7, 7, 7, 8, 8, 10, 10, 10, ...",[support for the community through job creatio...,{'energy efficiency efficiency': 0.90048879384...,{'renewable': 1.0}
10,Genneia_Green_Financing_Framework,"[5, 7]","[[Col0, 20161, 20202, 20251, 20301], [Eligible...",1,[renewable energy],True,[1],[renewable energy],{'renewable energy renewable': 0.9201155304908...,{'renewable': 1.0}
11,Nacional_Financiera_Green_Bond_MXN,"[3, 9, 10, 11, 17]","[[Categoría, Actividades elegibles], [Col0, Pr...",1,[centrales eólicas (solo terrestres)],False,"[0, 0]","[pequeñas centrales hidroeléctricas, centrales...",{'centrales eólicas (solo terrestres) cuadrícu...,{}
12,Green_Bond_Framework,"[10, 14, 19, 21, 22]","[[Categoria, Descrição], [Projeto, Capaci\nda ...",1,[energia renovável],True,"[0, 0]","[transmissão de energia, energia renovável]",{'energia renovável energia': 0.91402691602706...,{'energia': 1.0}

In [30]:
check11 = table_df.iloc[11].loc['simScores for ES']
check11

                  0
renewable  0.682400
power      0.657853
bioenergy  0.651106
biofuel    0.690298
biomass    0.675836

In [356]:
UOP_df

,pdfname,"results_UOP_list (text, fontSize, bbox, page_idx)",max_idx_UOP,"results_SEEGP_list (text, fontSize, bbox, page_idx)",max_idx_SEEGP
0,Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__i...,"[(Use of Proceeds , 11.039999961853027, (85.1...",0,[(Selection and Evaluation of Eligible Green P...,0
1,Bci_Sustainable_Financing_Framework,"[(Green Use of Proceeds instruments: , 9.0, (6...",10,"[(Process for , 9.0, (277.7300109863281, 28.43...",0
2,"BTG_Pactual_Green,_Social_and_Sustainable_Fina...","[(Use of Proceeds , 12.0, (184.590087890625, 6...",3,"[(Process for Project , 12.0, (184.59008789062...",5
3,BTG_Sustainable_Financing_Framework,"[(Use of Proceeds, 13.0, (241.72439575195312, ...",2,[(Process for Project Selection and Evaluation...,4
4,CABEI_Green_Bond_Framework,[(Use of Proceeds ...............................,1,[(Process for Project Evaluation and Selection...,3
5,CADU_GREEN_BOND_FRAMEWORK,"[(Use of Proceeds , 11.039999961853027, (84.98...",0,"[(selection processes; and, the reporting meth...",0
6,CAFs_GREEN_BOND_FRAMEWORK,[(1. Use of Proceeds ............................,2,[(2. Process for Project Evaluation and Select...,6
7,CIFI_Green_Bond_Framework,"[(a. Use of Proceeds, 12.531599998474121, (69....",0,"[(b. Project Selection Criteria , 12.531599998...",0
8,EGE_Haina_Green_Securities_Framework,"[(• Use of Proceeds\t, 10.0, (259.912902832031...",5,[(• Project Selection and Evaluation Process\t...,1
9,FS_Green_Bond_Framework_-_July_2021,"[(Use of Proceeds , 12.000450134277344, (110.6...",0,"[(theme within the company. Furthermore, in th...",0
10,FS_Green_Bond_Framework_-_November_2020,"[(Use of Proceeds , 12.0, (110.66000366210938,...",0,[(Capital Markets Association are voluntary pr...,0
11,Genneia_Green_Bond_Framework,"[( Use of Proceeds, 13.0, (253.3719940185547,...",1,"[(Process for Project Evaluation , 13.0, (269...",2
12,Green_Bond_Financing_Framework,"[(Use of Proceeds , 11.039999961853027, (108.0...",1,[(5.2 Process of Project Evaluation and S...,5
13,Green_Bond_Framework_of_Banco_Guayaquil,[(First Principle – Use of Proceeds .............,3,[(Second Principle – Process for Project Evalu...,6
14,Green_Finance_Framework_Interchile,[(4.1 Use of Proceeds ...........................,2,[(4.2 Process for Project Evaluation and Selec...,5
15,Green_social_bond_framework_series_ad_ae_2019,"[(SBPs: Use of Funds, Evaluation and Selection...",0,"[(SBPs: Use of Funds, Evaluation and Selection...",0
16,ILAP_Green_Financing_Framework,"[(1. Use of proceeds , 8.800000190734863, (77....",0,[( 2. Process for project evaluation and selec...,0
17,ISA_CTM_FRAMEWORK,"[(Use of the proceeds , 11.039999961853027, (1...",4,"[(Process for Evaluation and Selection , 11.03...",0
18,Marco_de_referencia_de_Bonos_Verdes_Soberanos_...,"[(Use of proceeds , 11.0, (360.3396911621094, ...",3,"[(Process for Project Evaluation and , 11.0, (...",5
19,Nacional_Financiera_Green_Bond_USD,"[(3.1 Use of Proceeds , 11.039999961853027, (9...",2,"[(3.2 Project Selection Process , 11.039999961...",1
20,Sicredi_Green_Bond_Framework,[(2.1 Use of Proceeds ...........................,2,[(2.2 Project evaluation & selection ............,3
21,SONDA_S_A__GREEN_BOND_FRAMEWORK,[(3.1 Use of Proceeds ...........................,1,[(3.2 Project Selection and Assessment Process...,1
22,Chile_Sustainable_Bond_Framework,"[(Use of Proceeds, 8.0, (311.42449951171875, 5...",2,"[(Project Evaluation , 11.0, (123.502014160156...",0
23,Genneia_Green_Financing_Framework,"[(Use of proceeds, 9.0, (73.48359680175781, 58...",0,[],0
24,Bono_Azul_-_Framework,"[(2.1 Uso de los recursos , 12.0, (41.13280105...",0,[(2.2 Proceso de evaluación y selección de pr...,0
25,Bono_Verde_de_Bancoldex_Framework,"[(Uso de los recursos , 12.0, (113.41999816894...",0,[(ingresos o recursos; (ii) proceso de evaluac...,2
26,Cartilla_Bonos_Verdes,"[(Uso de Fondos Proyectos Verdes Elegibles , 1...",3,"[(Procedimiento Selección y Evaluación , 12.0,...",2
27,Marco_de_Gestión_de_Bono_Verde,[(Uso de los Fondos .............................,2,[(Proceso de Selección y Evaluación de Proyect...,1
28,Marco_de_referencia_de_bono_verde_Coopeguanaca...,[(Destinos de Fondos. ...........................,1,[(Proceso de evaluación y selección de proyect...,2
29,Marco_de_Referencia_del_Bono_Verde_de_la_Ciuda...,"[(1. Uso de los Recursos , 12.0, (49.680000305...",0,[(2. Proceso de Evaluación y Selección de proy...,0
30,Nacional_Financiera_Green_Bond_MXN,"[(3.1. Uso de los Fondos , 11.039999961853027,...",1,[(3.2. Proceso de Evaluación y Selección de Pr...,2
31,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,[(Marco de uso de fondos para las emisiones de...,7,[(3.2. Selección y Evaluación de Proyectos ......,2
32,Green_Bond_Framework,"[(Usos dos Recursos , 12.0, (115.25, 291.32797...",0,"[(Avaliação e Seleção de Ativos , 12.0, (103.2...",0
33,Green_Bonds_Framework_Athon_2020,[(Uso de Recursos ...............................,2,[(Processo de Avaliação e Seleção de Projetos ...,1
34,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,[(Marco de uso de fondos para las emisiones de...,7,[(3.2. Selección y Evaluación de Proyectos ......,2

In [357]:
UOP_Words_df

,pdfname,energy_system_uop,simsre,simsee,simsppc,simsesml,simstabc,simsct,simsswwm,simscca,simsce,simsgb
0,Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__i...,True,"{'generation generation': 1.0, 'power power': ...",{},{},{},{},{},{},{},{},{}
1,Bci_Sustainable_Financing_Framework,True,"{'generation generation': 1.0, 'power power': ...",{'efficiency efficiency': 1.0},{'waste waste': 1.0},{},{},"{'electric electric': 1.0, 'car car': 1.0, 'tr...","{'water water': 1.0, 'potable potable': 1.0, '...",{},{},{'buildings buildings': 1.0}
2,BTG_Sustainable_Financing_Framework,True,"{'grid grid': 1.0, 'storage storage': 1.0, 're...",{'efficiency efficiency': 1.0},"{'pollution pollution': 1.0, 'waste waste': 1.0}","{'food food': 1.0, 'agriculture agriculture': ...","{'biodiversity biodiversity': 1.0, 'conservati...","{'electric electric': 1.0, 'rail rail': 1.0, '...","{'wastewater wastewater': 1.0, 'water water': ...",{'adaptation adaptation': 1.0},{},"{'buildings buildings': 1.0, 'housing housing'..."
3,CADU_GREEN_BOND_FRAMEWORK,False,{},{'efficiency efficiency': 1.0},{'waste waste': 1.0},{},{},{},{'water water': 1.0},{},{},"{'buildings buildings': 1.0, 'housing housing'..."
4,CIFI_Green_Bond_Framework,True,"{'power power': 1.0, 'renewable renewable': 1....",{},{'waste waste': 1.0},{},{},{},"{'treatment treatment': 1.0, 'wastewater waste...",{},{},{}
5,EGE_Haina_Green_Securities_Framework,True,"{'generation generation': 1.0, 'power power': ...",{},{},{'land land': 1.0},{},{'electric electric': 1.0},{'water water': 1.0},{},{},{}
6,FS_Green_Bond_Framework_-_July_2021,True,"{'generation generation': 1.0, 'storage storag...",{},{},"{'land land': 1.0, 'agriculture agriculture': ...",{},{'car car': 1.0},{'water water': 1.0},{},{},{}
7,FS_Green_Bond_Framework_-_November_2020,True,"{'generation generation': 1.0, 'storage storag...",{},{},"{'land land': 1.0, 'agriculture agriculture': ...",{},{'car car': 1.0},{'water water': 1.0},{},{},{}
8,Genneia_Green_Bond_Framework,True,"{'renewable renewable': 1.0, 'wind wind': 1.0,...",{},{},{},{},{'battery battery': 1.0},{},{},{},{}
9,ILAP_Green_Financing_Framework,True,"{'generation generation': 1.0, 'power power': ...",{},{'pollution pollution': 1.0},{},{'biodiversity biodiversity': 1.0},{},{},{},{},{}
10,Marco_de_referencia_de_Bonos_Verdes_Soberanos_...,True,"{'power power': 1.0, 'storage storage': 1.0, '...",{'efficiency efficiency': 1.0},"{'pollution pollution': 1.0, 'waste waste': 1.0}","{'agriculture agriculture': 1.0, 'forest fores...","{'conservation conservation': 1.0, 'biodiversi...","{'electric electric': 1.0, 'non non': 1.0, 'tr...","{'water water': 1.0, 'sanitation sanitation': ...","{'adaptation adaptation': 1.0, 'disaster disas...","{'reuse reuse': 1.0, 'circular circular': 1.0}",{'buildings buildings': 1.0}
11,Nacional_Financiera_Green_Bond_USD,True,"{'generation generation': 1.0, 'wind wind': 1....",{},{},{},{},{},{},{},{},{}
12,SONDA_S_A__GREEN_BOND_FRAMEWORK,True,"{'geothermal geothermal': 1.0, 'renewable rene...",{'efficiency efficiency': 1.0},{'waste waste': 1.0},{},{},{},{},{},{},{'buildings buildings': 1.0}
13,Bono_Azul_-_Framework,False,{},{},{},{},{},{},{},{},{},{}
14,Bono_Verde_de_Bancoldex_Framework,True,"{'generación generación': 1.0, 'almacenamiento...",{},{'contaminación contaminación': 1.0},{},{},"{'transporte transporte': 1.0, 'eléctricos elé...",{},{},{},{'construcciones construcciones': 1.0}
15,Cartilla_Bonos_Verdes,True,"{'generación generación': 1.0, 'almacenamiento...",{},{},{},{},"{'transporte transporte': 1.0, 'eléctricos elé...",{' potable': 1.0000001192092896},{},{},{}
16,Marco_de_Gestión_de_Bono_Verde,False,{},{},{},{},{},{},{},{},{},{}
17,Marco_de_referencia_de_bono_verde_Coopeguanaca...,True,"{'solar solar': 1.0, 'generación generación': ...",{},{},{},{},{'eléctricos eléctricos': 1.0},{},{},{},{}
18,Marco_de_Referencia_del_Bono_Verde_de_la_Ciuda...,True,"{'generación generación': 1.0, 'biomasa biomas...",{},{},{},{'biodiversidad biodiversidad': 1.0},{'transporte transporte': 1.0},{},{},{},{}
19,Green_Bonds_Framework_Athon_2020,True,"{'energia energia': 1.0, 'geração geração': 1.0}",{},{},{},{},{},{},{},{},{}
20,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,True,"{'potencia potencia': 1.0, 'renovable renovabl...",{},{'contaminación contaminación': 1.0},"{'alimentos alimentos': 1.0, 'bosque bosque': ...","{'biodiversidad biodiversidad': 1.0, 'conserva...","{'transporte transporte': 1.0, 'eléctricos elé...",{},{},{},{'construcciones construcciones': 1.0}

In [358]:
pred_train_rpts

,pdfname,nlp_path,language,similarity_threshold,cleanup_threshold,ES_0_percent,ES_100_percent,ES_partial,number_of_cats
0,Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__i...,UOP_section_true,EN,0.97,0.77,False,True,False,1
1,Bci_Sustainable_Financing_Framework,UOP_section_false,EN,0.97,0.77,False,False,True,6
2,"BTG_Pactual_Green,_Social_and_Sustainable_Fina...",Table,EN,0.97,0.77,False,False,True,4
3,BTG_Sustainable_Financing_Framework,UOP_section_true,EN,0.97,0.77,False,False,True,9
4,CABEI_Green_Bond_Framework,Table,EN,0.97,0.77,False,False,True,2
5,CADU_GREEN_BOND_FRAMEWORK,UOP_section_false,EN,0.97,0.77,True,False,False,4
6,CAFs_GREEN_BOND_FRAMEWORK,Table,EN,0.97,0.77,True,False,False,3
7,CIFI_Green_Bond_Framework,UOP_section_true,EN,0.97,0.77,False,False,True,3
8,EGE_Haina_Green_Securities_Framework,UOP_section_true,EN,0.97,0.77,False,False,True,4
9,FS_Green_Bond_Framework_-_July_2021,UOP_section_false,EN,0.97,0.77,False,False,True,4
10,FS_Green_Bond_Framework_-_November_2020,UOP_section_false,EN,0.97,0.77,False,False,True,4
11,Genneia_Green_Bond_Framework,UOP_section_true,EN,0.97,0.77,False,False,True,2
12,Green_Bond_Financing_Framework,Table,EN,0.97,0.77,True,False,False,2
13,Green_Bond_Framework_of_Banco_Guayaquil,Table,EN,0.97,0.77,False,False,True,2
14,Green_Finance_Framework_Interchile,Table,EN,0.97,0.77,False,False,True,2
15,Green_social_bond_framework_series_ad_ae_2019,Table,EN,0.97,0.77,True,False,False,2
16,ILAP_Green_Financing_Framework,UOP_section_false,EN,0.97,0.77,False,False,True,3
17,ISA_CTM_FRAMEWORK,Table,EN,0.97,0.77,False,False,True,2
18,Marco_de_referencia_de_Bonos_Verdes_Soberanos_...,UOP_section_true,EN,0.97,0.77,False,False,True,10
19,Nacional_Financiera_Green_Bond_USD,UOP_section_true,EN,0.97,0.77,False,True,False,1
20,Sicredi_Green_Bond_Framework,Table,EN,0.97,0.77,False,False,True,2
21,SONDA_S_A__GREEN_BOND_FRAMEWORK,UOP_section_true,EN,0.97,0.77,False,False,True,4
22,Chile_Sustainable_Bond_Framework,Table,EN,0.97,0.77,False,False,True,5
23,Genneia_Green_Financing_Framework,Table,EN,0.97,0.77,False,True,False,1
24,Bono_Azul_-_Framework,UOP_section_true,ES,0.97,0.77,True,False,False,0
25,Bono_Verde_de_Bancoldex_Framework,UOP_section_true,ES,0.97,0.77,False,False,True,4
26,Cartilla_Bonos_Verdes,UOP_section_true,ES,0.97,0.77,False,False,True,3
27,Marco_de_Gestión_de_Bono_Verde,UOP_section_false,ES,0.97,0.77,True,False,False,0
28,Marco_de_referencia_de_bono_verde_Coopeguanaca...,UOP_section_true,ES,0.97,0.77,False,False,True,2
29,Marco_de_Referencia_del_Bono_Verde_de_la_Ciuda...,UOP_section_false,ES,0.97,0.77,False,False,True,3
30,Nacional_Financiera_Green_Bond_MXN,Table,ES,0.97,0.77,True,False,False,1
31,Green_Bond_Framework,Table,PT,0.97,0.77,False,True,False,1
32,Green_Bonds_Framework_Athon_2020,UOP_section_true,PT,0.97,0.77,False,True,False,1
33,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,UOP_section_true,ES,0.97,0.77,False,False,True,6

In [359]:
import statistics
import numpy as np

In [341]:

cleanup_th_med = statistics.median(ttlsimScores_cln.values())
cleanup_th_25 = np.percentile(list(ttlsimScores_cln.values()), 25)
re_tbl_th_med = statistics.median(ttlresimScores.values())
re_tbl_th_25 = np.percentile(list(ttlresimScores.values()),25)
re_uop_th_med = statistics.median(ttlsimsre.values())
re_uop_th_25 = np.percentile(list(ttlsimsre.values()),25)
ee_uop_th_med = statistics.median(ttlsimsee.values())
ee_uop_th_25 = np.percentile(list(ttlsimsee.values()), 25)
cca_uop_th_med = statistics.median(ttlsimscca.values())
cca_uop_th_25 = np.percentile(list(ttlsimscca.values()), 25)
ppc_uop_th_med = statistics.median(ttlsimsppc.values())
ppc_uop_th_25 = np.percentile(list(ttlsimsppc.values()), 25)
tabc_uop_th_med = statistics.median(ttlsimstabc.values())
tabc_uop_th_25 = np.percentile(list(ttlsimstabc.values()), 25)
esml_uop_th_med = statistics.median(ttlsimsesml.values())
esml_uop_th_25 = np.percentile(list(ttlsimsesml.values()), 25)
ct_uop_th_med = statistics.median(ttlsimsct.values())
ct_uop_th_25 = np.percentile(list(ttlsimsct.values()), 25)
ce_uop_th_med = statistics.median(ttlsimsce. values())
ce_uop_th_25 = np.percentile(list(ttlsimsce. values()), 25)
swwm_uop_th_med = statistics.median(ttlsimsswwm.values())
swwm_uop_th_25 = np.percentile(list(ttlsimsswwm.values()), 25)
gb_uop_th_med = statistics.median(ttlsimsgb.values())
gb_uop_th_25 = np.percentile(list(ttlsimsgb.values()), 25)

In [360]:
V8_th_list = ['cleanup', cleanup_th_med, cleanup_th_25, 're_tbl', re_tbl_th_med, re_tbl_th_25, 're_uop',
              re_uop_th_med, re_uop_th_25, 'ee_uop', ee_uop_th_med, ee_uop_th_25, 'cca_uop', cca_uop_th_med, 
              cca_uop_th_25, 'ppc_uop', ppc_uop_th_med, ppc_uop_th_25, 'tabc_uop', tabc_uop_th_med, tabc_uop_th_25,
              'esml_uop', esml_uop_th_med, esml_uop_th_25, 'ct_uop', ct_uop_th_med, ct_uop_th_25, 'ce_uop', 
               ce_uop_th_med, ce_uop_th_25, 'swwm_uop', swwm_uop_th_med, swwm_uop_th_25, 'gb_uop', 
               gb_uop_th_med, gb_uop_th_25]

V8_th_list

['cleanup',
 0.7907696068286896,
 np.float64(0.7266973108053207),
 're_tbl',
 0.9762064516544342,
 np.float64(0.9414332658052444),
 're_uop',
 1.0,
 np.float64(0.9473557472229004),
 'ee_uop',
 1.0,
 np.float64(1.0),
 'cca_uop',
 1.0,
 np.float64(1.0),
 'ppc_uop',
 1.0,
 np.float64(0.9833246171474457),
 'tabc_uop',
 1.0,
 np.float64(1.0),
 'esml_uop',
 0.8981540203094482,
 np.float64(0.8884092569351196),
 'ct_uop',
 1.0,
 np.float64(1.0),
 'ce_uop',
 1.0,
 np.float64(1.0),
 'swwm_uop',
 1.0,
 np.float64(1.0),
 'gb_uop',
 1.0,
 np.float64(0.9901427030563354)]

In [361]:
columns = ['ttlsimScores_cln', 'ttlresimScores', 'ttlsimsre', 'ttlsimsee', 'ttlsimsppc', 'ttlsimsesml', 'ttlsimstabc', 'ttlsimsct', 'ttlsimscca', 'ttlsimsce', 'ttlsimsswwm', 'ttlsimsgb', 'V8_th_list']
sims_dicts_V8 = pd.DataFrame(columns=columns)
sims_dicts_V8.loc[len(sims_dicts_V8)] = [ttlsimScores_cln, ttlresimScores, ttlsimsre, ttlsimsee, ttlsimsppc, ttlsimsesml, ttlsimstabc, ttlsimsct, ttlsimscca, ttlsimsce, ttlsimsswwm, ttlsimsgb, V8_th_list]
sims_dicts_V8.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames/sims_dicts_V8.csv')

In [362]:
ttlsimScores_cln

{'clean transportation transportation': 0.8166900873184204,
 'renewable energy renewable': 0.9201155304908752,
 'green buildings buildings': 0.839942991733551,
 'afof rdable housing housing': 1.0,
 'water management water': 0.8119471073150635,
 'waste management waste': 0.8286465406417847,
 'energy efficiency efficiency': 0.9004887938499451,
 'potable water supply water': 0.8469440937042236,
 'potable water supply potable': 0.8287600874900818,
 'sanitation sanitation': 1.0,
 'green buildings (ecological buildings) buildings': 0.8016582131385803,
 'food security food': 0.7798810005187988,
 'centrales eólicas (solo terrestres) cuadrícula (sólo)': 0.8724079728126526,
 'energia renovável energia': 0.9140269160270691,
 'energia renovável energia hidráulica': 0.8522579669952393}

In [363]:
ttlresimScores

{'renewable': 1.0, 'energia': 1.0}

In [364]:
ttlsimsre

{'generation generation': 1.0,
 'power power': 1.0,
 'renewable renewable': 1.0,
 'solar solar': 1.0,
 'transmission transmission': 1.0,
 'storage storage': 1.0,
 'hydrogen hydrogen': 1.0,
 'grid grid': 1.0,
 'biofuel biofuel': 1.0,
 'wind wind': 1.0,
 'hydropower hydropower': 1.0,
 'biomass biomass': 1.0,
 'geothermal geothermal': 1.0,
 'generación generación': 1.0,
 'almacenamiento almacenamiento': 1.0,
 'renovable renovable': 1.0,
 'biomasa biomasa': 1.0,
 'energia energia': 1.0,
 'geração geração': 1.0,
 'potencia potencia': 1.0,
 'biocombustible biocombustible': 1.0}

In [365]:
ttlsimscca

{'adaptation adaptation': 1.0, 'disaster disaster': 1.0}

In [366]:
ttlsimsppc

{'waste waste': 1.0,
 'pollution pollution': 1.0,
 'contaminación contaminación': 1.0}

In [367]:
ttlsimsct

{'electric electric': 1.0,
 'car car': 1.0,
 'transportation transportation': 1.0,
 'rail rail': 1.0,
 'battery battery': 1.0,
 'vehicle vehicle': 1.0,
 'non non': 1.0,
 'transporte transporte': 1.0,
 'eléctricos eléctricos': 1.0}

In [368]:
ttlsimsee

{'efficiency efficiency': 1.0}

In [369]:
ttlsimsce

{'reuse reuse': 1.0, 'circular circular': 1.0}

In [370]:
ttlsimsesml

{'food food': 1.0,
 'agriculture agriculture': 1.0,
 'forest forest': 1.0,
 'land land': 1.0,
 'forestry forestry': 1.0,
 'alimentos alimentos': 1.0,
 'bosque bosque': 1.0}

In [371]:
ttlsimsswwm

{'water water': 1.0,
 'potable potable': 1.0,
 'treatment treatment': 1.0,
 'wastewater wastewater': 1.0,
 'sanitation sanitation': 1.0,
 '  potable': 1.0000001192092896}

In [372]:
ttlsimstabc

{'biodiversity biodiversity': 1.0,
 'conservation conservation': 1.0,
 'terrestrial terrestrial': 1.0,
 'biodiversidad biodiversidad': 1.0,
 'conservación conservación': 1.0,
 'terrestre terrestre': 1.0}

In [334]:
ttlsimsgb

{'buildings buildings': 1.0,
 'housing housing': 1.0,
 'construcciones construcciones': 1.0,
 'construcciones edificaciones': 0.9605708122253418}

In [373]:
# write dataframes to csvfiles with versions in the filenames

dataframes = [results_df, table_df, UOP_df, UOP_Words_df, pred_train_rpts]
dfname_list = ['results_df', 'table_df', 'UOP_df', 'UOP_Words_df', 'pred_train_rpts']
csvname_list = ['results_csv', 'table_csv', 'UOP_csv', 'UOP_Words_csv', 'pred_train_rpts_csv']
filepath = '/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames/'
extention = '.csv'
version = '8.0'


results_csv = results_df.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames/results_csv_V8.csv')
table_csv = table_df.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames/table_csv_V8.csv')
UOP_csv = UOP_df.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames/UOP_csv_V8.csv')
UOP_Words_csv = UOP_Words_df.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames/UOP_Words_csv_V8.csv')
pred_train_rpts_csv = pred_train_rpts.to_csv(path_or_buf='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames/pred_train_rpts_V8.csv')