In [2]:
import pandas as pd

2 cleanup_th_med = np.percentile(list(ttlsimScores_cln.values()), 50)
3 cleanup_th_25 = np.percentile(list(ttlsimScores_cln.values()), 25)
6 re_tbl_th_med = np.percentile(list(ttlresimScores.values()), 50)
7 re_tbl_th_25 = np.percentile(list(ttlresimScores.values()),25)
10 re_uop_th_med = np.percentile(list(ttlsimsre.values()), 50)
11 re_uop_th_25 = np.percentile(list(ttlsimsre.values()),25)
14 ee_uop_th_med = np.percentile(list(ttlsimsee.values()), 50)
15 ee_uop_th_25 = np.percentile(list(ttlsimsee.values()), 25)
18 cca_uop_th_med = np.percentile(list(ttlsimscca.values()), 50)
19 cca_uop_th_25 = np.percentile(list(ttlsimscca.values()), 25)
22 ppc_uop_th_med = np.percentile(list(ttlsimsppc.values()), 50)
23 ppc_uop_th_25 = np.percentile(list(ttlsimsppc.values()), 25)
26 tabc_uop_th_med = np.percentile(list(ttlsimstabc.values()), 50)
27 tabc_uop_th_25 = np.percentile(list(ttlsimstabc.values()), 25)
30 esml_uop_th_med = np.percentile(list(ttlsimsesml.values()), 50)
31 esml_uop_th_25 = np.percentile(list(ttlsimsesml.values()), 25)
34 ct_uop_th_med = np.percentile(list(ttlsimsct.values()), 50)
35 ct_uop_th_25 = np.percentile(list(ttlsimsct.values()), 25)
38 ce_uop_th_med = np.percentile(list(ttlsimsce. values()), 50)
39 ce_uop_th_25 = np.percentile(list(ttlsimsce. values()), 25)
42 swwm_uop_th_med = np.percentile(list(ttlsimsswwm.values()), 50)
43 swwm_uop_th_25 = np.percentile(list(ttlsimsswwm.values()), 25)
46 gb_uop_th_med = np.percentile(list(ttlsimsgb.values()), 50)
47 gb_uop_th_25 = np.percentile(list(ttlsimsgb.values()), 25)

In [ ]:
simDicts_output = pd.read_csv('/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames_2ndPass/sims_dicts_V4.csv')
simDicts = pd.DataFrame(simDicts_output)
V4_th_list = simDicts['V4_th_list']
V4_th_list_split = V4_th_list.str.split(',', expand=True)
V4_th_list_explode = V4_th_list.explode()
median_values = V4_th_list_split.iloc[:,[2,10,14]]
median_labels = V4_th_list_split.iloc[:,[0,8,12,]]
median_counts = V4_th_list_split.iloc[:,[1,9,13]]

,2,6,10,14,18,22,26,30,34,38,42,46
0,np.float64(0.7338055670261383),np.float64(0.7073158025741577),np.float64(0.6963879466056824),np.float64(0.6745208501815796),np.float64(0.724215567111969),np.float64(0.6897445023059845),np.float64(0.7029100656509399),np.float64(0.7436220049858093),np.float64(0.7292967736721039),np.float64(0.7198167145252228),np.float64(0.7020531296730042),np.float64(0.6907588243484497)

In [26]:
simDicts_output = pd.read_csv('/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames_2ndPass/sims_dicts_V5.csv')
simDicts = pd.DataFrame(simDicts_output)
V5_th_list = simDicts['V5_th_list']
V5_th_list_split = V5_th_list.str.split(',', expand=True)
V5_th_list_explode = V5_th_list.explode()
V5_th_list_split

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,['cleanup',38,np.float64(0.7338055670261383),np.float64(0.6936290115118027),'re_tbl',8,np.float64(0.9304536283016205),np.float64(0.8403543829917908),'re_uop',38,...,np.float64(1.0),np.float64(0.9139232337474823),'swwm_uop',9,np.float64(0.8658150434494019),np.float64(0.8477514386177063),'gb_uop',9,np.float64(0.9070735573768616),np.float64(0.8306095004081726)]

In [27]:
simDicts_output = pd.read_csv('/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames_2ndPass/sims_dicts_V6.csv')
simDicts = pd.DataFrame(simDicts_output)
V6_th_list = simDicts['V6_th_list']
V6_th_list_split = V6_th_list.str.split(',', expand=True)
V6_th_list_explode = V6_th_list.explode()
V6_th_list_split

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,['cleanup',28,np.float64(0.7907696068286896),np.float64(0.7266973108053207),'re_tbl',4,np.float64(0.9762064516544342),np.float64(0.9414332658052444),'re_uop',25,...,np.float64(1.0),np.float64(1.0),'swwm_uop',6,np.float64(1.0),np.float64(1.0),'gb_uop',6,np.float64(0.9802854061126709),np.float64(0.950408011674881)]

In [28]:
simDicts_output = pd.read_csv('/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames_2ndPass/sims_dicts_V7.csv')
simDicts = pd.DataFrame(simDicts_output)
V7_th_list = simDicts['V7_th_list']
V7_th_list_split = V7_th_list.str.split(',', expand=True)
V7_th_list_explode = V7_th_list.explode()
V7_th_list_split

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,['cleanup',15,np.float64(0.8469440937042236),np.float64(0.8226683139801025),'re_tbl',2,np.float64(1.0),np.float64(1.0),'re_uop',21,...,np.float64(1.0),np.float64(1.0),'swwm_uop',6,np.float64(1.0),np.float64(1.0),'gb_uop',3,np.float64(1.0),np.float64(1.0)]

In [37]:

simDicts_output = pd.read_csv('/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames_2ndPass/sims_dicts_V8.csv')
simDicts = pd.DataFrame(simDicts_output)
V8_th_list = simDicts['V8_th_list']
V8_th_list_split = V8_th_list.str.split(',', expand=True)
V8_th_list_explode = V8_th_list.explode()
tabcDict = simDicts['ttlsimstabc']
tabcDict

0    {'biodiversity biodiversity': 1.0, 'conservati...
Name: ttlsimstabc, dtype: str

In [42]:
medianlist = []
medianlist.append(V4_th_list_split.iloc[:,[6,34]])
countlist = []
countlist.append(V4_th_list_split.iloc[:,[5,33]])

print(medianlist)
print(countlist)

[                                6                                34
0   np.float64(0.7073158025741577)   np.float64(0.7292967736721039)]
[    5    33
0   19   66]